/************************************************************************/
/*JOB:      CO1J14 - CC_AGREEMENT_ME_SNAPSHOT                           */
/*VERSION:  CO1J14v01.sql                                               */
/*DATE VERSION IMPLEMENTED: 2015-10-02                                  */
/*DEPENDENCIES:                                                         */
/*C01J01                                                                */
/*C01J02                                                                */
/************************************************************************/

.SET ERRORLEVEL (2641,3603) SEVERITY 4, UNKNOWN SEVERITY 8

SET QUERY_BAND = 'ApplicationName=CC_Finance_daily_run;JobID=GRFD043;Worktype=TripleR;Version=LBG;' FOR SESSION;

DATABASE CC_COBRA;

/*STEP 01: CHECK PRIOR JOBS FOR COMPLETION*/

/*INITIAL CHECKS TO SEE IF DAILY LOAD IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J01';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*CHECK TO SEE IF PROCESSING LAST WORKING DAY OF MONTH*/

SELECT * FROM CC_COBRA.GRID_REPORTS_CONTROL 
WHERE (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT) = PRIOR_WORKDAY_DT
AND WORKDAY_OF_MONTH = 1;

.IF ACTIVITYCOUNT = 0 THEN .GOTO SKIPJOB;


/*INITIAL CHECKS TO SEE IF ADDED DATE IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J02';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF THIS JOB HAS ALREADY RUN SUCCESSFULLY*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J14';

.IF ACTIVITYCOUNT <> 0 THEN .GOTO SKIPJOB;

/*SET THE STATUS START DT/TM*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
FROM CC_COBRA.CC_COBRA_LOAD_STATUS A
SET RUN_ID = A.RUN_ID
,   LOAD_STATUS = 'I'
,   LOAD_START_DT = DATE
,   LOAD_START_TM = TIME
WHERE CC_COBRA.CC_COBRA_LOAD_LOG.GRID_LOAD_ID = 'C01J14'
AND   A.RUN_STATUS = 'I'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*STEP 02: UPDATE DATE PARAMETER TABLE*/

/*
CREATE SET TABLE CC_COBRA.WK_C01J14_REPORT_DATE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      REPORT_DT DATE FORMAT 'YY/MM/DD')
UNIQUE PRIMARY INDEX ( REPORT_DT );
*/

UPDATE CC_COBRA.WK_C01J14_REPORT_DATE
SET REPORT_DT = (SELECT ADD_MONTHS(CAST(((SOURCE_START_DT/100*100)+1)AS DATE),1)-1 FROM CC_COBRA.CC_COBRA_LOAD_START_DT);         
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.WK_C01J14_REPORT_DATE INDEX(REPORT_DT);

/*DISPLAY DATE INSERTED ABOVE FOR OUTPUT*/

SELECT * FROM CC_COBRA.WK_C01J14_REPORT_DATE;


/*
DROP TABLE  CC_COBRA.CC_AGREEMENT_ME_SNAPSHOT;
CREATE TABLE CC_COBRA.CC_AGREEMENT_ME_SNAPSHOT (
AGRMNT_ID INT
,PERIOD_END_DT DATE
,BLOCK_CD_1 CHAR(1) COMPRESS ('C',NULL,'Z','L','W','Y','I','U','D','G')
,BLOCK_CD_2 CHAR(1) COMPRESS (NULL,'Q','Z','P','N','G','C')
,INT_STATUS_CD CHAR(1) COMPRESS(NULL,'A','F','8','Z','D','X','9','T')
,ME_BAL_AM DECIMAL(15,2) COMPRESS(0,5.00)
,CREDIT_LIMIT_AM DECIMAL(15,2) COMPRESS (0.00,-1000.00,-500.00,-200.00,-15000.00,-3000.00,-5000.00,-1500.00,-2500.00,-2000.00,-10000.00,-4000.00,-3500.00,-4500.00,-6000.00,-7000.00,-8000.00,-2250.00,-5500.00,-2750.00,-6500.00,-7500.00,-9000.00,-750.00,-1250.00,-12000.00,-3250.00,-1750.00,-8500.00,-3750.00,-4750.00,-4800.00,-4250.00,-9500.00)
,TEMP_CREDIT_LMIIT_AM DECIMAL(15,2) COMPRESS (0.00)
) PRIMARY INDEX (AGRMNT_ID)
;
*/

DELETE FROM CC_COBRA.CC_AGREEMENT_ME_SNAPSHOT 
WHERE PERIOD_END_DT IN (SELECT REPORT_DT FROM CC_COBRA.WK_C01J14_REPORT_DATE);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.CC_AGREEMENT_ME_SNAPSHOT
SELECT 
A.AGRMNT_ID
,D.REPORT_DT
,BC1.AGRMNT_STATUS_SUMMRY_VL
,BC2.AGRMNT_STATUS_SUMMRY_VL
,I.AGRMNT_STATUS_SUMMRY_VL
,ZEROIFNULL(B.BL_SUMMRY_AM)
,ZEROIFNULL(C.CREDIT_LIMIT_AM)
,ZEROIFNULL(T.CREDIT_LIMIT_AM)

FROM 		CC_COBRA.CC_AGREEMENT_ADDED_DATE A
JOIN        CC_COBRA.WK_C01J14_REPORT_DATE D
ON          A.ADDED_DT <= D.REPORT_DT
LEFT JOIN 	GDW_VIEWS.AGREEMENT_STATUS_SUMMARY BC1
ON      	A.AGRMNT_ID = BC1.AGRMNT_ID
AND         BC1.AGRMNT_STATUS_SUMMRY_TYPE_CD = '00500023'
AND  		D.REPORT_DT BETWEEN BC1.SOURCE_START_DT AND BC1.SOURCE_END_DT-1
LEFT JOIN 	GDW_VIEWS.AGREEMENT_STATUS_SUMMARY BC2
ON      	A.AGRMNT_ID = BC2.AGRMNT_ID
AND         BC2.AGRMNT_STATUS_SUMMRY_TYPE_CD = '00500024'
AND  		D.REPORT_DT BETWEEN BC2.SOURCE_START_DT AND BC2.SOURCE_END_DT-1
LEFT JOIN 	GDW_VIEWS.AGREEMENT_STATUS_SUMMARY I
ON      	A.AGRMNT_ID = I.AGRMNT_ID
AND         I.AGRMNT_STATUS_SUMMRY_TYPE_CD = '00500026'
AND  		D.REPORT_DT BETWEEN I.SOURCE_START_DT AND I.SOURCE_END_DT-1
LEFT JOIN   GDW_VIEWS.CC_AGREEMENT_BALANCE_SUMMARY B
ON      	A.AGRMNT_ID = B.AGRMNT_ID
AND         B.BL_SUMMRY_AM_CD = '00500003'
AND  		D.REPORT_DT BETWEEN B.SOURCE_START_DT AND B.SOURCE_END_DT-1
LEFT JOIN   GDW_VIEWS.AGREEMENT_CREDIT_LIMIT C
ON      	A.AGRMNT_ID = C.AGRMNT_ID
AND         C.LIMIT_TYPE_CD = '00000001'
AND  		D.REPORT_DT BETWEEN C.SOURCE_START_DT AND C.SOURCE_END_DT-1
LEFT JOIN   GDW_VIEWS.AGREEMENT_CREDIT_LIMIT T
ON      	A.AGRMNT_ID = T.AGRMNT_ID
AND         T.LIMIT_TYPE_CD = '00000003'
AND  		D.REPORT_DT BETWEEN T.SOURCE_START_DT AND T.SOURCE_END_DT-1

;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_AGREEMENT_ME_SNAPSHOT INDEX(AGRMNT_ID);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*UPDATE THE LOG TABLE IF IT HAS RUN OK!*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  CURRENT_LOAD_DT = (SELECT START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , UPDATE_DT = DATE
   , UPDATE_TM = TIME
   , LOAD_STATUS = 'C'
WHERE GRID_LOAD_ID = 'C01J14'
;

SELECT GRID_LOAD_ID, CURRENT_BUS_DT, CURRENT_LOAD_DT   
FROM CC_COBRA.CC_COBRA_LOAD_LOG WHERE GRID_LOAD_ID = 'C01J14';

.QUIT;

.LABEL SKIPJOB;

.QUIT;

.LABEL GRIDERROR;

.QUIT;

.LABEL FOUNDERROR;

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  LOAD_STATUS = 'F'
WHERE GRID_LOAD_ID = 'C01J14'
;

.QUIT;

