/************************************************************************/
/*JOB:      C01J03 - TRNSCN_DERVTN_GROUPS                               */
/*VERSION:  C01J03v04 - change to 10002 data format.sql                 */
/*DATE VERSION IMPLEMENTED: 2017-11-21                                  */
/*DEPENDENCIES:                                                         */
/*C01J01                                                                */
/*                                                                      */
/*                                                                      */
/************************************************************************/

.SET ERRORLEVEL (2641,3603) SEVERITY 4, UNKNOWN SEVERITY 8

SET QUERY_BAND = 'ApplicationName=CC_Finance_daily_run;JobID=GRFD043;Worktype=TripleR;Version=LBG;' FOR SESSION;

DATABASE CC_COBRA;

/*STEP 01: INITIAL CHECKS TO SEE IF DAILY LOAD IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J01';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*STEP 02: INITIAL CHECKS TO SEE IF THIS PARTICULAR JOB HAS ALREADY RUN SUCCESSFULLY*/
/*IF THERE IS ALREADY DATA IT WILL SKIP THE JOB*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J03';

.IF ACTIVITYCOUNT <> 0 THEN .GOTO SKIPJOB;

/*SET THE STATUS START DT/TM*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
FROM CC_COBRA.CC_COBRA_LOAD_STATUS A
SET RUN_ID = A.RUN_ID
,   LOAD_STATUS = 'I'
,   LOAD_START_DT = DATE
,   LOAD_START_TM = TIME
WHERE CC_COBRA.CC_COBRA_LOAD_LOG.GRID_LOAD_ID = 'C01J03'
AND   A.RUN_STATUS = 'I'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*STEP 03: COLLECT ALL DATES THAT HAVE NOT BEEN RUN YET FROM LOAD_START_DT TO END OF FOLLOWING MONTH - HELPS WITH CATCH UP RERUNNING*/
/*
CREATE SET TABLE CC_COBRA.WK_C01J03_DATE_CONTROL ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      REPORT_DT DATE FORMAT 'YYYY-MM-DD')
UNIQUE PRIMARY INDEX ( REPORT_DT );
*/

DELETE FROM CC_COBRA.WK_C01J03_DATE_CONTROL ALL;

INSERT INTO CC_COBRA.WK_C01J03_DATE_CONTROL
SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.WK_C01J03_DATE_CONTROL INDEX(REPORT_DT);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*STEP 03: CREATE TABLE TO HOLD ALL TRANSCTIONS FOR TODAY'S PROCESSING DATE*/

/*
CREATE SET TABLE CC_COBRA.CC_MONETARY_TRANSACTION_TODAY
     (
      AGRMNT_ID INTEGER,
      EVENT_ID BIGINT NOT NULL,
      ISO_MRCHNT_CATGRY_CD CHAR(8) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS (NULL,'        ','0       ','2741    ','3246    ','4112    ','4131    ','4411    ','4511    ','4722    ','4784    ','4812    ','4814    ','4816    ','4899    ','4900    ','5045    ','5200    ','5211    ','5231    ','5251    ','5261    ','5300    ','5309    ','5310    ','5311    ','5331    ','5399    ','5411    ','5499    ','5511    ','5532    ','5533    ','5541    ','5542    ','5611    ','5621    ','5631    ','5641    ','5651    ','5655    ','5661    ','5691    ','5699    ','5712    ','5713    ','5714    ','5719    ','5722    ','5732    ','5733    ','5734    ','5735    ','5812    ','5813    ','5814    ','5912    ','5921    ','5940    ','5941    ','5942    ','5943    ','5944    ','5945    ','5946    ','5947    ','5964    ','5965    ','5967    ','5968    ','5969    ','5970    ','5977    ','5992    ','5994    ','5995    ','5999    ','6010    ','6011    ','6012    ','6300    ','7011    ','7033    ','7230    ','7299    ','7372    ','7399    ','742     ','7512    ','7523    ','7538    ','7832    ','7841    ','7922    ','7991    ','7995    ','7997    ','7999    ','8021    ','8043    ','8220    ','8398    ','8699    ','8999    ','9399    ','9402    ','9751    ','9752    '),
      MRCHNT_CATGRY_LEVEL_CD CHAR(8) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS (NULL,'        ','005     ','005  CT1','005  CT6','005  NA ','005  POI'),
      MRCHNT_DS CHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS (NULL,' PAYMENT RECEIVED - THAN                ',' PAYMENT RECEIVED - THANK YOU           ','ADJUSTMENT TO PAYMENT                   ','AMAZON SVCS EU-UK                       ','AMAZON.CO.UK                            ','AMAZON.CO.UK RETAIL    SLOUGH        826','AN ADJUSTMENT TO YOUR AC                ','AOL ONLINE SERVICE                      ','ARGOS LTD                               ','ASDA STORES                             ','ASDA STORES LTD                         ','ASDA SUPERSTORE                         ','ATM BARCLAYS BANK PLC                   ','Amazon *Mktplce EU-UK  AMAZON.CO.UK  LUX','Amazon EU                               ','Amazon EU              AMAZON.CO.UK  GBR','Amazon EU              AMAZON.CO.UK  LUX','Amazon Svcs EU-UK                       ','B & Q                                   ','B & Q SUPERCENTRE                       ','B & Q WAREHOUSE                         ','BALANCE TRANSFER                        ','BARCLAYS BANK PLC                       ','BHS LTD                                 ','BOOTS THE CHEMIST                       ','CASH ADVANCE                            ','CASH ADVANCE HANDLING CH                ','CREDIT COVER PREMIUM - 7                ','DEBENHAMS                               ','DIRECT DEBIT PAYMENT  00                ','DIRECT DEBIT PAYMENT  01                ','DIRECT DEBIT PAYMENT  02                ','DIRECT DEBIT PAYMENT - THANK YOU        ','DIRECT DEBIT RECEIVED                   ','DIRECT DEBIT RECEIVED-                  ','FOCUS DIY                               ','HMV UK LTD                              ','ICELAND                                 ','INTEREST                                ','INTEREST AT 2.210% PER M                ','INTEREST RATE   0.403% P                ','INTEREST RATE   0.482% P                ','INTEREST RATE   0.561% P                ','INTEREST RATE   0.639% P                ','ITUNES MUSIC                            ','LATE CHARGES                            ','LLOYDS TSB AD CVR                       ','LLOYDSTSB BANK PLC C/P                  ','MARKS & SPENCER                         ','MATALAN                                 ','MORRISON PETROL                         ','NATWEST BANK                            ','NATWEST BANK  /                         ','O2(UK)LTD PREPAY                        ','OVERLIMIT CHARGE                        ','OVERLIMIT IN THE LAST MO                ','PAYMENT RECEIVED                        ','PAYMENT RECEIVED - THANK YOU            ','PC WORLD                                ','PLAY.COM                                ','PLAY.COM               JERSEY        GBR','PRIMARK                                 ','PRIVACYGUARD                            ','Promotional Offer Fee                   ','QVC                                     ','QVC                    LIVERPOOL MER GBR','ROYAL BANK UK /                         ','ROYAL BK OF SCOTLAND                    ','SAINSBURYS                              ','SAINSBURYS PETROL                       ','SAINSBURYS SMKT                         ','SAINSBURYS-PFS                          ','SALE REVERSAL                           ','SIT-UP AUCTION CHANNEL                  ','SKY SUBSCRIPTION                        ','SOMERFIELD                              ','SPORTS WORLD                            ','SUPERDRUG STORES PLC                    ','Sainsburys-PFS                          ','T K MAXX                                ','TESCO PETROL FILLING STA                ','TESCO STORES                            ','TFL MFM                                 ','W M MORRISON                            ','W M MORRISON PLC                        ','W M MORRISONS                           ','WAITROSE                                ','WATERSTONES                             ','WH SMITH                                ','WICKES                                  ','WILKINSON                               ','WM MORRISONS                            ','WOOLWORTHS PLC                          '),
      TRNSCN_DISCNT_AM DECIMAL(15,2) COMPRESS (0.00, NULL) ,
      TRNSCN_EXCHNG_RT DECIMAL(13,6) COMPRESS (0.000000,NULL) ,
      FRAUD_MATCHD_IN CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS (' ','N',NULL),
      MRCHNT_CONTRY_CD CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('   ','GBR',NULL),
      POSTNG_DT DATE FORMAT 'YYYY/MM/DD',
      CARD_TRNSCN_REFRNC_NO VARCHAR(23) CHARACTER SET LATIN NOT CASESPECIFIC,
      ROLLED_AM DECIMAL(15,2) COMPRESS (0.00 ,-20.00, NULL ),
      ELCTRC_COMMRC_CD CHAR(8) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS (NULL,'005     ','0050    ','00500000','00500002','00500006','0050000C','0050000F','0050000S','0051    ','0052    ','0056    ','005C    ','005F    ','005S    '),
      TRNSCN_SEQUNC_NO INTEGER COMPRESS (0 ,1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10 ,11 ,12 ,13 ,14 ,15 ,16 ,17 ,18 ,19 ,20 ,21 ,22 ,23 ,24 ,25 ,26 ,27 ,28 ,29 ,999 ),
      RCRRNG_TRNSCN_IN CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS (NULL,'N','Y'),
      RCRRNG_MRCHNT_CATGRY_CD_IN CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS (NULL,'N','Y'),
      CARD_IN_HAND_NO CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS '                   ',
      PAYMNT_TYPE_CD CHAR(8) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('005     ','005    P'),
      TRNSCN_CRRNCY_CD CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ,
      TRNSCN_CATGRY_CD CHAR(8) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('005    G','005    P'),
      TRNSCN_CRRNCY_AM DECIMAL(15,2) COMPRESS ,
      EVENT_START_DT DATE FORMAT 'YYYY/MM/DD',
      EVENT_START_TM INTEGER FORMAT '99:99:99' COMPRESS ,
      EVENT_ACTVTY_CD CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('00500001  ','00500002  ','00500176  ','00505101  ','00505107  ','00505109  ','00505125  ','00505138  ','00505243  ','00505913  ','00508053  ','00508102  ','00508110  ','00508112  ','00508138  ','00508175  ','00508908  ','005ZA253  ','005ZA254  ','005ZA272  ','005ZA961  ','005ZA962  ','005ZA963  ','005ZA986  ','005ZA988  ','005ZB256  ','005ZC255  ','005ZC271  ','005ZD253  ','005ZF280  ','005ZN253  '),
      EVENT_CATGRY_CD CHAR(8) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS '00000005',
      EVENT_AM DECIMAL(15,2) COMPRESS (-23.00 ,-2.50 ,-5.00 ,-4.99 ,100.00 ,-28.00 ,-7.50 ,-10.00 ,-9.99 ,-9.98 ,-33.00 ,-9.95 ,-12.50 ,200.00 ,-120.00 ,-15.00 ,-14.99 ,90.00 ,-38.00 ,-17.50 ,-20.01 ,300.00 ,-20.00 ,-19.99 ,-19.98 ,-22.50 ,-2.00 ,-25.00 ,-24.99 ,-4.50 ,80.00 ,400.00 ,-48.00 ,-7.00 ,-6.99 ,-30.00 ,-29.99 ,75.00 ,500.00 ,-12.00 ,-11.99 ,-11.98 ,-35.00 ,-34.99 ,70.00 ,-250.00 ,-17.00 ,-16.99 ,-40.00 ,-39.99 ,-19.50 ,-150.00 ,-22.00 ,-45.00 ,60.00 ,-4.00 ,-3.99 ,-27.00 ,-50.00 ,-49.99 ,-9.00 ,-8.99 ,-32.00 ,-55.00 ,50.00 ,-14.00 ,-13.99 ,-13.98 ,-37.00 ,-60.00 ,45.00 ,-19.00 ,150.00 ,-42.00 ,-65.00 ,-1.00 ,40.00 ,1000.00 ,-24.00 ,250.00 ,-70.00 ,-6.00 ,-5.99 ,35.00 ,-29.00 ,-5.95 ,-8.50 ,12.00 ,-500.00 ,-75.00 ,-11.00 ,-10.99 ,30.00 ,-34.00 ,-80.00 ,-16.00 ,-15.99 ,-15.98 ,25.00 ,-39.00 ,-21.00 ,20.00 ,-300.00 ,-44.00 ,-3.00 ,-2.99 ,-90.00 ,-26.00 ,15.00 ,-49.00 ,120.00 ,-200.00 ,-8.00 ,-7.99 ,-31.00 ,10.00 ,-13.00 ,-12.99 ,-100.00 ,-36.00 ,5.00 ,110.00 ,-18.00 ,-17.99 ,-17.98 ,-41.00 ,-0.01 ),
      EVENT_AM_TYPE_IN CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'Y',
      CONTLS_PAYMNT_IN CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS (' ','N','Y'),
      SOURCE_START_DT DATE FORMAT 'YYYY/MM/DD',
      SOURCE_START_TM INTEGER FORMAT '99:99:99' DEFAULT NULL  COMPRESS ,
      START_DT DATE FORMAT 'YYYY/MM/DD' NOT NULL,
      START_TM INTEGER FORMAT '99:99:99' NOT NULL DEFAULT 1  COMPRESS 0,
      PLAN_NO INTEGER COMPRESS (10001 ,10002 ) )
PRIMARY INDEX ( AGRMNT_ID )
PARTITION BY RANGE_N(SOURCE_START_DT  BETWEEN DATE '1995-01-01' AND DATE '2020-12-31' EACH INTERVAL '1' MONTH )
UNIQUE INDEX ( EVENT_ID );
*/

DELETE FROM CC_COBRA.CC_MONETARY_TRANSACTION_TODAY ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*INSERT ALL THE DAYS TXNS WITH A VALUE OF 10002 (MOST COMMON)*/

INSERT INTO CC_COBRA.CC_MONETARY_TRANSACTION_TODAY
SELECT
	A.AGRMNT_ID
,	A.EVENT_ID
,	A.ISO_MRCHNT_CATGRY_CD
,	A.MRCHNT_CATGRY_LEVEL_CD
,	A.MRCHNT_DS
,	A.TRNSCN_DISCNT_AM
,	A.TRNSCN_EXCHNG_RT
,	A.FRAUD_MATCHD_IN
,	A.MRCHNT_CONTRY_CD
,	A.POSTNG_DT
,	A.CARD_TRNSCN_REFRNC_NO
,	A.ROLLED_AM
,	A.ELCTRC_COMMRC_CD
,	A.TRNSCN_SEQUNC_NO
,	A.RCRRNG_TRNSCN_IN
,	A.RCRRNG_MRCHNT_CATGRY_CD_IN
,	A.CARD_IN_HAND_NO
,	A.PAYMNT_TYPE_CD
,	A.TRNSCN_CRRNCY_CD
,	A.TRNSCN_CATGRY_CD
,	A.TRNSCN_CRRNCY_AM
,	A.EVENT_START_DT
,	A.EVENT_START_TM
,	A.EVENT_ACTVTY_CD
,	A.EVENT_CATGRY_CD
,	A.EVENT_AM
,	A.EVENT_AM_TYPE_IN
,	A.CONTLS_PAYMNT_IN
,	A.SOURCE_START_DT
,	A.SOURCE_START_TM
,	A.START_DT
,	A.START_TM
,   10002 AS PLAN_NO
FROM GDW_VIEWS.CC_MONETARY_TRANSACTION_HIST A
JOIN CC_COBRA.WK_C01J03_DATE_CONTROL B
ON   A.SOURCE_START_DT = B.REPORT_DT
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_MONETARY_TRANSACTION_TODAY INDEX ( AGRMNT_ID );
.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;
COLLECT STATS ON CC_COBRA.CC_MONETARY_TRANSACTION_TODAY INDEX ( EVENT_ID );
.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;
COLLECT STATS ON CC_COBRA.CC_MONETARY_TRANSACTION_TODAY COLUMN PARTITION;
.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*UPDATE WHERE THE VALUE IN AFE IS NOT 10002*/

UPDATE CC_COBRA.CC_MONETARY_TRANSACTION_TODAY
FROM
(SELECT A.EVENT_ID
       --,CAST(SUBSTR(DF.FEATUR_TX,4,5) AS INTEGER) AS PLAN_NO --Fell over 28.11.17. Eynon
       ,SUBSTR(DF.FEATUR_TX,4,5) AS PLAN_NO
FROM CC_COBRA.CC_MONETARY_TRANSACTION_TODAY A
JOIN  GDW_VIEWSX.AGREEMENT_FEATURE_EVENT AFE
ON         A.EVENT_ID = AFE.EVENT_ID
JOIN  GDW_VIEWSX.DESCRIPTIVE_FEATURE DF
ON         AFE.FEATUR_ID = DF.FEATUR_ID
AND        DF.EFFCTV_DT IS NULL ) A
SET PLAN_NO = A.PLAN_NO
WHERE CC_COBRA.CC_MONETARY_TRANSACTION_TODAY.EVENT_ID = A.EVENT_ID
--AND   A.PLAN_NO <> 10002 --Fell over 28.11.17. Eynon
AND   A.PLAN_NO <> '10002'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*UPDATE TO NULL WHERE THERE IS NO RECORD IN AFE*/

UPDATE CC_COBRA.CC_MONETARY_TRANSACTION_TODAY
FROM
(SELECT A.EVENT_ID
FROM CC_COBRA.CC_MONETARY_TRANSACTION_TODAY A
WHERE NOT EXISTS (
SELECT NULL
FROM  GDW_VIEWSX.AGREEMENT_FEATURE_EVENT AFE
WHERE A.EVENT_ID = AFE.EVENT_ID)
) A
SET PLAN_NO = NULL
WHERE CC_COBRA.CC_MONETARY_TRANSACTION_TODAY.EVENT_ID = A.EVENT_ID
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*STEP 04: CHECK FOR ANY TRANSACTIONS WITH TXN CODES THAT DON'T EXIST WITH CORRECT REFERENCE DATA*/

SELECT *
FROM CC_COBRA.CC_MONETARY_TRANSACTION_TODAY A
WHERE NOT EXISTS (
SEL NULL
FROM CC_COBRA.TRNSCN_DERVTN_GROUPS B
WHERE A.EVENT_ACTVTY_CD = B.EVENT_ACTVTY_CD
AND B.TRNSCN_DERVTN_GRP NOT IN ('UNKNOWN','NOT IN USE')
);

.IF ACTIVITYCOUNT <> 0 THEN .GOTO FOUNDERROR;

/*UPDATE THE LOAD LOG TO THE CURRENT DATE TO INDICATE SUCCESSFUL PROCESSING*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  CURRENT_LOAD_DT = (SELECT START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , UPDATE_DT = DATE
   , UPDATE_TM = TIME
   , LOAD_STATUS = 'C'
WHERE GRID_LOAD_ID = 'C01J03'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

SELECT GRID_LOAD_ID, CURRENT_BUS_DT, CURRENT_LOAD_DT  
FROM CC_COBRA.CC_COBRA_LOAD_LOG WHERE GRID_LOAD_ID = 'C01J03';

.QUIT;

.LABEL SKIPJOB;

.QUIT;

.LABEL GRIDERROR;

.QUIT;

.LABEL FOUNDERROR;

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  LOAD_STATUS = 'F'
WHERE GRID_LOAD_ID = 'C01J03'
;

.QUIT 0;