/************************************************************************/
/*JOB:      C01J21 - DISASTER RECOVERY                                  */
/*VERSION:  C01J21 - V1                                                 */
/*DATE VERSION IMPLEMENTED: 2020-08-05                                  */
/*DEPENDENCIES:                                                         */
/************************************************************************/

.SET ERRORLEVEL (2641,3603) SEVERITY 4, UNKNOWN SEVERITY 8

SET QUERY_BAND = 'ApplicationName=CC_Finance_daily_run;JobID=GRFD043;Worktype=TripleR;Version=LBG;' FOR SESSION;
   
DATABASE CC_COBRA;

/*STEP 00A: CHECK PRIOR JOBS FOR COMPLETION*/

/*INITIAL CHECKS TO SEE IF DAILY LOAD IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J01';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;


/*INITIAL CHECKS TO SEE IF THIS JOB HAS ALREADY RUN SUCCESSFULLY*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J21';

.IF ACTIVITYCOUNT <> 0 THEN .GOTO SKIPJOB;

/*SET THE STATUS START DT/TM*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
FROM CC_COBRA.CC_COBRA_LOAD_STATUS A
SET RUN_ID = A.RUN_ID
,   LOAD_STATUS = 'I'
,   LOAD_START_DT = DATE
,   LOAD_START_TM = TIME
WHERE CC_COBRA.CC_COBRA_LOAD_LOG.GRID_LOAD_ID = 'C01J21'
AND   A.RUN_STATUS = 'I'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*STEP 1 - GET COLUMN AND INDEX METADATA - THIS ASSISTS WITH AUDITING - PARTICULARLY WITH EMPTY TABLES*/

/*1.1 - COLUMN DATA*/

/*
CREATE TABLE CC_COBRA.SCHEDULED_TABLES_COLUMN_BOX_1 (
DATABASE_NM CHAR(30)
,TABLE_NM CHAR(30)
,COLUMN_NM CHAR(30)
,COLUMN_TYPE CHAR(2))
UNIQUE PRIMARY INDEX (DATABASE_NM,TABLE_NM,COLUMN_NM);
*/

DELETE FROM CC_COBRA.SCHEDULED_TABLES_COLUMN_BOX_1;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.SCHEDULED_TABLES_COLUMN_BOX_1
SELECT A.DATABASENAME
      ,A.TABLENAME
	  ,A.COLUMNNAME
	  ,A.COLUMNTYPE
FROM DBC_VIEWS_LBG.columns A
JOIN
(SELECT DATABASE_NM,TBL_NM,COUNT(*) AS L3M_VOL
FROM  CC_COBRA.CC_COBRA_TABLE_USAGE
WHERE  (TBL_LAST_ACCESS_BY_USER in ('CCSCHED1') OR SUBSTR(TBL_LAST_ACCESS_BY_USER,1,2)= 'BB')
AND CAST(TBL_LAST_ACCESS_TIME_STAMP AS DATE) >= ADD_MONTHS(DATE,-3)
GROUP BY 1,2
) L3M
ON A.DATABASENAME = L3M.DATABASE_NM
AND A.TABLENAME = L3M.TBL_NM
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.SCHEDULED_TABLES_COLUMN_BOX_1 INDEX (DATABASE_NM,TABLE_NM,COLUMN_NM);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*1.2 INDEX METADATA*/
/*
CREATE SET TABLE CC_COBRA.SCHEDULED_TABLES_INDICES_BOX_1 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      DATABASE_NM CHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      TABLE_NM CHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      COLUMN_NM CHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      IndexNumber SMALLINT,
      IndexType CHAR(1) CHARACTER SET LATIN UPPERCASE NOT CASESPECIFIC,
      UniqueFlag CHAR(1) CHARACTER SET LATIN UPPERCASE NOT CASESPECIFIC)
PRIMARY INDEX ( DATABASE_NM, TABLE_NM);
*/

DELETE FROM CC_COBRA.SCHEDULED_TABLES_INDICES_BOX_1;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.SCHEDULED_TABLES_INDICES_BOX_1
SELECT A.DATABASENAME
      ,A.TABLENAME
	  ,A.COLUMNNAME
	  ,A.INDEXNUMBER
	  ,A.INDEXTYPE
	  ,A.UNIQUEFLAG

FROM DBC_VIEWS_LBG.INDICES A
JOIN
(SELECT DATABASE_NM,TBL_NM,COUNT(*) AS L3M_VOL
FROM  CC_COBRA.CC_COBRA_TABLE_USAGE
WHERE  (TBL_LAST_ACCESS_BY_USER in ('CCSCHED1') OR SUBSTR(TBL_LAST_ACCESS_BY_USER,1,2)= 'BB')
AND CAST(TBL_LAST_ACCESS_TIME_STAMP AS DATE) >= ADD_MONTHS(DATE,-3)
GROUP BY 1,2
) L3M
ON A.DATABASENAME = L3M.DATABASE_NM
AND A.TABLENAME = L3M.TBL_NM 
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.SCHEDULED_TABLES_INDICES_BOX_1 INDEX ( DATABASE_NM, TABLE_NM);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*STEP 2 - WORK AROUND TO GET REFERENCE DATA TABLES COPIED ACROSS*/


/*COPY REFERENCE DATA TABLE INTO TEMP TABLE AND THEN CLEAR AND REINSERT BACK - THIS WILL FORCE THE DR PROCESS TO COPY THE TABLE WITH NO CHANGES*/

/***********************/
/* CC_COBRA.MCC_LOOKUP */
/***********************/

CREATE TABLE CC_COBRA.MCC_LOOKUP_C AS (
SELECT *
FROM  CC_COBRA.MCC_LOOKUP) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.MCC_LOOKUP ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.MCC_LOOKUP
SELECT * FROM CC_COBRA.MCC_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.MCC_LOOKUP
MINUS
SELECT * FROM CC_COBRA.MCC_LOOKUP_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.MCC_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.MCC_LOOKUP;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.CC_BT_ORG_PLAN_LOOKUP             */
/*********************************************/

CREATE TABLE CC_COBRA.CC_BT_ORG_PLAN_LOOKUP_C AS (
SELECT *
FROM  CC_COBRA.CC_BT_ORG_PLAN_LOOKUP) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.CC_BT_ORG_PLAN_LOOKUP ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.CC_BT_ORG_PLAN_LOOKUP
SELECT * FROM CC_COBRA.CC_BT_ORG_PLAN_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.CC_BT_ORG_PLAN_LOOKUP
MINUS
SELECT * FROM CC_COBRA.CC_BT_ORG_PLAN_LOOKUP_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.CC_BT_ORG_PLAN_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_BT_ORG_PLAN_LOOKUP;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.CC_BT_ORG_PLAN_LOOKUP_HIST        */
/*********************************************/

CREATE TABLE CC_COBRA.CC_BT_ORG_PLAN_LOOKUP_HIST_C AS (
SELECT *
FROM  CC_COBRA.CC_BT_ORG_PLAN_LOOKUP_HIST) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.CC_BT_ORG_PLAN_LOOKUP_HIST ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.CC_BT_ORG_PLAN_LOOKUP_HIST
SELECT * FROM CC_COBRA.CC_BT_ORG_PLAN_LOOKUP_HIST_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.CC_BT_ORG_PLAN_LOOKUP_HIST
MINUS
SELECT * FROM CC_COBRA.CC_BT_ORG_PLAN_LOOKUP_HIST_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.CC_BT_ORG_PLAN_LOOKUP_HIST_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_BT_ORG_PLAN_LOOKUP_HIST;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.CC_FD_CYCLE_CALENDAR              */
/*********************************************/

CREATE TABLE CC_COBRA.CC_FD_CYCLE_CALENDAR_C AS (
SELECT *
FROM  CC_COBRA.CC_FD_CYCLE_CALENDAR) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.CC_FD_CYCLE_CALENDAR ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.CC_FD_CYCLE_CALENDAR
SELECT * FROM CC_COBRA.CC_FD_CYCLE_CALENDAR_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.CC_FD_CYCLE_CALENDAR
MINUS
SELECT * FROM CC_COBRA.CC_FD_CYCLE_CALENDAR_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.CC_FD_CYCLE_CALENDAR_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_FD_CYCLE_CALENDAR;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.CC_FD_CYCLE_REPORT_CALENDAR       */
/*********************************************/

CREATE TABLE CC_COBRA.CC_FD_CYCLE_REPORT_CALENDAR_C AS (
SELECT *
FROM  CC_COBRA.CC_FD_CYCLE_REPORT_CALENDAR) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.CC_FD_CYCLE_REPORT_CALENDAR ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.CC_FD_CYCLE_REPORT_CALENDAR
SELECT * FROM CC_COBRA.CC_FD_CYCLE_REPORT_CALENDAR_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.CC_FD_CYCLE_REPORT_CALENDAR
MINUS
SELECT * FROM CC_COBRA.CC_FD_CYCLE_REPORT_CALENDAR_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.CC_FD_CYCLE_REPORT_CALENDAR_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_FD_CYCLE_REPORT_CALENDAR;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.CC_FD_REPORT_CONTROL              */
/*********************************************/

CREATE TABLE CC_COBRA.CC_FD_REPORT_CONTROL_C AS (
SELECT *
FROM  CC_COBRA.CC_FD_REPORT_CONTROL) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.CC_FD_REPORT_CONTROL ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.CC_FD_REPORT_CONTROL
SELECT * FROM CC_COBRA.CC_FD_REPORT_CONTROL_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.CC_FD_REPORT_CONTROL
MINUS
SELECT * FROM CC_COBRA.CC_FD_REPORT_CONTROL_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.CC_FD_REPORT_CONTROL_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_FD_REPORT_CONTROL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*********************************************/
/*CC_COBRA.CC_HIGH_CHANNL_CD                 */
/*********************************************/

CREATE TABLE CC_COBRA.CC_HIGH_CHANNL_CD_C AS (
SELECT *
FROM  CC_COBRA.CC_HIGH_CHANNL_CD) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.CC_HIGH_CHANNL_CD ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.CC_HIGH_CHANNL_CD
SELECT * FROM CC_COBRA.CC_HIGH_CHANNL_CD_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.CC_HIGH_CHANNL_CD
MINUS
SELECT * FROM CC_COBRA.CC_HIGH_CHANNL_CD_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.CC_HIGH_CHANNL_CD_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_HIGH_CHANNL_CD;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.CC_ISSUER_SORT_CODE_LOOKUP        */
/*********************************************/

CREATE TABLE CC_COBRA.CC_ISSUER_SORT_CODE_LOOKUP_C AS (
SELECT *
FROM  CC_COBRA.CC_ISSUER_SORT_CODE_LOOKUP) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.CC_ISSUER_SORT_CODE_LOOKUP ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.CC_ISSUER_SORT_CODE_LOOKUP
SELECT * FROM CC_COBRA.CC_ISSUER_SORT_CODE_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.CC_ISSUER_SORT_CODE_LOOKUP
MINUS
SELECT * FROM CC_COBRA.CC_ISSUER_SORT_CODE_LOOKUP_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.CC_ISSUER_SORT_CODE_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_ISSUER_SORT_CODE_LOOKUP;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.CC_L2CP_LOOKUP                    */
/*********************************************/

CREATE TABLE CC_COBRA.CC_L2CP_LOOKUP_C AS (
SELECT *
FROM  CC_COBRA.CC_L2CP_LOOKUP) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.CC_L2CP_LOOKUP ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.CC_L2CP_LOOKUP
SELECT * FROM CC_COBRA.CC_L2CP_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.CC_L2CP_LOOKUP
MINUS
SELECT * FROM CC_COBRA.CC_L2CP_LOOKUP_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.CC_L2CP_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_L2CP_LOOKUP;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.CC_LOAD_ORG_CHECK                 */
/*********************************************/

CREATE TABLE CC_COBRA.CC_LOAD_ORG_CHECK_C AS (
SELECT *
FROM  CC_COBRA.CC_LOAD_ORG_CHECK) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.CC_LOAD_ORG_CHECK ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.CC_LOAD_ORG_CHECK
SELECT * FROM CC_COBRA.CC_LOAD_ORG_CHECK_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.CC_LOAD_ORG_CHECK
MINUS
SELECT * FROM CC_COBRA.CC_LOAD_ORG_CHECK_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.CC_LOAD_ORG_CHECK_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_LOAD_ORG_CHECK ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.CC_ORG_SPECIAL_PLAN_LOOKUP        */
/*********************************************/

CREATE TABLE CC_COBRA.CC_ORG_SPECIAL_PLAN_LOOKUP_C AS (
SELECT *
FROM  CC_COBRA.CC_ORG_SPECIAL_PLAN_LOOKUP) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.CC_ORG_SPECIAL_PLAN_LOOKUP ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.CC_ORG_SPECIAL_PLAN_LOOKUP
SELECT * FROM CC_COBRA.CC_ORG_SPECIAL_PLAN_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.CC_ORG_SPECIAL_PLAN_LOOKUP
MINUS
SELECT * FROM CC_COBRA.CC_ORG_SPECIAL_PLAN_LOOKUP_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.CC_ORG_SPECIAL_PLAN_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_ORG_SPECIAL_PLAN_LOOKUP;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.CC_PLAN_LOOKUP                    */
/*********************************************/

CREATE TABLE CC_COBRA.CC_PLAN_LOOKUP_C AS (
SELECT *
FROM  CC_COBRA.CC_PLAN_LOOKUP) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.CC_PLAN_LOOKUP ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.CC_PLAN_LOOKUP
SELECT * FROM CC_COBRA.CC_PLAN_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.CC_PLAN_LOOKUP
MINUS
SELECT * FROM CC_COBRA.CC_PLAN_LOOKUP_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.CC_PLAN_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_PLAN_LOOKUP;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*********************************************/
/*CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP          */
/*********************************************/

CREATE TABLE CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP_C AS (
SELECT *
FROM  CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP
SELECT * FROM CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP
MINUS
SELECT * FROM CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*********************************************/
/*CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP_HIST     */
/*********************************************/

CREATE TABLE CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP_HST_C AS (
SELECT *
FROM  CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP_HIST) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP_HIST ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP_HIST
SELECT * FROM CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP_HST_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP_HIST
MINUS
SELECT * FROM CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP_HST_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP_HST_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_PROMO_ORG_PLAN_LOOKUP_HIST;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*********************************************/
/*CC_COBRA.DERVTN_SOURCE_CHANNL              */
/*********************************************/

CREATE TABLE CC_COBRA.DERVTN_SOURCE_CHANNL_C AS (
SELECT *
FROM  CC_COBRA.DERVTN_SOURCE_CHANNL) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.DERVTN_SOURCE_CHANNL ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.DERVTN_SOURCE_CHANNL
SELECT * FROM CC_COBRA.DERVTN_SOURCE_CHANNL_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.DERVTN_SOURCE_CHANNL
MINUS
SELECT * FROM CC_COBRA.DERVTN_SOURCE_CHANNL_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.DERVTN_SOURCE_CHANNL_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.DERVTN_SOURCE_CHANNL ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*********************************************/
/*CC_COBRA.DERVTN_SOURCE_CHANNL_DETAIL       */
/*********************************************/

CREATE TABLE CC_COBRA.DERVTN_SOURCE_CHANNL_DETAIL_C AS (
SELECT *
FROM  CC_COBRA.DERVTN_SOURCE_CHANNL_DETAIL) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.DERVTN_SOURCE_CHANNL_DETAIL ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.DERVTN_SOURCE_CHANNL_DETAIL
SELECT * FROM CC_COBRA.DERVTN_SOURCE_CHANNL_DETAIL_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.DERVTN_SOURCE_CHANNL_DETAIL
MINUS
SELECT * FROM CC_COBRA.DERVTN_SOURCE_CHANNL_DETAIL_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.DERVTN_SOURCE_CHANNL_DETAIL_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.DERVTN_SOURCE_CHANNL_DETAIL ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.FR03_PPI_FEATURES                 */
/*********************************************/

CREATE TABLE CC_COBRA.FR03_PPI_FEATURES_C AS (
SELECT *
FROM  CC_COBRA.FR03_PPI_FEATURES) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.FR03_PPI_FEATURES ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.FR03_PPI_FEATURES
SELECT * FROM CC_COBRA.FR03_PPI_FEATURES_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.FR03_PPI_FEATURES
MINUS
SELECT * FROM CC_COBRA.FR03_PPI_FEATURES_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.FR03_PPI_FEATURES_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR03_PPI_FEATURES ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.FR11_ACCRUAL_ME_POINT             */
/*********************************************/

CREATE TABLE CC_COBRA.FR11_ACCRUAL_ME_POINT_C AS (
SELECT *
FROM  CC_COBRA.FR11_ACCRUAL_ME_POINT) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.FR11_ACCRUAL_ME_POINT ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.FR11_ACCRUAL_ME_POINT
SELECT * FROM CC_COBRA.FR11_ACCRUAL_ME_POINT_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.FR11_ACCRUAL_ME_POINT
MINUS
SELECT * FROM CC_COBRA.FR11_ACCRUAL_ME_POINT_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.FR11_ACCRUAL_ME_POINT_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR11_ACCRUAL_ME_POINT ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.FR11_FDI_CALENDAR                 */
/*********************************************/

CREATE TABLE CC_COBRA.FR11_FDI_CALENDAR_C AS (
SELECT *
FROM  CC_COBRA.FR11_FDI_CALENDAR) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.FR11_FDI_CALENDAR ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.FR11_FDI_CALENDAR
SELECT * FROM CC_COBRA.FR11_FDI_CALENDAR_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.FR11_FDI_CALENDAR
MINUS
SELECT * FROM CC_COBRA.FR11_FDI_CALENDAR_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.FR11_FDI_CALENDAR_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR11_FDI_CALENDAR ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*********************************************/
/*CC_COBRA.FR11_FDI_CALENDAR_WORKDAY         */
/*********************************************/

CREATE TABLE CC_COBRA.FR11_FDI_CALENDAR_WORKDAY_C AS (
SELECT *
FROM  CC_COBRA.FR11_FDI_CALENDAR_WORKDAY) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.FR11_FDI_CALENDAR_WORKDAY ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.FR11_FDI_CALENDAR_WORKDAY
SELECT * FROM CC_COBRA.FR11_FDI_CALENDAR_WORKDAY_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.FR11_FDI_CALENDAR_WORKDAY
MINUS
SELECT * FROM CC_COBRA.FR11_FDI_CALENDAR_WORKDAY_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.FR11_FDI_CALENDAR_WORKDAY_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR11_FDI_CALENDAR_WORKDAY ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*********************************************/
/*CC_COBRA.FR14_PRODUCT_SCHEME               */
/*********************************************/

CREATE TABLE CC_COBRA.FR14_PRODUCT_SCHEME_C AS (
SELECT *
FROM  CC_COBRA.FR14_PRODUCT_SCHEME) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.FR14_PRODUCT_SCHEME ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.FR14_PRODUCT_SCHEME
SELECT * FROM CC_COBRA.FR14_PRODUCT_SCHEME_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.FR14_PRODUCT_SCHEME
MINUS
SELECT * FROM CC_COBRA.FR14_PRODUCT_SCHEME_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.FR14_PRODUCT_SCHEME_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR14_PRODUCT_SCHEME ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.FR15_BALANC_TYPE_CD_DRIVER        */
/*********************************************/

CREATE TABLE CC_COBRA.FR15_BALANC_TYPE_CD_DRIVER_C AS (
SELECT *
FROM  CC_COBRA.FR15_BALANC_TYPE_CD_DRIVER) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.FR15_BALANC_TYPE_CD_DRIVER ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.FR15_BALANC_TYPE_CD_DRIVER
SELECT * FROM CC_COBRA.FR15_BALANC_TYPE_CD_DRIVER_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.FR15_BALANC_TYPE_CD_DRIVER
MINUS
SELECT * FROM CC_COBRA.FR15_BALANC_TYPE_CD_DRIVER_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.FR15_BALANC_TYPE_CD_DRIVER_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR15_BALANC_TYPE_CD_DRIVER ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.FR15_BALANC_TYPE_CD_LOOKUP        */
/*********************************************/

CREATE TABLE CC_COBRA.FR15_BALANC_TYPE_CD_LOOKUP_C AS (
SELECT *
FROM  CC_COBRA.FR15_BALANC_TYPE_CD_LOOKUP) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.FR15_BALANC_TYPE_CD_LOOKUP ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.FR15_BALANC_TYPE_CD_LOOKUP
SELECT * FROM CC_COBRA.FR15_BALANC_TYPE_CD_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.FR15_BALANC_TYPE_CD_LOOKUP
MINUS
SELECT * FROM CC_COBRA.FR15_BALANC_TYPE_CD_LOOKUP_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.FR15_BALANC_TYPE_CD_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR15_BALANC_TYPE_CD_LOOKUP ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.FR17_BALANC_TYPE_CD_LOOKUP        */
/*********************************************/

CREATE TABLE CC_COBRA.FR17_BALANC_TYPE_CD_LOOKUP_C AS (
SELECT *
FROM  CC_COBRA.FR17_BALANC_TYPE_CD_LOOKUP) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.FR17_BALANC_TYPE_CD_LOOKUP ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.FR17_BALANC_TYPE_CD_LOOKUP
SELECT * FROM CC_COBRA.FR17_BALANC_TYPE_CD_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.FR17_BALANC_TYPE_CD_LOOKUP
MINUS
SELECT * FROM CC_COBRA.FR17_BALANC_TYPE_CD_LOOKUP_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.FR17_BALANC_TYPE_CD_LOOKUP_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR17_BALANC_TYPE_CD_LOOKUP ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.FR36_SCHEMES                      */
/*********************************************/

CREATE TABLE CC_COBRA.FR36_SCHEMES_C AS (
SELECT *
FROM  CC_COBRA.FR36_SCHEMES) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.FR36_SCHEMES ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.FR36_SCHEMES
SELECT * FROM CC_COBRA.FR36_SCHEMES_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.FR36_SCHEMES
MINUS
SELECT * FROM CC_COBRA.FR36_SCHEMES_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.FR36_SCHEMES_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR36_SCHEMES ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.GDW_RAG_REVIEW                    */
/*********************************************/

CREATE TABLE CC_COBRA.GDW_RAG_REVIEW_C AS (
SELECT *
FROM  CC_COBRA.GDW_RAG_REVIEW) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.GDW_RAG_REVIEW ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.GDW_RAG_REVIEW
SELECT * FROM CC_COBRA.GDW_RAG_REVIEW_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.GDW_RAG_REVIEW
MINUS
SELECT * FROM CC_COBRA.GDW_RAG_REVIEW_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.GDW_RAG_REVIEW_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.GDW_RAG_REVIEW ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.TRNSCN_DERVTN_GROUPS              */
/*********************************************/

CREATE TABLE CC_COBRA.TRNSCN_DERVTN_GROUPS_C AS (
SELECT *
FROM  CC_COBRA.TRNSCN_DERVTN_GROUPS) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.TRNSCN_DERVTN_GROUPS ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.TRNSCN_DERVTN_GROUPS
SELECT * FROM CC_COBRA.TRNSCN_DERVTN_GROUPS_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.TRNSCN_DERVTN_GROUPS
MINUS
SELECT * FROM CC_COBRA.TRNSCN_DERVTN_GROUPS_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.TRNSCN_DERVTN_GROUPS_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.TRNSCN_DERVTN_GROUPS ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.WK_CC_ISSUER_SORT_CODE_REMOVE     */
/*********************************************/

CREATE TABLE CC_COBRA.WK_CC_ISSUER_SORT_CODE_R_C AS (
SELECT *
FROM  CC_COBRA.WK_CC_ISSUER_SORT_CODE_REMOVE) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.WK_CC_ISSUER_SORT_CODE_REMOVE ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.WK_CC_ISSUER_SORT_CODE_REMOVE
SELECT * FROM CC_COBRA.WK_CC_ISSUER_SORT_CODE_R_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.WK_CC_ISSUER_SORT_CODE_REMOVE
MINUS
SELECT * FROM CC_COBRA.WK_CC_ISSUER_SORT_CODE_R_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.WK_CC_ISSUER_SORT_CODE_R_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.WK_CC_ISSUER_SORT_CODE_REMOVE ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*********************************************/
/*CC_COBRA.WK_CC_MACS_TO_EXCLUDE             */
/*********************************************/

CREATE TABLE CC_COBRA.WK_CC_MACS_TO_EXCLUDE_C AS (
SELECT *
FROM  CC_COBRA.WK_CC_MACS_TO_EXCLUDE) WITH DATA;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.WK_CC_MACS_TO_EXCLUDE ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.WK_CC_MACS_TO_EXCLUDE
SELECT * FROM CC_COBRA.WK_CC_MACS_TO_EXCLUDE_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FAILSAFE - CHECK THE TABLES ARE THE SAME*/
SELECT * FROM CC_COBRA.WK_CC_MACS_TO_EXCLUDE
MINUS
SELECT * FROM CC_COBRA.WK_CC_MACS_TO_EXCLUDE_C;

.IF ACTIVITYCOUNT <> 0  THEN .GOTO FOUNDERROR;

DROP TABLE CC_COBRA.WK_CC_MACS_TO_EXCLUDE_C;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.WK_CC_MACS_TO_EXCLUDE ;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*UPDATE THE LOG TABLE IF IT HAS RUN OK!*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  CURRENT_LOAD_DT = (SELECT START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , UPDATE_DT = DATE
   , UPDATE_TM = TIME
   , LOAD_STATUS = 'C'
WHERE GRID_LOAD_ID = 'C01J21'
;

SELECT GRID_LOAD_ID, CURRENT_BUS_DT, CURRENT_LOAD_DT   
FROM CC_COBRA.CC_COBRA_LOAD_LOG WHERE GRID_LOAD_ID = 'C01J21';

.QUIT 0;

.LABEL SKIPJOB;

.QUIT;

.LABEL GRIDERROR;

.QUIT;

.LABEL FOUNDERROR;

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  LOAD_STATUS = 'F'
WHERE GRID_LOAD_ID = 'C01J21'
;

.QUIT 0;

