/************************************************************************/
/*JOB:      C01J17: DATA DELETION                                       */
/*VERSION:  C01J17v08 - FR11_STATEMENT table retention.sql              */
/*DATE VERSION IMPLEMENTED: 2023-10-31                                  */
/*DEPENDENCIES:                                                         */
/*C01J01                                                                */
/*C01J04                                                                */
/************************************************************************/

.SET ERRORLEVEL (2641,3603) SEVERITY 4, UNKNOWN SEVERITY 8

SET QUERY_BAND = 'ApplicationName=CC_Finance_daily_run;JobID=GRFD043;Worktype=TripleR;Version=LBG;' FOR SESSION;
   
DATABASE CC_COBRA;

/*STEP 00: CHECK PRIOR JOBS FOR COMPLETION*/

/*INITIAL CHECKS TO SEE IF DAILY LOAD IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J01';

.IF ActivityCount = 0 THEN .GOTO GRIDERROR;


/*CHECK TO SEE IF PROCESSING GREATER THAN THE FIRST WORKING DAY OF THE MONTH - THIS IS AIMED AT RUNNING WD2, BUT IF IT HASN'T RUN ALREADY THIS MONTH IT WILL TRY AGAIN ON WD3 WD4 ETC*/

SELECT * FROM CC_COBRA.GRID_REPORTS_CONTROL 
WHERE (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT) = PRIOR_WORKDAY_DT
AND WORKDAY_OF_MONTH >= 2;

.IF ActivityCount = 0 THEN .GOTO SKIPJOB;


/*INITIAL CHECKS TO SEE IF THIS JOB HAS ALREADY RUN SUCCESSFULLY FOR LAST COMPLETED MONTH*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE (CURRENT_BUS_DT+1)/100 = (SELECT SOURCE_START_DT/100 FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J17';

.IF ActivityCount <> 0 THEN .GOTO SKIPJOB;

/*ANOTHER CHECK TO SEE IF IT HAS ALREADY BEEN PROCESSED FOR LAST MONTH*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG
WHERE GRID_LOAD_ID = 'C01J17'
AND CURRENT_BUS_DT/100 = (
SELECT PRIOR_WORKDAY_DT/100
FROM  CC_COBRA.GRID_REPORTS_CONTROL 
WHERE CALENDAR_DATE/100 = (SELECT SOURCE_START_DT/100 FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND WORKDAY_OF_MONTH = 1)
;

.IF ActivityCount <> 0 THEN .GOTO SKIPJOB;


/*SET THE STATUS START DT/TM*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
FROM CC_COBRA.CC_COBRA_LOAD_STATUS A
SET RUN_ID = A.RUN_ID
,   LOAD_STATUS = 'I'
,   LOAD_START_DT = DATE
,   LOAD_START_TM = TIME
WHERE CC_COBRA.CC_COBRA_LOAD_LOG.GRID_LOAD_ID = 'C01J17'
AND   A.RUN_STATUS = 'I'
;

.IF Errorcode <> 0 THEN .GOTO FOUNDERROR;

/*DELETION OF OLD DATA FROM FR11*/

DELETE FROM CC_COBRA.FR11_PAYMENTS  WHERE POSTNG_DT < (SELECT Add_Months((SOURCE_START_DT-Extract(DAY From SOURCE_START_DT)+1),-37) FROM CC_COBRA.CC_COBRA_LOAD_START_DT); 
.IF Errorcode <> 0 THEN .GOTO FOUNDERROR;
DELETE FROM CC_COBRA.FR11_STATEMENTS WHERE STTMNT_MTH < (SELECT Add_Months((SOURCE_START_DT-Extract(DAY From SOURCE_START_DT)+1),-13) FROM CC_COBRA.CC_COBRA_LOAD_START_DT);
.IF Errorcode <> 0 THEN .GOTO FOUNDERROR;

/*DELETION OF OLD DATA FROM FR14*/

DELETE FROM CC_COBRA.FR14_PLAN_PAYMENTS WHERE REPORT_DT < (SELECT Add_Months((SOURCE_START_DT-Extract(DAY From SOURCE_START_DT)+1),-37) FROM CC_COBRA.CC_COBRA_LOAD_START_DT); 
.IF Errorcode <> 0 THEN .GOTO FOUNDERROR;
DELETE FROM CC_COBRA.FR14_PAYMENT_GROUP WHERE REPORT_DT < (SELECT Add_Months((SOURCE_START_DT-Extract(DAY From SOURCE_START_DT)+1),-37) FROM CC_COBRA.CC_COBRA_LOAD_START_DT); 
.IF Errorcode <> 0 THEN .GOTO FOUNDERROR;
DELETE FROM CC_COBRA.FR14_PLAN_IN_OUT_UNMATCHED WHERE REPORT_DT < (SELECT Add_Months((SOURCE_START_DT-Extract(DAY From SOURCE_START_DT)+1),-37) FROM CC_COBRA.CC_COBRA_LOAD_START_DT); 
.IF Errorcode <> 0 THEN .GOTO FOUNDERROR;
DELETE FROM CC_COBRA.FR14_PLAN_IN_OUT WHERE REPORT_DT < (SELECT Add_Months((SOURCE_START_DT-Extract(DAY From SOURCE_START_DT)+1),-37) FROM CC_COBRA.CC_COBRA_LOAD_START_DT); 
.IF Errorcode <> 0 THEN .GOTO FOUNDERROR;

/*DELETION OF OLD DATA FROM FR15*/

DELETE FROM CC_COBRA.FR15_AGREEMENT_BALANCE_WALK WHERE PERIOD_END_DT < (SELECT Add_Months((SOURCE_START_DT-Extract(DAY From SOURCE_START_DT)+1),-37) FROM CC_COBRA.CC_COBRA_LOAD_START_DT); 
.IF Errorcode <> 0 THEN .GOTO FOUNDERROR;
DELETE FROM CC_COBRA.FR15_AVERAGE_BALANCE WHERE PERIOD_END_DT < (SELECT Add_Months((SOURCE_START_DT-Extract(DAY From SOURCE_START_DT)+1),-37) FROM CC_COBRA.CC_COBRA_LOAD_START_DT); 
.IF Errorcode <> 0 THEN .GOTO FOUNDERROR;

/*DELETION OF OLD DATA FROM C01J14 - limited to 3 months of data from 07/02/2020*/

DELETE FROM CC_COBRA.CC_AGREEMENT_ME_SNAPSHOT WHERE PERIOD_END_DT < (SELECT Add_Months((SOURCE_START_DT-Extract(DAY From SOURCE_START_DT)+1),-3) FROM CC_COBRA.CC_COBRA_LOAD_START_DT);
.IF Errorcode <> 0 THEN .GOTO FOUNDERROR;

/*DELETION OF OLD DATA FROM C01J16*/
   
DELETE  FROM CC_COBRA.CC_EVENT_FEATURE_ID
WHERE EVENT_ID IN (
SELECT A.EVENT_ID
FROM CC_COBRA.CC_EVENT_FEATURE_ID A
JOIN GDW_VIEWS.CC_MONETARY_TRANSACTION_HIST B
ON  A.EVENT_ID = B.EVENT_ID
AND B.SOURCE_START_DT < (SELECT Add_Months((SOURCE_START_DT-Extract(DAY From SOURCE_START_DT)+1),-37) FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
);
.IF Errorcode <> 0 THEN .GOTO FOUNDERROR;

/*DELETION OF OLD DATA FROM C01J15 - KEEP UP TO 3 MONTHS OF DATA ONLY */

DELETE FROM CC_COBRA.CC_ACCOUNT_DAILY 
WHERE REPORT_DT < 
(SELECT Add_Months(Cast(((REPORT_DT/100*100)+1) AS DATE),-2)-2 FROM CC_COBRA.WK_C01J15_REPORT_DATE);

.IF Errorcode <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.CC_ACCOUNT_FEATURE_DAILY 
WHERE REPORT_DT < 
(SELECT Add_Months(Cast(((REPORT_DT/100*100)+1) AS DATE),-2)-2 FROM CC_COBRA.WK_C01J15_REPORT_DATE);

.IF Errorcode <> 0 THEN .GOTO FOUNDERROR;

/*DELETION OF OLD DATA FROM C01J20 - KEEP UP TO 3 MONTHS OF DATA ONLY */

DELETE FROM CC_COBRA.CC_ACCOUNT_FEATURE_CTD_CUML 
WHERE REPORT_DT < 
(SELECT Add_Months(Cast(((REPORT_DT/100*100)+1) AS DATE),-2)-2 FROM CC_COBRA.WK_C01J15_REPORT_DATE);

DELETE FROM CC_COBRA.CC_AGRMNT_FEATUR_INT_CONV
WHERE REPORT_DT < 
(SELECT Add_Months(Cast(((REPORT_DT/100*100)+1) AS DATE),-35)-35 FROM CC_COBRA.WK_C01J15_REPORT_DATE);

.IF Errorcode <> 0 THEN .GOTO FOUNDERROR;


/*UPDATE THE LOG TABLE IF IT HAS RUN OK!*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  CURRENT_LOAD_DT = (SELECT START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , CURRENT_BUS_DT = 
(SELECT Add_Months(Cast((PRIOR_WORKDAY_DT/100*100)+1 AS DATE),1)-1  /*SETS TO LAST DAY OF MONTH*/
 FROM CC_COBRA.GRID_REPORTS_CONTROL 
 WHERE  WORKDAY_OF_MONTH = 1
 AND (SELECT SOURCE_START_DT/100 FROM CC_COBRA.CC_COBRA_LOAD_START_DT) = CALENDAR_DATE/100)
   , UPDATE_DT = DATE
   , UPDATE_TM = TIME
   , LOAD_STATUS = 'C'
WHERE GRID_LOAD_ID = 'C01J17'
;

.IF Errorcode <> 0 THEN .GOTO FOUNDERROR;

.QUIT;

.LABEL SKIPJOB;

.QUIT;

.LABEL GRIDERROR;

.QUIT;

.LABEL FOUNDERROR;

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  LOAD_STATUS = 'F'
WHERE GRID_LOAD_ID = 'C01J17'
;

.QUIT 0;

