/************************************************************************/
/*JOB:      C01J13 - CC_AGREEMENT_CHANNEL                               */
/*VERSION:  C01J13v13 - MBNA Migration Update.sql           */
/*DATE VERSION IMPLEMENTED: 2019-02-24                                  */
/*DEPENDENCIES:                                                         */
/*C01J01                                                                */
/*C01J13                                                                */
/*FR14                                                                  */
/************************************************************************/

.SET ERRORLEVEL (2641,3603) SEVERITY 4, UNKNOWN SEVERITY 8

SET QUERY_BAND = 'ApplicationName=CC_Finance_daily_run;JobID=GRFD043;Worktype=TripleR;Version=LBG;' FOR SESSION;

DATABASE CC_COBRA;

/*STEP 01: INITIAL CHECKS TO SEE IF DAILY LOAD IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J01';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*STEP 02: INITIAL CHECKS TO SEE IF CC_AGREEMENT_ADDED_DATE IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J02';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*STEP 02: INITIAL CHECKS TO SEE IF AGREEMENT_STATIC DAILY IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J08';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*STEP 02: INITIAL CHECKS TO SEE IF THIS PARTICULAR JOB HAS ALREADY RUN SUCCESSFULLY*/
/*IF THERE IS ALREADY DATA IT WILL SKIP THE JOB*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J13';

.IF ACTIVITYCOUNT <> 0 THEN .GOTO SKIPJOB;


/*CHECK TO SEE IF ANY NEW RECORDS FOR  FROM AGREEMENT_APPLICATION - IF NOT, SKIP JOB*/

/*THE FOLLOWING CHECK HAS BEEN COMMENTED OUT BECAUSE IT CAUSES ISSUES ON A BANK HOLIDAY. APPLICATIONS ARE A DAY LATE SO THE JOB FAILS AT THIS STAGE AND HAS A KNOCK ON EFFECT ON DEPENDENT JOBS (EG. FR15). EYNON 3RD MAY 2016.*/
/*
SELECT TOP 2 *
FROM 
(SELECT 	APPLCN_ID
      	,MIN(START_DT) AS APP_ADDED_DT
FROM  	GDW_VIEWS.APPLICATION
WHERE 	PRODCT_TYPE_CD = '52200100'
GROUP BY 1 ) B
JOIN    GDW_VIEWS.AGREEMENT_APPLICATION C
ON      B.APPLCN_ID = C.APPLCN_ID
JOIN    CC_COBRA.CC_COBRA_LOAD_START_DT S
ON      C.START_DT = S.START_DT
;

.IF ACTIVITYCOUNT = 0 THEN .GOTO SKIPJOB;
*/

/*SET THE STATUS START DT/TM*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
FROM CC_COBRA.CC_COBRA_LOAD_STATUS A
SET RUN_ID = A.RUN_ID
,   LOAD_STATUS = 'I'
,   LOAD_START_DT = DATE
,   LOAD_START_TM = TIME
WHERE CC_COBRA.CC_COBRA_LOAD_LOG.GRID_LOAD_ID = 'C01J13'
AND   A.RUN_STATUS = 'I'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*REFERENCE DATA*/
/*
CREATE TABLE CC_COBRA.CC_HIGH_CHANNL_CD (
HIGH_CHANNL_CD CHAR(1)
,HIGH_CHANNL_DESC VARCHAR(20)
) UNIQUE PRIMARY INDEX(HIGH_CHANNL_CD);


INSERT INTO CC_COBRA.CC_HIGH_CHANNL_CD SELECT 'S', 'Store';
INSERT INTO CC_COBRA.CC_HIGH_CHANNL_CD SELECT 'D', 'DM -Lloyds';
INSERT INTO CC_COBRA.CC_HIGH_CHANNL_CD SELECT 'T', 'Telephony';
INSERT INTO CC_COBRA.CC_HIGH_CHANNL_CD SELECT 'I', 'Internet';
INSERT INTO CC_COBRA.CC_HIGH_CHANNL_CD SELECT 'G', 'Internet -Airmiles';
INSERT INTO CC_COBRA.CC_HIGH_CHANNL_CD SELECT 'A', 'DM -Airmiles';
INSERT INTO CC_COBRA.CC_HIGH_CHANNL_CD SELECT 'O', 'Other';
INSERT INTO CC_COBRA.CC_HIGH_CHANNL_CD SELECT 'J', 'Agency';
INSERT INTO CC_COBRA.CC_HIGH_CHANNL_CD SELECT 'P', 'Digital Bought';
INSERT INTO CC_COBRA.CC_HIGH_CHANNL_CD SELECT 'U', 'Telephony -Inbound';
INSERT INTO CC_COBRA.CC_HIGH_CHANNL_CD SELECT 'V', 'Telephony -Outbound';
COLLECT STATS ON CC_COBRA.CC_HIGH_CHANNL_CD INDEX(HIGH_CHANNL_CD );



CREATE TABLE CC_COBRA.CC_CHANNL_CD (
CHANNL_CD CHAR(1)
,CHANNL_DESC VARCHAR(20)
) UNIQUE PRIMARY INDEX(CHANNL_CD);

INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'S', 'Store';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'D', 'DM -Lloyds';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'T', 'Telephony';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'I', 'Internet';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'G', 'Internet -Airmiles';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'A', 'DM -Airmiles';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'O', 'Other';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'B', 'Direct Mail-Other DM';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'C', 'Internet-Affiliate';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'E', 'Internet-Run of Site';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT '1','Member Get Member';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT '2','Outdoor';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT '3','Unallocated Branch-Guaranteed';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT '4','Unallocated Branch-Non-Guaranteed';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT '5','HBOS Unknown';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT '6','3rd Party Outbound';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT '7','Internet -Bought';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT '8','Print-Press';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'F','Door Drop';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'H','DM -HBOS';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'J','Agency - RCC';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'K','Agency - Branch';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'L','Cross Sale';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'M','E-Mail';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'N','HEA';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'P','Print';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'Q','RCC';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'R','Inserts';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'U','Telephony -Inbound';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'V','Telephony -Outbound Cardiff Gate';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT '9','Telephony -Outbound';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'W','TV-Radio';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'X','RCC';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'Y','Event';
INSERT INTO CC_COBRA.CC_CHANNL_CD SELECT 'Z','Duality';

COLLECT STATS ON CC_COBRA.CC_CHANNL_CD INDEX(CHANNL_CD );


*/


/*
CREATE TABLE CC_COBRA.WK_CC_AGREEMENT_CHANNEL 
(
AGRMNT_ID INT
,MAC_CD CHAR(20) COMPRESS '9999999999999999    '
,AGRMNT_SELLNG_SORT_CD CHAR(8)
,AGRMNT_SELLNG_CHANNL_CD VARCHAR(12)
,DERVTN_SOURCE_NM VARCHAR(20)
,REGION_ORGNSN_NM VARCHAR(100)

) UNIQUE PRIMARY INDEX(AGRMNT_ID);

*/

DELETE FROM CC_COBRA.WK_CC_AGREEMENT_CHANNEL ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO  CC_COBRA.WK_CC_AGREEMENT_CHANNEL
SELECT 
ASTD.AGRMNT_ID
,ASTD.MAC_CD
,ASTD.AGRMNT_SELLNG_SORT_CD
,AGRMNT_SELLNG_CHANNL_CD
,COALESCE(DSCD.DERVTN_SOURCE_NM, 'UNKNOWN') CHANNEL
,OSSG.REGION_ORGNSN_NM
FROM  CC_COBRA.AGREEMENT_STATIC_DAILY ASTD
LEFT JOIN CC_COBRA.DERVTN_SOURCE_CHANNL DSC
ON   ASTD.AGRMNT_SELLNG_CHANNL_CD = DSC.CHANNL_GROUP_CD
AND  DSC.SOURCE_END_DT = '3500/12/31'
LEFT JOIN CC_COBRA.DERVTN_SOURCE_CHANNL_DETAIL DSCD
ON   ASTD.MAC_CD = DSCD.MAC_CD
AND (DSC.DERVTN_CHANNL_GROUP_NM = DSCD.DERVTN_CHANNL_GROUP_NM
OR   (DSC.DERVTN_CHANNL_GROUP_NM IS NULL AND DSCD.DERVTN_CHANNL_GROUP_NM IS NULL))
/*AND  DSCD.SOURCE_END_DT = '3500/12/31'*/
AND ASTD.AGRMNT_OPEN_DT BETWEEN DSCD.SOURCE_START_DT AND DSCD.SOURCE_END_DT -1
AND  (DSCD.INSERT_FLAG <> 'T' OR DSCD.INSERT_FLAG IS NULL)
LEFT JOIN (SELECT SORT_CD, MAX(REGION_ORGNSN_NM) AS REGION_ORGNSN_NM  FROM GDW_VIEWS.OU_STRUCTURE_SORTCODE_GL GROUP BY 1) OSSG
ON   ASTD.AGRMNT_SELLNG_SORT_CD = CAST(OSSG.SORT_CD AS CHAR(8))
;


.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.WK_CC_AGREEMENT_CHANNEL INDEX(AGRMNT_ID);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*
CREATE TABLE CC_COBRA.CC_AGREEMENT_CHANNEL 
(
AGRMNT_ID INT
,MAC_CD CHAR(20) COMPRESS '9999999999999999    '
,AGRMNT_SELLNG_SORT_CD CHAR(8)
,AGRMNT_SELLNG_CHANNL_CD VARCHAR(12)
,HIGH_CHANNL_CD CHAR(1)
,CHANNL_CD CHAR(1)
,REGION_ORGNSN_NM VARCHAR(100)
,ORIGNL_AGRMNT_ID INT
,ORIGNL_HIGH_CHANNL_CD CHAR(1)
,ORIGNL_CHANNL_CD CHAR(1)
,ORIGNL_REGION_ORGNSN_NM VARCHAR(100)
) UNIQUE PRIMARY INDEX(AGRMNT_ID);
*/


DELETE FROM CC_COBRA.CC_AGREEMENT_CHANNEL ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*INSERT THE FIRST AGRMNT_ID IN A CHAIN*/
 
INSERT INTO CC_COBRA.CC_AGREEMENT_CHANNEL 
SELECT 
 A.AGRMNT_ID
,CHNL.MAC_CD 
,CHNL.AGRMNT_SELLNG_SORT_CD
,CHNL.AGRMNT_SELLNG_CHANNL_CD
,CASE WHEN M.HIGH_CHANNL_CD IS NOT NULL THEN M.HIGH_CHANNL_CD
      WHEN CHNL.DERVTN_SOURCE_NM = 'Store' THEN 'S'
      WHEN CHNL.DERVTN_SOURCE_NM = 'DM -Brand' THEN 'D'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Telephony' THEN 'T'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Internet -Brand' THEN 'I'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Internet' THEN 'I'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Internet -Airmiles' THEN 'G'
      WHEN CHNL.DERVTN_SOURCE_NM = 'DM -Airmiles' THEN 'A'
      WHEN CHNL.DERVTN_SOURCE_NM = 'DM -Other' THEN 'D'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Other' THEN 'O'
      WHEN CHNL.DERVTN_SOURCE_NM = 'UNKNOWN' THEN 'O'
      ELSE 'O'
      END AS HIGH_CHANNL_CD
,CASE WHEN M.CHANNL_CD IS NOT NULL THEN M.CHANNL_CD
      WHEN CHNL.DERVTN_SOURCE_NM = 'Internet -Airmiles' THEN 'G'
      WHEN I.CHANNL_TYPE_NR = 'Affiliates' AND CHNL.DERVTN_SOURCE_NM IN ('Internet','Internet -Brand') THEN 'C'
      WHEN I.CHANNL_TYPE_NR IN ('Dotcom','Internet Banking') AND CHNL.DERVTN_SOURCE_NM IN ('Internet','Internet -Brand') THEN 'E'
      WHEN I.CHANNL_TYPE_CD = '52302003' THEN 'B'
      WHEN CHNL.DERVTN_SOURCE_NM IN ('Internet') THEN 'E'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Store' THEN 'S'
      WHEN CHNL.DERVTN_SOURCE_NM = 'DM -Brand' THEN 'D'
      WHEN CHNL.DERVTN_SOURCE_NM = 'DM -Other' THEN 'B'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Telephony' THEN 'T'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Internet -Brand' THEN 'I'
      WHEN CHNL.DERVTN_SOURCE_NM = 'DM -Airmiles' THEN 'A'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Other' THEN 'O'
      WHEN CHNL.DERVTN_SOURCE_NM = 'UNKNOWN' THEN 'O'
      ELSE 'O' END AS CHANNL_CD
,COALESCE(M.TNS_BRANCH_REGION_NAME,CHNL.REGION_ORGNSN_NM) 
,A.ORIGNL_AGRMNT_ID
,HIGH_CHANNL_CD AS ORIGNL_HIGH_CHANNL_CD
,CHANNL_CD AS ORIGNL_CHANNL_CD
,COALESCE(M.TNS_BRANCH_REGION_NAME,CHNL.REGION_ORGNSN_NM) 

FROM (SELECT * FROM CC_COBRA.CC_AGREEMENT_ADDED_DATE WHERE AGRMNT_ID = ORIGNL_AGRMNT_ID) A

LEFT JOIN	CC_COBRA.WK_CC_AGREEMENT_CHANNEL CHNL
ON 			A.AGRMNT_ID = CHNL.AGRMNT_ID

/* INTERNET OWNED/BOUGHT SPLIT */
LEFT JOIN 
       (SELECT 
        T1.AGRMNT_ID
        ,T1.APPLCN_ID
        ,COALESCE(T2.CHANNL_TYPE_CD,T3.CHANNL_TYPE_CD) AS CHANNL_TYPE_CD
        ,COALESCE(T2.APPLCN_CHANNL_TYPE_ROLE_CD, T3.APPLCN_CHANNL_TYPE_ROLE_CD) AS APPLCN_CHANNL_TYPE_ROLE_CD
        --,MIN(T1.START_DT) MIN_START_DT
        FROM GDW_VIEWS.AGREEMENT_APPLICATION T1
        LEFT JOIN GDW_VIEWS.APPLICATION_CHANNEL_TYPE T2
        ON T1.APPLCN_ID = T2.APPLCN_ID
        AND T2.CHANNL_TYPE_CD NE '52301004'  
        AND T2.APPLCN_CHANNL_TYPE_ROLE_CD = '52300001'
            JOIN GDW_VIEWS.APPLICATION_CHANNEL_TYPE T3
            ON   T1.APPLCN_ID = T3.APPLCN_ID
            AND  T3.CHANNL_TYPE_CD NE '52301004'  
        QUALIFY ROW_NUMBER() OVER(PARTITION BY T1.AGRMNT_ID ORDER BY T1.START_DT ASC) = 1 
		--More than 1 APPLCN_ID per AGRMNT_ID. 
	    --More than 1 APPLCN_CHANNL_TYPE_ROLE_CD per APPLCN_ID. Use '52300001' where available, else '523000012. 
        --This duplication is a consequence of the AOO project and should eventually be fixed.
	    --Eynon 15-11-2017
       ) D
ON A.AGRMNT_ID = D.AGRMNT_ID

LEFT JOIN 	GDW_VIEWS.CHANNEL_TYPE I
ON 			D.CHANNL_TYPE_CD = I.CHANNL_TYPE_CD


/*LEFT JOIN   CC_COBRA.CC_HBOS_MIGRATION_ACCOUNTS M --Replaced on 24/02/2019 - MBNA migration        */
LEFT JOIN   CC_COBRA_VIEWS.VW_CC_MIGRATION_ACCOUNTS M
ON          A.AGRMNT_ID = M.AGRMNT_ID
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_AGREEMENT_CHANNEL INDEX(AGRMNT_ID);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*INSERT ANY SUBSEQUENT AGRMNT_IDS*/

INSERT INTO CC_COBRA.CC_AGREEMENT_CHANNEL 
SELECT 
 A.AGRMNT_ID
,CHNL.MAC_CD 
,CHNL.AGRMNT_SELLNG_SORT_CD
,CHNL.AGRMNT_SELLNG_CHANNL_CD
,CASE WHEN M.HIGH_CHANNL_CD IS NOT NULL THEN M.HIGH_CHANNL_CD
      WHEN CHNL.DERVTN_SOURCE_NM = 'Store' THEN 'S'
      WHEN CHNL.DERVTN_SOURCE_NM = 'DM -Brand' THEN 'D'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Telephony' THEN 'T'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Internet -Brand' THEN 'I'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Internet' THEN 'I'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Internet -Airmiles' THEN 'G'
      WHEN CHNL.DERVTN_SOURCE_NM = 'DM -Airmiles' THEN 'A'
      WHEN CHNL.DERVTN_SOURCE_NM = 'DM -Other' THEN 'D'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Other' THEN 'O'
      WHEN CHNL.DERVTN_SOURCE_NM = 'UNKNOWN' THEN 'O'
      ELSE NULL
      END AS HIGH_CHANNL_CD
,CASE WHEN M.CHANNL_CD IS NOT NULL THEN M.CHANNL_CD
      WHEN CHNL.DERVTN_SOURCE_NM = 'Internet -Airmiles' THEN 'G'
      WHEN I.CHANNL_TYPE_NR = 'Affiliates' THEN 'C'
      WHEN I.CHANNL_TYPE_NR IN ('Dotcom','Internet Banking') THEN 'E'
      WHEN I.CHANNL_TYPE_CD = '52302003' THEN 'B'
      WHEN CHNL.DERVTN_SOURCE_NM IN ('Internet') THEN 'E'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Store' THEN 'S'
      WHEN CHNL.DERVTN_SOURCE_NM = 'DM -Brand' THEN 'D'
      WHEN CHNL.DERVTN_SOURCE_NM = 'DM -Other' THEN 'B'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Telephony' THEN 'T'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Internet -Brand' THEN 'I'
      WHEN CHNL.DERVTN_SOURCE_NM = 'DM -Airmiles' THEN 'A'
      WHEN CHNL.DERVTN_SOURCE_NM = 'Other' THEN 'O'
      WHEN CHNL.DERVTN_SOURCE_NM = 'UNKNOWN' THEN 'O'
      ELSE NULL END AS CHANNL_CD
,COALESCE(M.TNS_BRANCH_REGION_NAME,CHNL.REGION_ORGNSN_NM) 
,A.ORIGNL_AGRMNT_ID
,CASE WHEN M.AGRMNT_ID IS NOT NULL THEN M.HIGH_CHANNL_CD 
      ELSE C.ORIGNL_HIGH_CHANNL_CD END AS ORIGNL_HIGH_CHANNL_CD
,CASE WHEN M.AGRMNT_ID IS NOT NULL THEN M.CHANNL_CD
      ELSE C.ORIGNL_CHANNL_CD END AS ORIGNL_CHANNL_CD
,COALESCE(M.TNS_BRANCH_REGION_NAME, C.ORIGNL_REGION_ORGNSN_NM)

FROM (SELECT * FROM CC_COBRA.CC_AGREEMENT_ADDED_DATE WHERE AGRMNT_ID <> ORIGNL_AGRMNT_ID) A
JOIN CC_COBRA.CC_AGREEMENT_CHANNEL C
ON   A.ORIGNL_AGRMNT_ID = C.ORIGNL_AGRMNT_ID

LEFT JOIN	CC_COBRA.WK_CC_AGREEMENT_CHANNEL CHNL
ON 			A.AGRMNT_ID = CHNL.AGRMNT_ID

/* INTERNET OWNED/BOUGHT SPLIT */
LEFT JOIN 
       (SELECT 
        T1.AGRMNT_ID
        ,T1.APPLCN_ID
        ,COALESCE(T2.CHANNL_TYPE_CD,T3.CHANNL_TYPE_CD) AS CHANNL_TYPE_CD
        ,COALESCE(T2.APPLCN_CHANNL_TYPE_ROLE_CD, T3.APPLCN_CHANNL_TYPE_ROLE_CD) AS APPLCN_CHANNL_TYPE_ROLE_CD
        --,MIN(T1.START_DT) MIN_START_DT
        FROM GDW_VIEWS.AGREEMENT_APPLICATION T1
        LEFT JOIN GDW_VIEWS.APPLICATION_CHANNEL_TYPE T2
        ON T1.APPLCN_ID = T2.APPLCN_ID
        AND T2.CHANNL_TYPE_CD NE '52301004'  
        AND T2.APPLCN_CHANNL_TYPE_ROLE_CD = '52300001'
            JOIN GDW_VIEWS.APPLICATION_CHANNEL_TYPE T3
            ON   T1.APPLCN_ID = T3.APPLCN_ID
            AND  T3.CHANNL_TYPE_CD NE '52301004'  
        QUALIFY ROW_NUMBER() OVER(PARTITION BY T1.AGRMNT_ID ORDER BY T1.START_DT ASC) = 1 
       ) D
ON A.AGRMNT_ID = D.AGRMNT_ID

LEFT JOIN 	GDW_VIEWS.CHANNEL_TYPE I
ON 			D.CHANNL_TYPE_CD = I.CHANNL_TYPE_CD

/*LEFT JOIN   CC_COBRA.CC_HBOS_MIGRATION_ACCOUNTS M --Replaced on 24/02/2019 - MBNA migration        */
LEFT JOIN   CC_COBRA_VIEWS.VW_CC_MIGRATION_ACCOUNTS M
ON          A.AGRMNT_ID = M.AGRMNT_ID
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.CC_AGREEMENT_CHANNEL INDEX(AGRMNT_ID);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*UPDATE VERDE ACCOUNTS WITH 120 ACCOUNT*/
/*NO LONGER NEEDED FOR LBG
UPDATE CC_COBRA.CC_AGREEMENT_CHANNEL
FROM 
(
SELECT  
 L.V_AGRMNT_ID
,MAC_CD
,AGRMNT_SELLNG_SORT_CD
,AGRMNT_SELLNG_CHANNL_CD
,HIGH_CHANNL_CD
,CHANNL_CD
,REGION_ORGNSN_NM
,ORIGNL_HIGH_CHANNL_CD
,ORIGNL_CHANNL_CD
,ORIGNL_REGION_ORGNSN_NM

FROM 	CC_COBRA.VERDE_MIG_ACCOUNTS_LKUP L
JOIN    CC_COBRA.CC_AGREEMENT_CHANNEL C
ON      C.AGRMNT_ID = L.AGRMNT_ID
) T1
SET 
MAC_CD = T1.MAC_CD
,AGRMNT_SELLNG_SORT_CD = T1.AGRMNT_SELLNG_SORT_CD
,AGRMNT_SELLNG_CHANNL_CD = T1.AGRMNT_SELLNG_CHANNL_CD
,HIGH_CHANNL_CD = T1.HIGH_CHANNL_CD
,CHANNL_CD = T1.CHANNL_CD
,REGION_ORGNSN_NM = T1.REGION_ORGNSN_NM
,ORIGNL_HIGH_CHANNL_CD = T1.ORIGNL_HIGH_CHANNL_CD
,ORIGNL_CHANNL_CD = T1.ORIGNL_CHANNL_CD
,ORIGNL_REGION_ORGNSN_NM = T1.ORIGNL_REGION_ORGNSN_NM
WHERE CC_COBRA.CC_AGREEMENT_CHANNEL.AGRMNT_ID = T1.V_AGRMNT_ID
;
*/

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*UPDATE THE LOAD LOG TO THE CURRENT DATE TO INDICATE SUCCESSFUL PROCESSING*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  CURRENT_LOAD_DT = (SELECT START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , UPDATE_DT = DATE
   , UPDATE_TM = TIME
   , LOAD_STATUS = 'C'
WHERE GRID_LOAD_ID = 'C01J13'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

SELECT GRID_LOAD_ID, CURRENT_BUS_DT, CURRENT_LOAD_DT 
FROM CC_COBRA.CC_COBRA_LOAD_LOG WHERE GRID_LOAD_ID = 'C01J13';

.QUIT;

.LABEL SKIPJOB;

.QUIT;

.LABEL FOUNDERROR;

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  LOAD_STATUS = 'F'
WHERE GRID_LOAD_ID = 'C01J13'
;

.QUIT 0;

.LABEL GRIDERROR;

.QUIT;
