/************************************************************************/
/*JOB:      C01J10 - MAC CODE CHECK - CHECK FOR NEW VALUES              */
/*VERSION:  C01J10v01.sql                                               */
/*DATE VERSION IMPLEMENTED: 2013-09-08                                  */
/*DEPENDENCIES:                                                         */
/*C01J01                                                                */
/************************************************************************/

.SET ERRORLEVEL (2641,3603) SEVERITY 4, UNKNOWN SEVERITY 8

SET QUERY_BAND = 'ApplicationName=CC_Finance_daily_run;JobID=GRFD043;Worktype=TripleR;Version=LBG;' FOR SESSION;

DATABASE CC_COBRA;

/*STEP 01: INITIAL CHECKS TO SEE IF DAILY LOAD IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J01';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*STEP 02: INITIAL CHECKS TO SEE IF THIS PARTICULAR JOB HAS ALREADY RUN SUCCESSFULLY*/
/*IF THERE IS ALREADY DATA IT WILL SKIP THE JOB*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J10';

.IF ACTIVITYCOUNT <> 0 THEN .GOTO SKIPJOB;

/*SET THE STATUS START DT/TM*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
FROM CC_COBRA.CC_COBRA_LOAD_STATUS A
SET RUN_ID = A.RUN_ID
,   LOAD_STATUS = 'I'
,   LOAD_START_DT = DATE
,   LOAD_START_TM = TIME
WHERE CC_COBRA.CC_COBRA_LOAD_LOG.GRID_LOAD_ID = 'C01J10'
AND   A.RUN_STATUS = 'I'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*THIS TABLE HOLDS ANY VALUES YOU WANT TO EXCLUDE FROM THE DAILY CHECKS*/
/*
CREATE TABLE CC_COBRA.WK_CC_MACS_TO_EXCLUDE (
MAC_CD CHAR(16)
,VOLUME_TOLERANCE INT
) UNIQUE PRIMARY INDEX(MAC_CD);

COLLECT STATS ON CC_COBRA.WK_CC_MACS_TO_EXCLUDE INDEX(MAC_CD);
*/


/*STEP 03: THIS WILL PULL BACK ANY NEW MACS THAT AREN'T IN THE LOOKUP AND HAVE SIGNIFCANT NEW VOLUME*/

SELECT T1.MAC_CD
      ,T1.VOLUME
FROM 

(
SELECT 
A.MAC_CD
,A.VOLUME
,CASE WHEN B.MAC_CD IS NULL THEN 0 ELSE 1 END AS EXCLUDE_IND

FROM 
(SELECT 
T1.MAC_CD
,COUNT(*) AS VOLUME

FROM  CC_COBRA.AGREEMENT_STATIC_DAILY T1
LEFT JOIN CC_COBRA.DERVTN_SOURCE_CHANNL B
ON   T1.AGRMNT_SELLNG_CHANNL_CD = B.CHANNL_GROUP_CD
AND  B.SOURCE_END_DT = '3500/12/31'
LEFT JOIN CC_COBRA.DERVTN_SOURCE_CHANNL_DETAIL C
ON   T1.MAC_CD = C.MAC_CD
AND  (B.DERVTN_CHANNL_GROUP_NM = C.DERVTN_CHANNL_GROUP_NM
OR   (B.DERVTN_CHANNL_GROUP_NM IS NULL AND C.DERVTN_CHANNL_GROUP_NM IS NULL))
AND  C.SOURCE_END_DT = '3500/12/31'

WHERE T1.AGRMNT_OPEN_REASON_CD <>'F'
AND T1.AGRMNT_OPEN_DT / 100  >= 10912
AND C.DERVTN_SOURCE_NM IS NULL
GROUP BY 1
HAVING COUNT(*) > 5 --ONLY PICK UP ONES THAT HAVE SOME VOLUME
) A
/*MAKE SURE NOT IN ONES TO IGNORE - OR THEY HAVE SIGNIFICANT NEW VOLUME*/
LEFT JOIN CC_COBRA.WK_CC_MACS_TO_EXCLUDE B
ON 		  A.MAC_CD = B.MAC_CD
AND		  (A.VOLUME-B.VOLUME_TOLERANCE) < 30
) T1
WHERE     T1.EXCLUDE_IND = 0

ORDER BY 2 DESC
;

.IF ACTIVITYCOUNT <> 0 THEN .GOTO FOUNDERROR;

/*UPDATE THE LOAD LOG TO THE CURRENT DATE TO INDICATE SUCCESSFUL PROCESSING*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  CURRENT_LOAD_DT = (SELECT START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , UPDATE_DT = DATE
   , UPDATE_TM = TIME
   , LOAD_STATUS = 'C'
WHERE GRID_LOAD_ID = 'C01J10'
;

SELECT GRID_LOAD_ID, CURRENT_BUS_DT, CURRENT_LOAD_DT  
FROM CC_COBRA.CC_COBRA_LOAD_LOG WHERE GRID_LOAD_ID = 'C01J10';

.QUIT;


.LABEL SKIPJOB;

.QUIT;

.LABEL GRIDERROR;

.QUIT;

.LABEL FOUNDERROR;

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  LOAD_STATUS = 'F'
WHERE GRID_LOAD_ID = 'C01J10'
;

.QUIT 0;