/*COBRA - CC FINANCE DATA LOAD - RUN 1 - END JOB*/

SET QUERY_BAND = 'ApplicationName=CC_Finance_daily_run;JobID=GRFD043;Worktype=TripleR;Version=LBG;' FOR SESSION;

DATABASE CC_COBRA;

UPDATE CC_COBRA.CC_COBRA_LOAD_STATUS
SET RUN_STATUS = 'C' /*COMPLETED*/
   ,UPDATE_DT = DATE
   ,UPDATE_TM = TIME
WHERE RUN_ID = 1
;

.QUIT;
