/************************************************************************/
/*JOB:      FR10 - LATE FEES AND INTEREST BY BILLING CYCLE              */
/*VERSION:  FR10v06 - change to add in QJK for BW Bal Type.sql          */
/*DATE VERSION IMPLEMENTED: 20181031                                    */
/*DEPENDENCIES:                                                         */
/*C01J01                                                                */
/*C01J02                                                                */
/*C01J03                                                                */
/*C01J04                                                                */
/************************************************************************/

.SET ERRORLEVEL (2641,3603) SEVERITY 4, UNKNOWN SEVERITY 8

SET QUERY_BAND = 'ApplicationName=CC_Finance_daily_run;JobID=GRFD043;Worktype=TripleR;Version=LBG;' FOR SESSION;

DATABASE CC_COBRA;

/*STEP 01: CHECK PRIOR JOBS FOR COMPLETION*/

/*INITIAL CHECKS TO SEE IF DAILY LOAD IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J01';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF CC_AGREEMENT_ADDED_DATE IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J02';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;


/*INITIAL CHECKS TO SEE IF CC_MONETARY_TRANSACTION_TODAY IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J03';


/*INITIAL CHECKS TO SEE IF CC_EVENTS_TO_EXCLUDE IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J04';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF THIS JOB HAS ALREADY RUN SUCCESSFULLY*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'FR10';

.IF ACTIVITYCOUNT <> 0 THEN .GOTO SKIPJOB;

/*SET THE STATUS START DT/TM*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
FROM CC_COBRA.CC_COBRA_LOAD_STATUS A
SET RUN_ID = A.RUN_ID
,   LOAD_STATUS = 'I'
,   LOAD_START_DT = DATE
,   LOAD_START_TM = TIME
WHERE CC_COBRA.CC_COBRA_LOAD_LOG.GRID_LOAD_ID = 'FR10'
AND   A.RUN_STATUS = 'I'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*STEP 02: UPDATE DATE PARAMETER TABLE*/

/*
CREATE SET TABLE CC_COBRA.WK_FR10_DAILY_DATES ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      REPORT_DT DATE FORMAT 'YY/MM/DD')
UNIQUE PRIMARY INDEX ( REPORT_DT );

*/

UPDATE CC_COBRA.WK_FR10_DAILY_DATES
SET REPORT_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)        
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.WK_FR10_DAILY_DATES INDEX(REPORT_DT);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*DISPLAY DATE INSERTED ABOVE FOR OUTPUT*/

SELECT * FROM CC_COBRA.WK_FR10_DAILY_DATES;

/*STEP 03: COLLECT INTEREST DATA FROM FEATURE AREA*/

/*PRE-DELETE DATA FROM STAGING TABLE AND INSERT DATA*/

DELETE FROM CC_COBRA.WK_FR10_DAILY_INTEREST_T1 ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*INSERT INTEREST DATA FROM PLAN SEGMENT AREA OF GRID (FEATURES AREA)*/

INSERT INTO CC_COBRA.WK_FR10_DAILY_INTEREST_T1
SELECT 
A.AGRMNT_ID
,A.PLAN_NO
,SUM(CASE WHEN TRNSCN_DERVTN_GRP = 'INTEREST' AND REVRSL_IN = 0 THEN EVENT_AM ELSE 0 END)
,SUM(CASE WHEN TRNSCN_DERVTN_GRP = 'INTEREST' AND REVRSL_IN = 1 THEN EVENT_AM ELSE 0 END)
,SUM(CASE WHEN TRNSCN_DERVTN_GRP = 'LATE FEE' AND REVRSL_IN = 0 THEN EVENT_AM ELSE 0 END)
,SUM(CASE WHEN TRNSCN_DERVTN_GRP = 'LATE FEE' AND REVRSL_IN = 1 THEN EVENT_AM ELSE 0 END)
,SUM(CASE WHEN TRNSCN_DERVTN_GRP = 'LATE FEE' AND REVRSL_IN = 0 THEN 1 ELSE 0 END)
,SUM(CASE WHEN TRNSCN_DERVTN_GRP = 'LATE FEE' AND REVRSL_IN = 1 THEN 1 ELSE 0 END)

FROM CC_COBRA.CC_MONETARY_TRANSACTION_TODAY A
JOIN CC_COBRA.WK_FR10_DAILY_DATES D
ON   A.SOURCE_START_DT = D.REPORT_DT
JOIN CC_COBRA.TRNSCN_DERVTN_GROUPS B
ON   A.EVENT_ACTVTY_CD = B.EVENT_ACTVTY_CD
AND  B.TRNSCN_DERVTN_GRP IN ('LATE FEE','INTEREST')
GROUP BY 1,2;

.IF ACTIVITYCOUNT <> 0 THEN .GOTO SKIPHST;

/*INSERT FROM TRANSACTION HISTORY TABLE IN THE CASE OF NO INSERTS FROM PREVIOUS STEP*/

INSERT INTO CC_COBRA.WK_FR10_DAILY_INTEREST_T1
SELECT 
A.AGRMNT_ID
,CAST(SUBSTR(DF.FEATUR_TX,4,5) AS INT) AS PLAN_NO
,SUM(CASE WHEN TRNSCN_DERVTN_GRP = 'INTEREST' AND REVRSL_IN = 0 THEN EVENT_AM ELSE 0 END)
,SUM(CASE WHEN TRNSCN_DERVTN_GRP = 'INTEREST' AND REVRSL_IN = 1 THEN EVENT_AM ELSE 0 END)
,SUM(CASE WHEN TRNSCN_DERVTN_GRP = 'LATE FEE' AND REVRSL_IN = 0 THEN EVENT_AM ELSE 0 END)
,SUM(CASE WHEN TRNSCN_DERVTN_GRP = 'LATE FEE' AND REVRSL_IN = 1 THEN EVENT_AM ELSE 0 END)
,SUM(CASE WHEN TRNSCN_DERVTN_GRP = 'LATE FEE' AND REVRSL_IN = 0 THEN 1 ELSE 0 END)
,SUM(CASE WHEN TRNSCN_DERVTN_GRP = 'LATE FEE' AND REVRSL_IN = 1 THEN 1 ELSE 0 END)

FROM 	GDW_VIEWS.CC_MONETARY_TRANSACTION_HIST A
JOIN 	CC_COBRA.WK_FR10_DAILY_DATES D
ON   	A.SOURCE_START_DT = D.REPORT_DT
AND     NOT EXISTS (
        SELECT NULL 
        FROM CC_COBRA.CC_EVENTS_TO_EXCLUDE X
        WHERE A.EVENT_ID = X.EVENT_ID)
JOIN 	CC_COBRA.TRNSCN_DERVTN_GROUPS B
ON   	A.EVENT_ACTVTY_CD = B.EVENT_ACTVTY_CD
AND  	B.TRNSCN_DERVTN_GRP IN ('LATE FEE','INTEREST')
JOIN  	GDW_VIEWSX.AGREEMENT_FEATURE_EVENT AFE
ON      A.EVENT_ID = AFE.EVENT_ID
JOIN  	GDW_VIEWSX.DESCRIPTIVE_FEATURE DF
ON      AFE.FEATUR_ID = DF.FEATUR_ID
AND     DF.EFFCTV_DT IS NULL
GROUP BY 1,2;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

.LABEL SKIPHST;

COLLECT STATS ON CC_COBRA.WK_FR10_DAILY_INTEREST_T1 INDEX(AGRMNT_ID);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*STEP 04: COLLECT CYCLE DATA*/

/*PRE-DELETE DATA FROM STAGING TABLE*/

DELETE FROM CC_COBRA.WK_FR10_DAILY_INTEREST_T2 ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*STEP 04A:1ST INSERT - PICK UP BILLING CYCLE FOR EACH AGREEMENT FOR ANYONE WITH INTEREST FOR THAT DAY*/

INSERT INTO  CC_COBRA.WK_FR10_DAILY_INTEREST_T2
SELECT A.AGRMNT_ID
      ,A.ORG_TX
      ,CCA.V_ORG
      ,A.CREDIT_CARD_LOGO_CD
      ,A.BILLNG_CYCLE_NO
      ,DD.REPORT_DT
      ,CCA.ADDED_DT
FROM GDW_VIEWSX.CREDIT_CARD_AGREEMENT A
JOIN CC_COBRA.WK_FR10_DAILY_DATES DD
ON   DD.REPORT_DT BETWEEN A.SOURCE_START_DT AND A.SOURCE_END_DT-1
JOIN CC_COBRA.WK_FR10_DAILY_INTEREST_T1 B
ON   A.AGRMNT_ID = B.AGRMNT_ID
JOIN CC_COBRA.CC_AGREEMENT_ADDED_DATE CCA
ON   A.AGRMNT_ID = CCA.AGRMNT_ID
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*STEP 04B:2ND INSERT - PICK UP BILLING CYCLE FOR EACH AGREEMENT FOR ANYONE WITH LATE FEE FOR THAT DAY*/
/*WHERE NOT IN 1ST INSERT*/

INSERT INTO  CC_COBRA.WK_FR10_DAILY_INTEREST_T2
SELECT A.AGRMNT_ID
      ,A.ORG_TX
      ,CCA.V_ORG
      ,A.CREDIT_CARD_LOGO_CD
      ,A.BILLNG_CYCLE_NO
      ,DD.REPORT_DT
      ,CCA.ADDED_DT
FROM GDW_VIEWSX.CREDIT_CARD_AGREEMENT A
JOIN CC_COBRA.WK_FR10_DAILY_DATES DD
ON   DD.REPORT_DT BETWEEN A.SOURCE_START_DT AND A.SOURCE_END_DT-1
JOIN CC_COBRA.WK_FR10_DAILY_INTEREST_T1 B
ON   A.AGRMNT_ID = B.AGRMNT_ID
AND  (B.LATE_FEE_AM <> 0 OR LATE_FEE_REVRSL_AM <> 0)
AND NOT EXISTS (SELECT NULL
                FROM CC_COBRA.WK_FR10_DAILY_INTEREST_T2 T2
                WHERE A.AGRMNT_ID = T2.AGRMNT_ID)
JOIN CC_COBRA.CC_AGREEMENT_ADDED_DATE CCA
ON  A.AGRMNT_ID = CCA.AGRMNT_ID
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.WK_FR10_DAILY_INTEREST_T2 INDEX(AGRMNT_ID);

/*STEP 07: AGGREGATE INTO FINAL TABLE FOR REPORTING - BY LOGO*/

/*DELETE RECORDS IN FINAL TABLE FOR DAY BEING RUN (IN CASE OF RE-RUN)*/

DELETE FROM CC_COBRA.FR10_DAILY_INT_LATE_FEES_LOGO
WHERE REPORT_DT IN (SELECT REPORT_DT FROM CC_COBRA.WK_FR10_DAILY_DATES );

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*INSERT COLLATED DATA*/
INSERT INTO CC_COBRA.FR10_DAILY_INT_LATE_FEES_LOGO
SELECT T2.REPORT_DT
      ,T2.BILLING_CYCLE_NO
      ,T2.ORG_TX
      ,T2.V_ORG
      ,T2.LOGO_CD
      ,SUM(CASE WHEN BW_PLAN_TYPE_CD IN ('P','R','X','F','I','K','J','Q') THEN INTRST_FEE_AM ELSE 0 END) AS RETAIL_INTRST_AM --change JM 2017-05-22
      ,SUM(CASE WHEN BW_PLAN_TYPE_CD IN ('P','R','X','F','I','K','J','Q') THEN INTRST_FEE_REVRSL_AM ELSE 0 END) AS RETAIL_INTRST_REVRSL_AM--change JM 2017-05-22
      ,SUM(CASE WHEN BW_PLAN_TYPE_CD IN ('C') THEN INTRST_FEE_AM ELSE 0 END) AS CASH_INTRST_AM
      ,SUM(CASE WHEN BW_PLAN_TYPE_CD IN ('C') THEN INTRST_FEE_REVRSL_AM ELSE 0 END) AS CASH_INTRST_REVRSL_AM
      ,SUM(CASE WHEN BW_PLAN_TYPE_CD IN ('B','M') THEN INTRST_FEE_AM ELSE 0 END) AS BT_INTRST_AM--change JM 2017-05-22
      ,SUM(CASE WHEN BW_PLAN_TYPE_CD IN ('B','M') THEN INTRST_FEE_REVRSL_AM ELSE 0 END) AS BT_INTRST_REVRSL_AM--change JM 2017-05-22
      ,SUM(ZEROIFNULL(LATE_FEE_AM)) AS LATE_FEE_AM
      ,SUM(ZEROIFNULL(LATE_FEE_REVRSL_AM)) AS LATE_FEE_REVRSL_AM
      ,SUM(ZEROIFNULL(LATE_FEE_CT)) AS LATE_FEE_CT
      ,SUM(ZEROIFNULL(LATE_FEE_REVRSL_CT)) AS LATE_FEE_REVRSL_CT
 FROM CC_COBRA.WK_FR10_DAILY_INTEREST_T1 T1
 JOIN CC_COBRA.WK_FR10_DAILY_INTEREST_T2 T2
 ON   T1.AGRMNT_ID = T2.AGRMNT_ID
 JOIN CC_COBRA.CC_PLAN_LOOKUP PL
 ON   T2.ORG_TX = PL.ORG_TX
 AND  T1.PLAN_NO = PL.PLAN_NO
 GROUP BY 1,2,3,4,5
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR10_DAILY_INT_LATE_FEES_LOGO INDEX ( REPORT_DT, BILLING_CYCLE_NO, ORG_TX, LOGO_CD );

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*STEP 07: AGGREGATE INTO FINAL TABLE FOR REPORTING*/

/*DELETE RECORDS IN FINAL TABLE FOR DAY BEING RUN (IN CASE OF RE-RUN)*/

DELETE FROM CC_COBRA.FR10_DAILY_INTEREST_LATE_FEES
WHERE REPORT_DT IN (SELECT REPORT_DT FROM CC_COBRA.WK_FR10_DAILY_DATES );

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*INSERT COLLATED DATA*/
INSERT INTO CC_COBRA.FR10_DAILY_INTEREST_LATE_FEES
SELECT T3.REPORT_DT
      ,T3.BILLING_CYCLE_NO
      ,T3.ORG_TX
      ,T3.V_ORG
      ,SUM(RETAIL_INTRST_AM+RETAIL_INTRST_REVRSL_AM) AS RETAIL_INTRST_AM
      ,SUM(CASH_INTRST_AM+CASH_INTRST_REVRSL_AM) AS CASH_INTRST_AM
      ,SUM(BT_INTRST_AM+BT_INTRST_REVRSL_AM) AS BT_INTRST_AM
      ,SUM(LATE_FEE_AM) AS LATE_FEE_AM
      ,SUM(LATE_FEE_REVRSL_AM) AS LATE_FEE_REVRSL_AM
      ,SUM(LATE_FEE_CT) AS LATE_FEE_CT
      ,SUM(LATE_FEE_REVRSL_CT) AS LATE_FEE_REVRSL_CT
FROM CC_COBRA.FR10_DAILY_INT_LATE_FEES_LOGO T3
WHERE REPORT_DT IN (SELECT REPORT_DT FROM CC_COBRA.WK_FR10_DAILY_DATES )
GROUP BY 1,2,3,4;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR10_DAILY_INTEREST_LATE_FEES INDEX( REPORT_DT, BILLING_CYCLE_NO, ORG_TX);



COLLECT STATS ON CC_COBRA.FR10_DAILY_INTEREST_LATE_FEES INDEX( REPORT_DT, BILLING_CYCLE_NO, ORG_TX);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*UPDATE THE LOG TABLE IF IT HAS RUN OK!*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  CURRENT_LOAD_DT = (SELECT START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , UPDATE_DT = DATE
   , UPDATE_TM = TIME
   , LOAD_STATUS = 'C'
WHERE GRID_LOAD_ID = 'FR10'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

SELECT GRID_LOAD_ID, CURRENT_BUS_DT, CURRENT_LOAD_DT   
FROM CC_COBRA.CC_COBRA_LOAD_LOG WHERE GRID_LOAD_ID = 'FR10';

/*UPDATE THE GDW RAG STATUS*/

UPDATE CC_COBRA.GDW_RAG_REVIEW
FROM (
SEL A.*
,CAST( ((UPDATE_DT (DATE, FORMAT 'YYYY-MM-DD')) (CHAR(10)) )
                       || ' ' || UPDATE_TM AS TIMESTAMP(0) ) AS TM2
,CAST( ((UPDATE_DT (DATE, FORMAT 'YYYY-MM-DD')) (CHAR(10)) )
                       || ' ' || LOAD_START_TM AS TIMESTAMP(0) ) AS TM1                       
, ((EXTRACT( HOUR FROM TM2) - EXTRACT( HOUR FROM TM1)) * 60*60)
+ ((EXTRACT(MINUTE FROM TM2) - EXTRACT(MINUTE FROM TM1)) * 60)
+ (EXTRACT(SECOND FROM TM2) - EXTRACT(SECOND FROM TM1)) AS SECS 

FROM CC_COBRA.CC_COBRA_LOAD_LOG A 
JOIN CC_COBRA.CC_COBRA_LOAD_START_DT B
ON   A.CURRENT_BUS_DT = B.SOURCE_START_DT
WHERE A.GRID_LOAD_ID = 'FR10'
AND  A.UPDATE_DT = A.LOAD_START_DT
AND  TM2 > TM1
)
T1
SET PRIORITY_JOB_COMPLT_TM = T1.UPDATE_TM
   ,PRIORITY_JOB_COMPLT_LENGTH = T1.SECS
WHERE CC_COBRA.GDW_RAG_REVIEW.LOAD_DT = CURRENT_BUS_DT+1
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


.QUIT;

.LABEL SKIPJOB;

.QUIT;

.LABEL GRIDERROR;

.QUIT;

.LABEL FOUNDERROR;

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  LOAD_STATUS = 'F'
WHERE GRID_LOAD_ID = 'FR10'
;

.QUIT 0;


