
/************************************************************************/
/*JOB:      FR15A - BALANCE WALK - AGGREGATIONS                         */
/*VERSION:  FR15Av07 - MT & EXPIRED PLANS Rework.sql                    */
/*DATE VERSION IMPLEMENTED: 2018-09-20                                  */
/*DEPENDENCIES:                                                         */
/*C01J01                                                                */
/*FR14                                                                  */    
/*FR15                                                                  */
/************************************************************************/


.SET ERRORLEVEL (2641,3603) SEVERITY 4, UNKNOWN SEVERITY 8

SET QUERY_BAND = 'ApplicationName=CC_Finance_daily_run;JobID=GRFD043;Worktype=TripleR;Version=LBG;' FOR SESSION;

DATABASE CC_COBRA;

/*STEP 01: CHECK PRIOR JOBS FOR COMPLETION*/

/*INITIAL CHECKS TO SEE IF DAILY LOAD IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J01';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF FR14 IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'FR14';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF FR15 IS SUCCESSFUL AND HAS BEEN UPDATED (FIRST WORKING DAY)*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'FR15';

.IF ACTIVITYCOUNT = 0 THEN .GOTO SKIPJOB;

/*INITIAL CHECKS TO SEE IF THIS JOB HAS ALREADY RUN SUCCESSFULLY*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'FR15A';

.IF ACTIVITYCOUNT <> 0 THEN .GOTO SKIPJOB;

/*SET THE STATUS START DT/TM*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
FROM CC_COBRA.CC_COBRA_LOAD_STATUS A
SET RUN_ID = A.RUN_ID
,   LOAD_STATUS = 'I'
,   LOAD_START_DT = DATE
,   LOAD_START_TM = TIME
WHERE CC_COBRA.CC_COBRA_LOAD_LOG.GRID_LOAD_ID = 'FR15A'
AND   A.RUN_STATUS = 'I'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*NOTE THIS JOB SHOULD ONLY BE RUN ON THE FIRST WORKING DAY - APART FROM ONE SECTION WHICH SHOULD BE RUN DAILY*/
/*USING THE PROCESSING DATE FOR FR14 TO TRIGGER THIS*/

/*FR15 - J09 - AGGREGATION FOR REPORTING*/

DELETE FROM CC_COBRA.WK_FR15_J09_REPORT_T1 ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.WK_FR15_J09_REPORT_T1
SELECT
A.AGRMNT_ID
,A.PLAN_NO
,B.ORG_TX
,CASE WHEN COALESCE(VERDE_IN,0) IN (1,2,3) THEN COALESCE((CASE WHEN V.ORG IN ('996','997') THEN '170' ELSE V.ORG END), B.ORG_TX) ELSE B.ORG_TX END AS V_ORG
,B.LOGO_CD
--,B.ORIGNL_ADDED_DT 
,CASE WHEN B.ORIGNL_ADDED_DT < 1000101 THEN DATE'1999-12-31'
      ELSE ADD_MONTHS(CAST(((B.ORIGNL_ADDED_DT/100*100)+1) AS DATE),1)-1 
      END AS VINTAGE_MTH
,F.LTSB_REL_TYPE_CD
,F.SEC_FLAG
,A.BALANC_TYPE_CD
,A.PERIOD_END_DT
,SUM(CASE WHEN COALESCE(VERDE_IN,0) IN (0,1,3,5) THEN OPEN_BALANC_AM ELSE 0 END) AS OPEN_BALANC_AM
,SUM(TRADE_XFRIN_AM) AS TRADE_XFRIN_AM
,SUM(TRADE_XFROUT_AM) AS TRADE_XFROUT_AM

,SUM(XFRIN_CHRDSP_AM) AS XFRIN_CHRDSP_AM
,SUM(XFRIN_RHRDSP_AM) AS XFRIN_RHRDSP_AM
,SUM(XFRIN_IHRDSP_AM) AS XFRIN_IHRDSP_AM
,SUM(XFRIN_BHRDSP_AM) AS XFRIN_BHRDSP_AM
,SUM(XFRIN_MHRDSP_AM) AS XFRIN_MHRDSP_AM
,SUM(XFRIN_PHRDSP_AM) AS XFRIN_PHRDSP_AM
,SUM(XFRIN_BXHDSP_AM) AS XFRIN_BXHDSP_AM
,SUM(XFRIN_MXHDSP_AM) AS XFRIN_MXHDSP_AM
,SUM(XFRIN_IXHDSP_AM) AS XFRIN_IXHDSP_AM
,SUM(XFRIN_ISTAT_AM) AS XFRIN_ISTAT_AM
,SUM(XFRIN_CIMPRD_AM) AS XFRIN_CIMPRD_AM
,SUM(XFRIN_RIMPRD_AM) AS XFRIN_RIMPRD_AM
,SUM(XFRIN_IIMPRD_AM) AS XFRIN_IIMPRD_AM
,SUM(XFRIN_BIMPRD_AM) AS XFRIN_BIMPRD_AM
,SUM(XFRIN_MIMPRD_AM) AS XFRIN_MIMPRD_AM
,SUM(XFRIN_PIMPRD_AM) AS XFRIN_PIMPRD_AM
,SUM(XFRIN_BXIMPD_AM) AS XFRIN_BXIMPD_AM
,SUM(XFRIN_MXIMPD_AM) AS XFRIN_MXIMPD_AM
,SUM(XFRIN_IXIMPD_AM) AS XFRIN_IXIMPD_AM
,SUM(XFRIN_CIBB_AM) AS XFRIN_CIBB_AM
,SUM(XFRIN_RIBB_AM) AS XFRIN_RIBB_AM
,SUM(XFRIN_IIBB_AM) AS XFRIN_IIBB_AM
,SUM(XFRIN_IZIBB_AM) AS XFRIN_IZIBB_AM
,SUM(XFRIN_BIBB_AM) AS XFRIN_BIBB_AM
,SUM(XFRIN_BZIBB_AM) AS XFRIN_BZIBB_AM
,SUM(XFRIN_MIBB_AM) AS XFRIN_MIBB_AM
,SUM(XFRIN_MZIBB_AM) AS XFRIN_MZIBB_AM
,SUM(XFRIN_PIBB_AM) AS XFRIN_PIBB_AM
,SUM(XFRIN_PZIBB_AM) AS XFRIN_PZIBB_AM
,SUM(XFRIN_BXIBB_AM) AS XFRIN_BXIBB_AM
,SUM(XFRIN_MXIBB_AM) AS XFRIN_MXIBB_AM
,SUM(XFRIN_IXIBB_AM) AS XFRIN_IXIBB_AM
,SUM(XFRIN_RNIBB_AM) AS XFRIN_RNIBB_AM
,SUM(XFROUT_CHRDSP_AM) AS XFROUT_CHRDSP_AM
,SUM(XFROUT_RHRDSP_AM) AS XFROUT_RHRDSP_AM
,SUM(XFROUT_IHRDSP_AM) AS XFROUT_IHRDSP_AM
,SUM(XFROUT_BHRDSP_AM) AS XFROUT_BHRDSP_AM
,SUM(XFROUT_MHRDSP_AM) AS XFROUT_MHRDSP_AM
,SUM(XFROUT_PHRDSP_AM) AS XFROUT_PHRDSP_AM
,SUM(XFROUT_BXHDSP_AM) AS XFROUT_BXHDSP_AM
,SUM(XFROUT_MXHDSP_AM) AS XFROUT_MXHDSP_AM
,SUM(XFROUT_IXHDSP_AM) AS XFROUT_IXHDSP_AM
,SUM(XFROUT_ISTAT_AM) AS XFROUT_ISTAT_AM
,SUM(XFROUT_CIMPRD_AM) AS XFROUT_CIMPRD_AM
,SUM(XFROUT_RIMPRD_AM) AS XFROUT_RIMPRD_AM
,SUM(XFROUT_IIMPRD_AM) AS XFROUT_IIMPRD_AM
,SUM(XFROUT_BIMPRD_AM) AS XFROUT_BIMPRD_AM
,SUM(XFROUT_MIMPRD_AM) AS XFROUT_MIMPRD_AM
,SUM(XFROUT_PIMPRD_AM) AS XFROUT_PIMPRD_AM
,SUM(XFROUT_BXIMPD_AM) AS XFROUT_BXIMPD_AM
,SUM(XFROUT_MXIMPD_AM) AS XFROUT_MXIMPD_AM
,SUM(XFROUT_IXIMPD_AM) AS XFROUT_IXIMPD_AM
,SUM(XFROUT_CIBB_AM) AS XFROUT_CIBB_AM
,SUM(XFROUT_RIBB_AM) AS XFROUT_RIBB_AM
,SUM(XFROUT_IIBB_AM) AS XFROUT_IIBB_AM
,SUM(XFROUT_IZIBB_AM) AS XFROUT_IZIBB_AM
,SUM(XFROUT_BIBB_AM) AS XFROUT_BIBB_AM
,SUM(XFROUT_BZIBB_AM) AS XFROUT_BZIBB_AM
,SUM(XFROUT_MIBB_AM) AS XFROUT_MIBB_AM
,SUM(XFROUT_MZIBB_AM) AS XFROUT_MZIBB_AM
,SUM(XFROUT_PIBB_AM) AS XFROUT_PIBB_AM
,SUM(XFROUT_PZIBB_AM) AS XFROUT_PZIBB_AM
,SUM(XFROUT_BXIBB_AM) AS XFROUT_BXIBB_AM
,SUM(XFROUT_MXIBB_AM) AS XFROUT_MXIBB_AM
,SUM(XFROUT_IXIBB_AM) AS XFROUT_IXIBB_AM
,SUM(XFROUT_RNIBB_AM) AS XFROUT_RNIBB_AM

,SUM(RETAIL_A_UK_AM) AS RETAIL_A_UK_AM
,SUM(RETAIL_A_UK_CT) AS RETAIL_A_UK_CT
,SUM(RETAIL_M_UK_AM) AS RETAIL_M_UK_AM
,SUM(RETAIL_M_UK_CT) AS RETAIL_M_UK_CT
,SUM(RETAIL_V_UK_AM) AS RETAIL_V_UK_AM
,SUM(RETAIL_V_UK_CT) AS RETAIL_V_UK_CT
,SUM(RETAIL_A_FOREGN_AM) AS RETAIL_A_FOREGN_AM
,SUM(RETAIL_A_FOREGN_CT) AS RETAIL_A_FOREGN_CT
,SUM(RETAIL_M_FOREGN_AM) AS RETAIL_M_FOREGN_AM
,SUM(RETAIL_M_FOREGN_CT) AS RETAIL_M_FOREGN_CT
,SUM(RETAIL_V_FOREGN_AM) AS RETAIL_V_FOREGN_AM
,SUM(RETAIL_V_FOREGN_CT) AS RETAIL_V_FOREGN_CT
,SUM(CASH_A_UK_AM) AS CASH_A_UK_AM
,SUM(CASH_A_UK_CT) AS CASH_A_UK_CT
,SUM(CASH_M_UK_AM) AS CASH_M_UK_AM
,SUM(CASH_M_UK_CT) AS CASH_M_UK_CT
,SUM(CASH_V_UK_AM) AS CASH_V_UK_AM
,SUM(CASH_V_UK_CT) AS CASH_V_UK_CT
,SUM(CASH_A_FOREGN_AM) AS CASH_A_FOREGN_AM
,SUM(CASH_A_FOREGN_CT) AS CASH_A_FOREGN_CT
,SUM(CASH_M_FOREGN_AM) AS CASH_M_FOREGN_AM
,SUM(CASH_M_FOREGN_CT) AS CASH_M_FOREGN_CT
,SUM(CASH_V_FOREGN_AM) AS CASH_V_FOREGN_AM
,SUM(CASH_V_FOREGN_CT) AS CASH_V_FOREGN_CT
,SUM(BALANC_TRNSFR_AM) AS BALANC_TRNSFR_AM
,SUM(BALANC_TRNSFR_CT) AS BALANC_TRNSFR_CT
,SUM(MONEY_TRNSFR_AM) AS MONEY_TRNSFR_AM
,SUM(MONEY_TRNSFR_CT) AS MONEY_TRNSFR_CT
,SUM(PROMO_CHEQUE_AM) AS PROMO_CHEQUE_AM
,SUM(PROMO_CHEQUE_CT) AS PROMO_CHEQUE_CT
,SUM(CONVNC_CHEQUE_AM) AS CONVNC_CHEQUE_AM
,SUM(CONVNC_CHEQUE_CT) AS CONVNC_CHEQUE_CT
,SUM(INTRST_FEE_AM) AS INTRST_FEE_AM
,SUM(INTRST_FEE_REVRSL_AM) AS INTRST_FEE_REVRSL_AM
,SUM(PPI_FEE_AM) AS PPI_FEE_AM
,SUM(PPI_FEE_REVRSL_AM) AS PPI_FEE_REVRSL_AM
,SUM(BT_FEE_AM) AS BT_FEE_AM
,SUM(MT_FEE_AM) AS MT_FEE_AM
,SUM(LATE_FEE_AM) AS LATE_FEE_AM
,SUM(LATE_FEE_REVRSL_AM) AS LATE_FEE_REVRSL_AM
,SUM(OVRLMT_FEE_AM) AS OVRLMT_FEE_AM
,SUM(OVRLMT_FEE_REVRSL_AM) AS OVRLMT_FEE_REVRSL_AM
,SUM(RETPMT_FEE_AM) AS RETPMT_FEE_AM
,SUM(RETPMT_FEE_REVRSL_AM) AS RETPMT_FEE_REVRSL_AM
,SUM(MBRSHP_FEE_AM) AS MBRSHP_FEE_AM
,SUM(CSHADV_FEE_AM) AS CSHADV_FEE_AM
,SUM(SNTNL_FEE_AM) AS SNTNL_FEE_AM
,SUM(PVYGRD_FEE_AM) AS PVYGRD_FEE_AM
,SUM(FOREX_FEE_AM) AS FOREX_FEE_AM
,SUM(OTHER_FEE_AM) AS OTHER_FEE_AM
,SUM(BT_OUT_AM) AS BT_OUT_AM
,SUM(PAYMNT_MIN_AM) AS PAYMNT_MIN_AM
,SUM(PAYMNT_PRTFUL_AM) AS PAYMNT_PRTFUL_AM
,SUM(CHARGE_OFF_AM) AS CHARGE_OFF_AM
,SUM(ADJMNT_AM) AS ADJMNT_AM
,SUM(CSHBCK_AM) AS CSHBCK_AM
,SUM(TRNSFR_AM) AS TRNSFR_AM
,SUM(WRITE_OFF_AM) AS WRITE_OFF_AM
,SUM(FRAUD_AM) AS FRAUD_AM
,SUM(UNCLFD_MOVMNT_AM) AS UNCLFD_MOVMNT_AM
,SUM(CLOSE_BALANC_AM) AS CLOSE_BALANC_AM
,SUM(CASE WHEN COALESCE(V.VERDE_IN,0) IN (2,4) THEN OPEN_BALANC_AM ELSE 0 END) AS VERDE_IN_AM
,SUM(0) AS VERDE_OUT_AM
,SUM(ZEROIFNULL(C.AVERGE_BALANC_AM)) AS AVERAG_MNTHLY_BALANC_AM
,SUM(BT_OUT_CT) AS BT_OUT_CT

FROM CC_COBRA.FR15_AGREEMENT_BALANCE_WALK A
JOIN CC_COBRA.WK_FR15_DATE_CONTROL DC
ON   A.PERIOD_END_DT = DC.REPORT_DT
JOIN CC_COBRA.FR15_FLAGS_STATIC B
ON   A.AGRMNT_ID = B.AGRMNT_ID
AND  A.BALANC_TYPE_CD IS NOT NULL

JOIN CC_COBRA.FR15_FLAGS F
ON   A.AGRMNT_ID = F.AGRMNT_ID
AND  F.PERIOD_END_DT = (SELECT REPORT_DT FROM CC_COBRA.WK_FR15_DATE_CONTROL)
/*
JOIN CC_COBRA.FR15_FLAGS_HST F
ON   A.AGRMNT_ID = F.AGRMNT_ID
AND  DC.REPORT_DT BETWEEN F.SOURCE_START_DT AND F.SOURCE_END_DT-1
*/

LEFT JOIN CC_COBRA.FR15_AVERAGE_BALANCE C
ON   A.AGRMNT_ID = C.AGRMNT_ID
AND  A.PLAN_NO = C.PLAN_NO 
AND  A.BALANC_TYPE_CD = C.BALANC_TYPE_CD
AND  C.PERIOD_END_DT = (SELECT REPORT_DT FROM CC_COBRA.WK_FR15_DATE_CONTROL)
AND  A.MIN_INSERT_STEP = 1  /*ENSURES NO DUPLICATION OF AVERAGES*/
LEFT JOIN CC_COBRA.CC_VERDE_FLAG_MTH V
ON   A.AGRMNT_ID = V.AGRMNT_ID
AND  V.PERIOD_END_DT = (SELECT REPORT_DT FROM CC_COBRA.WK_FR15_DATE_CONTROL)
GROUP BY 1,2,3,4,5,6,7,8,9,10;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


INSERT INTO CC_COBRA.WK_FR15_J09_REPORT_T1
SELECT
A.AGRMNT_ID
,A.PLAN_NO
,B.ORG_TX
,CASE WHEN COALESCE(VERDE_IN,0) IN (1,3,4) THEN COALESCE((CASE WHEN V.ORG IN ('996','997') THEN '170' ELSE V.ORG END), B.ORG_TX) ELSE B.ORG_TX END AS V_ORG
,B.LOGO_CD
,CASE WHEN B.ORIGNL_ADDED_DT < 1000101 THEN DATE'1999-12-31'
      ELSE ADD_MONTHS(CAST(((B.ORIGNL_ADDED_DT/100*100)+1) AS DATE),1)-1 
      END AS VINTAGE_MTH
,F.LTSB_REL_TYPE_CD
,F.SEC_FLAG
,BALANC_TYPE_CD
,A.PERIOD_END_DT
,SUM(CASE WHEN COALESCE(VERDE_IN,0) IN (2,4) THEN OPEN_BALANC_AM ELSE 0 END) AS OPEN_BALANC_AM
,SUM(0) AS TRADE_XFRIN_AM
,SUM(0) AS TRADE_XFROUT_AM

,SUM(0) AS XFRIN_CHRDSP_AM
,SUM(0) AS XFRIN_RHRDSP_AM
,SUM(0) AS XFRIN_IHRDSP_AM
,SUM(0) AS XFRIN_BHRDSP_AM
,SUM(0) AS XFRIN_MHRDSP_AM
,SUM(0) AS XFRIN_PHRDSP_AM
,SUM(0) AS XFRIN_BXHDSP_AM
,SUM(0) AS XFRIN_MXHDSP_AM
,SUM(0) AS XFRIN_IXHDSP_AM
,SUM(0) AS XFRIN_ISTAT_AM
,SUM(0) AS XFRIN_CIMPRD_AM
,SUM(0) AS XFRIN_RIMPRD_AM
,SUM(0) AS XFRIN_IIMPRD_AM
,SUM(0) AS XFRIN_BIMPRD_AM
,SUM(0) AS XFRIN_MIMPRD_AM
,SUM(0) AS XFRIN_PIMPRD_AM
,SUM(0) AS XFRIN_BXIMPD_AM
,SUM(0) AS XFRIN_MXIMPD_AM
,SUM(0) AS XFRIN_IXIMPD_AM
,SUM(0) AS XFRIN_CIBB_AM
,SUM(0) AS XFRIN_RIBB_AM
,SUM(0) AS XFRIN_IIBB_AM
,SUM(0) AS XFRIN_IZIBB_AM
,SUM(0) AS XFRIN_BIBB_AM
,SUM(0) AS XFRIN_BZIBB_AM
,SUM(0) AS XFRIN_MIBB_AM
,SUM(0) AS XFRIN_MZIBB_AM
,SUM(0) AS XFRIN_PIBB_AM
,SUM(0) AS XFRIN_PZIBB_AM
,SUM(0) AS XFRIN_BXIBB_AM
,SUM(0) AS XFRIN_MXIBB_AM
,SUM(0) AS XFRIN_IXIBB_AM
,SUM(0) AS XFRIN_RNIBB_AM
,SUM(0) AS XFROUT_CHRDSP_AM
,SUM(0) AS XFROUT_RHRDSP_AM
,SUM(0) AS XFROUT_IHRDSP_AM
,SUM(0) AS XFROUT_BHRDSP_AM
,SUM(0) AS XFROUT_MHRDSP_AM
,SUM(0) AS XFROUT_PHRDSP_AM
,SUM(0) AS XFROUT_BXHDSP_AM
,SUM(0) AS XFROUT_MXHDSP_AM
,SUM(0) AS XFROUT_IXHDSP_AM
,SUM(0) AS XFROUT_ISTAT_AM
,SUM(0) AS XFROUT_CIMPRD_AM
,SUM(0) AS XFROUT_RIMPRD_AM
,SUM(0) AS XFROUT_IIMPRD_AM
,SUM(0) AS XFROUT_BIMPRD_AM
,SUM(0) AS XFROUT_MIMPRD_AM
,SUM(0) AS XFROUT_PIMPRD_AM
,SUM(0) AS XFROUT_BXIMPD_AM
,SUM(0) AS XFROUT_MXIMPD_AM
,SUM(0) AS XFROUT_IXIMPD_AM
,SUM(0) AS XFROUT_CIBB_AM
,SUM(0) AS XFROUT_RIBB_AM
,SUM(0) AS XFROUT_IIBB_AM
,SUM(0) AS XFROUT_IZIBB_AM
,SUM(0) AS XFROUT_BIBB_AM
,SUM(0) AS XFROUT_BZIBB_AM
,SUM(0) AS XFROUT_MIBB_AM
,SUM(0) AS XFROUT_MZIBB_AM
,SUM(0) AS XFROUT_PIBB_AM
,SUM(0) AS XFROUT_PZIBB_AM
,SUM(0) AS XFROUT_BXIBB_AM
,SUM(0) AS XFROUT_MXIBB_AM
,SUM(0) AS XFROUT_IXIBB_AM
,SUM(0) AS XFROUT_RNIBB_AM

,SUM(0) AS RETAIL_A_UK_AM
,SUM(0) AS RETAIL_A_UK_CT
,SUM(0) AS RETAIL_M_UK_AM
,SUM(0) AS RETAIL_M_UK_CT
,SUM(0) AS RETAIL_V_UK_AM
,SUM(0) AS RETAIL_V_UK_CT
,SUM(0) AS RETAIL_A_FOREGN_AM
,SUM(0) AS RETAIL_A_FOREGN_CT
,SUM(0) AS RETAIL_M_FOREGN_AM
,SUM(0) AS RETAIL_M_FOREGN_CT
,SUM(0) AS RETAIL_V_FOREGN_AM
,SUM(0) AS RETAIL_V_FOREGN_CT
,SUM(0) AS CASH_A_UK_AM
,SUM(0) AS CASH_A_UK_CT
,SUM(0) AS CASH_M_UK_AM
,SUM(0) AS CASH_M_UK_CT
,SUM(0) AS CASH_V_UK_AM
,SUM(0) AS CASH_V_UK_CT
,SUM(0) AS CASH_A_FOREGN_AM
,SUM(0) AS CASH_A_FOREGN_CT
,SUM(0) AS CASH_M_FOREGN_AM
,SUM(0) AS CASH_M_FOREGN_CT
,SUM(0) AS CASH_V_FOREGN_AM
,SUM(0) AS CASH_V_FOREGN_CT
,SUM(0) AS BALANC_TRNSFR_AM
,SUM(0) AS BALANC_TRNSFR_CT
,SUM(0) AS MONEY_TRNSFR_AM
,SUM(0) AS MONEY_TRNSFR_CT
,SUM(0) AS PROMO_CHEQUE_AM
,SUM(0) AS PROMO_CHEQUE_CT
,SUM(0) AS CONVNC_CHEQUE_AM
,SUM(0) AS CONVNC_CHEQUE_CT
,SUM(0) AS INTRST_FEE_AM
,SUM(0) AS INTRST_FEE_REVRSL_AM
,SUM(0) AS PPI_FEE_AM
,SUM(0) AS PPI_FEE_REVRSL_AM
,SUM(0) AS BT_FEE_AM
,SUM(0) AS MT_FEE_AM
,SUM(0) AS LATE_FEE_AM
,SUM(0) AS LATE_FEE_REVRSL_AM
,SUM(0) AS OVRLMT_FEE_AM
,SUM(0) AS OVRLMT_FEE_REVRSL_AM
,SUM(0) AS RETPMT_FEE_AM
,SUM(0) AS RETPMT_FEE_REVRSL_AM
,SUM(0) AS MBRSHP_FEE_AM
,SUM(0) AS CSHADV_FEE_AM
,SUM(0) AS SNTNL_FEE_AM
,SUM(0) AS PVYGRD_FEE_AM
,SUM(0) AS FOREX_FEE_AM
,SUM(0) AS OTHER_FEE_AM
,SUM(0) AS BT_OUT_AM
,SUM(0) AS PAYMNT_MIN_AM
,SUM(0) AS PAYMNT_PRTFUL_AM
,SUM(0) AS CHARGE_OFF_AM
,SUM(0) AS ADJMNT_AM
,SUM(0) AS CSHBCK_AM
,SUM(0) AS TRNSFR_AM
,SUM(0) AS WRITE_OFF_AM
,SUM(0) AS FRAUD_AM
,SUM(0) AS UNCLFD_MOVMNT_AM
,SUM(0) AS CLOSE_BALANC_AM
,SUM(0) AS VERDE_IN_AM
,SUM(CASE WHEN COALESCE(V.VERDE_IN,0) IN (2,4) THEN OPEN_BALANC_AM*-1 ELSE 0 END) AS VERDE_OUT_AM
,SUM(0) AS AVERAG_MNTHLY_BALANC_AM
,SUM(0) AS BT_OUT_CT

FROM CC_COBRA.FR15_AGREEMENT_BALANCE_WALK A
JOIN CC_COBRA.WK_FR15_DATE_CONTROL DC
ON   A.PERIOD_END_DT = DC.REPORT_DT
JOIN CC_COBRA.FR15_FLAGS_STATIC B
ON A.AGRMNT_ID = B.AGRMNT_ID
AND A.BALANC_TYPE_CD IS NOT NULL

JOIN CC_COBRA.FR15_FLAGS F
ON   A.AGRMNT_ID = F.AGRMNT_ID
AND  F.PERIOD_END_DT = (SELECT REPORT_DT FROM CC_COBRA.WK_FR15_DATE_CONTROL)
/*
JOIN CC_COBRA.FR15_FLAGS_HST F
ON   A.AGRMNT_ID = F.AGRMNT_ID
AND  DC.REPORT_DT BETWEEN F.SOURCE_START_DT AND F.SOURCE_END_DT-1
*/
LEFT JOIN CC_COBRA.CC_VERDE_FLAG_MTH V
ON   A.AGRMNT_ID = V.AGRMNT_ID
AND  V.PERIOD_END_DT = (SELECT REPORT_DT FROM CC_COBRA.WK_FR15_DATE_CONTROL)
GROUP BY 1,2,3,4,5,6,7,8,9,10;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.WK_FR15_J09_REPORT_T2 ALL;
.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.WK_FR15_J09_REPORT_T2 
SELECT 
AGRMNT_ID
,PLAN_NO
,ORG
,V_ORG
,LOGO_CD
,VINTAGE_MTH
,LTSB_REL_TYPE_CD
,SEC_FLAG
,BALANC_TYPE_CD
,PERIOD_END_DT
,SUM(OPEN_BALANC_AM)
,SUM(TRADE_XFRIN_AM)
,SUM(TRADE_XFROUT_AM)

,SUM(XFRIN_CHRDSP_AM)
,SUM(XFRIN_RHRDSP_AM)
,SUM(XFRIN_IHRDSP_AM)
,SUM(XFRIN_BHRDSP_AM)
,SUM(XFRIN_MHRDSP_AM)
,SUM(XFRIN_PHRDSP_AM)
,SUM(XFRIN_BXHDSP_AM)
,SUM(XFRIN_MXHDSP_AM)
,SUM(XFRIN_IXHDSP_AM)
,SUM(XFRIN_ISTAT_AM)
,SUM(XFRIN_CIMPRD_AM)
,SUM(XFRIN_RIMPRD_AM)
,SUM(XFRIN_IIMPRD_AM)
,SUM(XFRIN_BIMPRD_AM)
,SUM(XFRIN_MIMPRD_AM)
,SUM(XFRIN_PIMPRD_AM)
,SUM(XFRIN_BXIMPD_AM)
,SUM(XFRIN_MXIMPD_AM)
,SUM(XFRIN_IXIMPD_AM)
,SUM(XFRIN_CIBB_AM)
,SUM(XFRIN_RIBB_AM)
,SUM(XFRIN_IIBB_AM)
,SUM(XFRIN_IZIBB_AM)
,SUM(XFRIN_BIBB_AM)
,SUM(XFRIN_BZIBB_AM)
,SUM(XFRIN_MIBB_AM)
,SUM(XFRIN_MZIBB_AM)
,SUM(XFRIN_PIBB_AM)
,SUM(XFRIN_PZIBB_AM)
,SUM(XFRIN_BXIBB_AM)
,SUM(XFRIN_MXIBB_AM)
,SUM(XFRIN_IXIBB_AM)
,SUM(XFRIN_RNIBB_AM)
,SUM(XFROUT_CHRDSP_AM)
,SUM(XFROUT_RHRDSP_AM)
,SUM(XFROUT_IHRDSP_AM)
,SUM(XFROUT_BHRDSP_AM)
,SUM(XFROUT_MHRDSP_AM)
,SUM(XFROUT_PHRDSP_AM)
,SUM(XFROUT_BXHDSP_AM)
,SUM(XFROUT_MXHDSP_AM)
,SUM(XFROUT_IXHDSP_AM)
,SUM(XFROUT_ISTAT_AM)
,SUM(XFROUT_CIMPRD_AM)
,SUM(XFROUT_RIMPRD_AM)
,SUM(XFROUT_IIMPRD_AM)
,SUM(XFROUT_BIMPRD_AM)
,SUM(XFROUT_MIMPRD_AM)
,SUM(XFROUT_PIMPRD_AM)
,SUM(XFROUT_BXIMPD_AM)
,SUM(XFROUT_MXIMPD_AM)
,SUM(XFROUT_IXIMPD_AM)
,SUM(XFROUT_CIBB_AM)
,SUM(XFROUT_RIBB_AM)
,SUM(XFROUT_IIBB_AM)
,SUM(XFROUT_IZIBB_AM)
,SUM(XFROUT_BIBB_AM)
,SUM(XFROUT_BZIBB_AM)
,SUM(XFROUT_MIBB_AM)
,SUM(XFROUT_MZIBB_AM)
,SUM(XFROUT_PIBB_AM)
,SUM(XFROUT_PZIBB_AM)
,SUM(XFROUT_BXIBB_AM)
,SUM(XFROUT_MXIBB_AM)
,SUM(XFROUT_IXIBB_AM)
,SUM(XFROUT_RNIBB_AM)

,SUM(RETAIL_A_UK_AM) 
,SUM(RETAIL_A_UK_CT) 
,SUM(RETAIL_M_UK_AM)
,SUM(RETAIL_M_UK_CT) 
,SUM(RETAIL_V_UK_AM) 
,SUM(RETAIL_V_UK_CT) 
,SUM(RETAIL_A_FOREGN_AM)
,SUM(RETAIL_A_FOREGN_CT)
,SUM(RETAIL_M_FOREGN_AM) 
,SUM(RETAIL_M_FOREGN_CT)
,SUM(RETAIL_V_FOREGN_AM) 
,SUM(RETAIL_V_FOREGN_CT)
,SUM(CASH_A_UK_AM) 
,SUM(CASH_A_UK_CT)
,SUM(CASH_M_UK_AM) 
,SUM(CASH_M_UK_CT)
,SUM(CASH_V_UK_AM)
,SUM(CASH_V_UK_CT) 
,SUM(CASH_A_FOREGN_AM) 
,SUM(CASH_A_FOREGN_CT) 
,SUM(CASH_M_FOREGN_AM) 
,SUM(CASH_M_FOREGN_CT) 
,SUM(CASH_V_FOREGN_AM) 
,SUM(CASH_V_FOREGN_CT)
,SUM(BALANC_TRNSFR_AM) 
,SUM(BALANC_TRNSFR_CT)
,SUM(MONEY_TRNSFR_AM) 
,SUM(MONEY_TRNSFR_CT)
,SUM(PROMO_CHEQUE_AM)
,SUM(PROMO_CHEQUE_CT) 
,SUM(CONVNC_CHEQUE_AM) 
,SUM(CONVNC_CHEQUE_CT)
,SUM(INTRST_FEE_AM) 
,SUM(INTRST_FEE_REVRSL_AM) 
,SUM(PPI_FEE_AM)
,SUM(PPI_FEE_REVRSL_AM) 
,SUM(BT_FEE_AM)
,SUM(MT_FEE_AM)
,SUM(LATE_FEE_AM)
,SUM(LATE_FEE_REVRSL_AM)
,SUM(OVRLMT_FEE_AM) 
,SUM(OVRLMT_FEE_REVRSL_AM) 
,SUM(RETPMT_FEE_AM)
,SUM(RETPMT_FEE_REVRSL_AM) 
,SUM(MBRSHP_FEE_AM)
,SUM(CSHADV_FEE_AM)
,SUM(SNTNL_FEE_AM)
,SUM(PVYGRD_FEE_AM)
,SUM(FOREX_FEE_AM)
,SUM(OTHER_FEE_AM)
,SUM(BT_OUT_AM)
,SUM(PAYMNT_MIN_AM)
,SUM(PAYMNT_PRTFUL_AM)
,SUM(CHARGE_OFF_AM)
,SUM(ADJMNT_AM)
,SUM(CSHBCK_AM)
,SUM(TRNSFR_AM)
,SUM(WRITE_OFF_AM)
,SUM(FRAUD_AM)
,SUM(UNCLFD_MOVMNT_AM)
,SUM(CLOSE_BALANC_AM)
,SUM(VERDE_IN_AM)
,SUM(VERDE_OUT_AM)
,SUM(AVERAG_MNTHLY_BALANC_AM)
,SUM(BT_OUT_CT) 
FROM CC_COBRA.WK_FR15_J09_REPORT_T1
GROUP BY 1,2,3,4,5,6,7,8,9,10;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.WK_FR15_J09_REPORT_T2
WHERE
ABS(OPEN_BALANC_AM)
+ABS(TRADE_XFRIN_AM)
+ABS(TRADE_XFROUT_AM)

+ABS(XFRIN_CHRDSP_AM)
+ABS(XFRIN_RHRDSP_AM)
+ABS(XFRIN_IHRDSP_AM)
+ABS(XFRIN_BHRDSP_AM)
+ABS(XFRIN_MHRDSP_AM)
+ABS(XFRIN_PHRDSP_AM)
+ABS(XFRIN_BXHDSP_AM)
+ABS(XFRIN_MXHDSP_AM)
+ABS(XFRIN_IXHDSP_AM)
+ABS(XFRIN_ISTAT_AM)
+ABS(XFRIN_CIMPRD_AM)
+ABS(XFRIN_RIMPRD_AM)
+ABS(XFRIN_IIMPRD_AM)
+ABS(XFRIN_BIMPRD_AM)
+ABS(XFRIN_MIMPRD_AM)
+ABS(XFRIN_PIMPRD_AM)
+ABS(XFRIN_BXIMPD_AM)
+ABS(XFRIN_MXIMPD_AM)
+ABS(XFRIN_IXIMPD_AM)
+ABS(XFRIN_CIBB_AM)
+ABS(XFRIN_RIBB_AM)
+ABS(XFRIN_IIBB_AM)
+ABS(XFRIN_IZIBB_AM)
+ABS(XFRIN_BIBB_AM)
+ABS(XFRIN_BZIBB_AM)
+ABS(XFRIN_MIBB_AM)
+ABS(XFRIN_MZIBB_AM)
+ABS(XFRIN_PIBB_AM)
+ABS(XFRIN_PZIBB_AM)
+ABS(XFRIN_BXIBB_AM)
+ABS(XFRIN_MXIBB_AM)
+ABS(XFRIN_IXIBB_AM)
+ABS(XFRIN_RNIBB_AM)
+ABS(XFROUT_CHRDSP_AM)
+ABS(XFROUT_RHRDSP_AM)
+ABS(XFROUT_IHRDSP_AM)
+ABS(XFROUT_BHRDSP_AM)
+ABS(XFROUT_MHRDSP_AM)
+ABS(XFROUT_PHRDSP_AM)
+ABS(XFROUT_BXHDSP_AM)
+ABS(XFROUT_MXHDSP_AM)
+ABS(XFROUT_IXHDSP_AM)
+ABS(XFROUT_ISTAT_AM)
+ABS(XFROUT_CIMPRD_AM)
+ABS(XFROUT_RIMPRD_AM)
+ABS(XFROUT_IIMPRD_AM)
+ABS(XFROUT_BIMPRD_AM)
+ABS(XFROUT_MIMPRD_AM)
+ABS(XFROUT_PIMPRD_AM)
+ABS(XFROUT_BXIMPD_AM)
+ABS(XFROUT_MXIMPD_AM)
+ABS(XFROUT_IXIMPD_AM)
+ABS(XFROUT_CIBB_AM)
+ABS(XFROUT_RIBB_AM)
+ABS(XFROUT_IIBB_AM)
+ABS(XFROUT_IZIBB_AM)
+ABS(XFROUT_BIBB_AM)
+ABS(XFROUT_BZIBB_AM)
+ABS(XFROUT_MIBB_AM)
+ABS(XFROUT_MZIBB_AM)
+ABS(XFROUT_PIBB_AM)
+ABS(XFROUT_PZIBB_AM)
+ABS(XFROUT_IZIBB_AM)
+ABS(XFROUT_BXIBB_AM)
+ABS(XFROUT_MXIBB_AM)
+ABS(XFROUT_IXIBB_AM)
+ABS(XFROUT_RNIBB_AM)

+ABS(RETAIL_A_UK_AM) 
+ABS(RETAIL_A_UK_CT) 
+ABS(RETAIL_M_UK_AM)
+ABS(RETAIL_M_UK_CT) 
+ABS(RETAIL_V_UK_AM) 
+ABS(RETAIL_V_UK_CT) 
+ABS(RETAIL_A_FOREGN_AM)
+ABS(RETAIL_A_FOREGN_CT)
+ABS(RETAIL_M_FOREGN_AM) 
+ABS(RETAIL_M_FOREGN_CT)
+ABS(RETAIL_V_FOREGN_AM) 
+ABS(RETAIL_V_FOREGN_CT)
+ABS(CASH_A_UK_AM) 
+ABS(CASH_A_UK_CT)
+ABS(CASH_M_UK_AM) 
+ABS(CASH_M_UK_CT)
+ABS(CASH_V_UK_AM)
+ABS(CASH_V_UK_CT) 
+ABS(CASH_A_FOREGN_AM) 
+ABS(CASH_A_FOREGN_CT) 
+ABS(CASH_M_FOREGN_AM) 
+ABS(CASH_M_FOREGN_CT) 
+ABS(CASH_V_FOREGN_AM) 
+ABS(CASH_V_FOREGN_CT)
+ABS(BALANC_TRNSFR_AM) 
+ABS(BALANC_TRNSFR_CT)
+ABS(MONEY_TRNSFR_AM) 
+ABS(MONEY_TRNSFR_CT)
+ABS(PROMO_CHEQUE_AM)
+ABS(PROMO_CHEQUE_CT) 
+ABS(CONVNC_CHEQUE_AM) 
+ABS(CONVNC_CHEQUE_CT)
+ABS(INTRST_FEE_AM) 
+ABS(INTRST_FEE_REVRSL_AM) 
+ABS(PPI_FEE_AM)
+ABS(PPI_FEE_REVRSL_AM) 
+ABS(BT_FEE_AM)
+ABS(MT_FEE_AM)
+ABS(LATE_FEE_AM)
+ABS(LATE_FEE_REVRSL_AM)
+ABS(OVRLMT_FEE_AM)
+ABS(OVRLMT_FEE_REVRSL_AM)
+ABS(RETPMT_FEE_AM)
+ABS(RETPMT_FEE_REVRSL_AM)
+ABS(MBRSHP_FEE_AM)
+ABS(CSHADV_FEE_AM)
+ABS(SNTNL_FEE_AM)
+ABS(PVYGRD_FEE_AM)
+ABS(FOREX_FEE_AM)
+ABS(OTHER_FEE_AM)
+ABS(BT_OUT_AM)
+ABS(PAYMNT_MIN_AM)
+ABS(PAYMNT_PRTFUL_AM)
+ABS(CHARGE_OFF_AM)
+ABS(ADJMNT_AM)
+ABS(CSHBCK_AM)
+ABS(TRNSFR_AM)
+ABS(WRITE_OFF_AM)
+ABS(FRAUD_AM)
+ABS(UNCLFD_MOVMNT_AM)
+ABS(CLOSE_BALANC_AM)
+ABS(AVERAG_MNTHLY_BALANC_AM)
+ABS(VERDE_IN_AM)
+ABS(VERDE_OUT_AM)
+ABS(BT_OUT_CT)
=0;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

DELETE FROM CC_COBRA.FR15_NEW_BALANCE_WALK_AGG 
WHERE PERIOD_END_DT = (SELECT REPORT_DT FROM CC_COBRA.WK_FR15_DATE_CONTROL);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.FR15_NEW_BALANCE_WALK_AGG 
SELECT
ORG 
,V_ORG
,A.LOGO_CD
,VINTAGE_MTH
,LTSB_REL_TYPE_CD
,SEC_FLAG
,ORIGNL_CHANNEL_CD AS ACQ_CHANNL
,BALANC_TYPE_CD
,PERIOD_END_DT
,SUM(OPEN_BALANC_AM)*-1 AS OPEN_BALANC_AM
,SUM(TRADE_XFRIN_AM)*-1 AS TRADE_XFRIN_AM
,SUM(TRADE_XFROUT_AM)*-1 AS TRADE_XFROUT_AM

,SUM(XFRIN_CHRDSP_AM)*-1 AS XFRIN_CHRDSP_AM
,SUM(XFRIN_RHRDSP_AM)*-1 AS XFRIN_RHRDSP_AM
,SUM(XFRIN_IHRDSP_AM)*-1 AS XFRIN_IHRDSP_AM
,SUM(XFRIN_BHRDSP_AM)*-1 AS XFRIN_BHRDSP_AM
,SUM(XFRIN_MHRDSP_AM)*-1 AS XFRIN_MHRDSP_AM
,SUM(XFRIN_PHRDSP_AM)*-1 AS XFRIN_PHRDSP_AM
,SUM(XFRIN_BXHDSP_AM)*-1 AS XFRIN_BXHDSP_AM
,SUM(XFRIN_MXHDSP_AM)*-1 AS XFRIN_MXHDSP_AM
,SUM(XFRIN_IXHDSP_AM)*-1 AS XFRIN_IXHDSP_AM
,SUM(XFRIN_ISTAT_AM)*-1 AS XFRIN_ISTAT_AM
,SUM(XFRIN_CIMPRD_AM)*-1 AS XFRIN_CIMPRD_AM
,SUM(XFRIN_RIMPRD_AM)*-1 AS XFRIN_RIMPRD_AM
,SUM(XFRIN_IIMPRD_AM)*-1 AS XFRIN_IIMPRD_AM
,SUM(XFRIN_BIMPRD_AM)*-1 AS XFRIN_BIMPRD_AM
,SUM(XFRIN_MIMPRD_AM)*-1 AS XFRIN_MIMPRD_AM
,SUM(XFRIN_PIMPRD_AM)*-1 AS XFRIN_PIMPRD_AM
,SUM(XFRIN_BXIMPD_AM)*-1 AS XFRIN_BXIMPD_AM
,SUM(XFRIN_MXIMPD_AM)*-1 AS XFRIN_MXIMPD_AM
,SUM(XFRIN_IXIMPD_AM)*-1 AS XFRIN_IXIMPD_AM
,SUM(XFRIN_CIBB_AM)*-1 AS XFRIN_CIBB_AM
,SUM(XFRIN_RIBB_AM)*-1 AS XFRIN_RIBB_AM
,SUM(XFRIN_IIBB_AM)*-1 AS XFRIN_IIBB_AM
,SUM(XFRIN_IZIBB_AM)*-1 AS XFRIN_IZIBB_AM
,SUM(XFRIN_BIBB_AM)*-1 AS XFRIN_BIBB_AM
,SUM(XFRIN_BZIBB_AM)*-1 AS XFRIN_BZIBB_AM
,SUM(XFRIN_MIBB_AM)*-1 AS XFRIN_MIBB_AM
,SUM(XFRIN_MZIBB_AM)*-1 AS XFRIN_MZIBB_AM
,SUM(XFRIN_PIBB_AM)*-1 AS XFRIN_PIBB_AM
,SUM(XFRIN_PZIBB_AM)*-1 AS XFRIN_PZIBB_AM
,SUM(XFRIN_BXIBB_AM)*-1 AS XFRIN_BXIBB_AM
,SUM(XFRIN_MXIBB_AM)*-1 AS XFRIN_MXIBB_AM
,SUM(XFRIN_IXIBB_AM)*-1 AS XFRIN_IXIBB_AM
,SUM(XFRIN_RNIBB_AM)*-1 AS XFRIN_RNIBB_AM
,SUM(XFROUT_CHRDSP_AM)*-1 AS XFROUT_CHRDSP_AM
,SUM(XFROUT_RHRDSP_AM)*-1 AS XFROUT_RHRDSP_AM
,SUM(XFROUT_IHRDSP_AM)*-1 AS XFROUT_IHRDSP_AM
,SUM(XFROUT_BHRDSP_AM)*-1 AS XFROUT_BHRDSP_AM
,SUM(XFROUT_MHRDSP_AM)*-1 AS XFROUT_MHRDSP_AM
,SUM(XFROUT_PHRDSP_AM)*-1 AS XFROUT_PHRDSP_AM
,SUM(XFROUT_BXHDSP_AM)*-1 AS XFROUT_BXHDSP_AM
,SUM(XFROUT_MXHDSP_AM)*-1 AS XFROUT_MXHDSP_AM
,SUM(XFROUT_IXHDSP_AM)*-1 AS XFROUT_IXHDSP_AM
,SUM(XFROUT_ISTAT_AM)*-1 AS XFROUT_ISTAT_AM
,SUM(XFROUT_CIMPRD_AM)*-1 AS XFROUT_CIMPRD_AM
,SUM(XFROUT_RIMPRD_AM)*-1 AS XFROUT_RIMPRD_AM
,SUM(XFROUT_IIMPRD_AM)*-1 AS XFROUT_IIMPRD_AM
,SUM(XFROUT_BIMPRD_AM)*-1 AS XFROUT_BIMPRD_AM
,SUM(XFROUT_MIMPRD_AM)*-1 AS XFROUT_MIMPRD_AM
,SUM(XFROUT_PIMPRD_AM)*-1 AS XFROUT_PIMPRD_AM
,SUM(XFROUT_BXIMPD_AM)*-1 AS XFROUT_BXIMPD_AM
,SUM(XFROUT_MXIMPD_AM)*-1 AS XFROUT_MXIMPD_AM
,SUM(XFROUT_IXIMPD_AM)*-1 AS XFROUT_IXIMPD_AM
,SUM(XFROUT_CIBB_AM)*-1 AS XFROUT_CIBB_AM
,SUM(XFROUT_RIBB_AM)*-1 AS XFROUT_RIBB_AM
,SUM(XFROUT_IIBB_AM)*-1 AS XFROUT_IIBB_AM
,SUM(XFROUT_IZIBB_AM)*-1 AS XFROUT_IZIBB_AM
,SUM(XFROUT_BIBB_AM)*-1 AS XFROUT_BIBB_AM
,SUM(XFROUT_BZIBB_AM)*-1 AS XFROUT_BZIBB_AM
,SUM(XFROUT_MIBB_AM)*-1 AS XFROUT_MIBB_AM
,SUM(XFROUT_MZIBB_AM)*-1 AS XFROUT_MZIBB_AM
,SUM(XFROUT_PIBB_AM)*-1 AS XFROUT_PIBB_AM
,SUM(XFROUT_PZIBB_AM)*-1 AS XFROUT_PZIBB_AM
,SUM(XFROUT_BXIBB_AM)*-1 AS XFROUT_BXIBB_AM
,SUM(XFROUT_MXIBB_AM)*-1 AS XFROUT_MXIBB_AM
,SUM(XFROUT_IXIBB_AM)*-1 AS XFROUT_IXIBB_AM
,SUM(XFROUT_RNIBB_AM)*-1 AS XFROUT_RNIBB_AM

,SUM(RETAIL_A_UK_AM)*-1 AS RETAIL_A_UK_AM
,SUM(RETAIL_A_UK_CT) AS RETAIL_A_UK_CT
,SUM(RETAIL_M_UK_AM)*-1 AS RETAIL_M_UK_AM
,SUM(RETAIL_M_UK_CT) AS RETAIL_M_UK_CT
,SUM(RETAIL_V_UK_AM)*-1 AS RETAIL_V_UK_AM
,SUM(RETAIL_V_UK_CT) AS RETAIL_V_UK_CT
,SUM(RETAIL_A_FOREGN_AM)*-1 AS RETAIL_A_FOREGN_AM
,SUM(RETAIL_A_FOREGN_CT) AS RETAIL_A_FOREGN_CT
,SUM(RETAIL_M_FOREGN_AM)*-1 AS RETAIL_M_FOREGN_AM
,SUM(RETAIL_M_FOREGN_CT) AS RETAIL_M_FOREGN_CT
,SUM(RETAIL_V_FOREGN_AM)*-1 AS RETAIL_V_FOREGN_AM
,SUM(RETAIL_V_FOREGN_CT) AS RETAIL_V_FOREGN_CT
,SUM(CASH_A_UK_AM)*-1 AS CASH_A_UK_AM
,SUM(CASH_A_UK_CT) AS CASH_A_UK_CT
,SUM(CASH_M_UK_AM)*-1 AS CASH_M_UK_AM
,SUM(CASH_M_UK_CT) AS CASH_M_UK_CT
,SUM(CASH_V_UK_AM)*-1 AS CASH_V_UK_AM
,SUM(CASH_V_UK_CT) AS CASH_V_UK_CT
,SUM(CASH_A_FOREGN_AM)*-1 AS CASH_A_FOREGN_AM
,SUM(CASH_A_FOREGN_CT) AS CASH_A_FOREGN_CT
,SUM(CASH_M_FOREGN_AM)*-1 AS CASH_M_FOREGN_AM
,SUM(CASH_M_FOREGN_CT) AS CASH_M_FOREGN_CT
,SUM(CASH_V_FOREGN_AM)*-1 AS CASH_V_FOREGN_AM
,SUM(CASH_V_FOREGN_CT) AS CASH_V_FOREGN_CT
,SUM(BALANC_TRNSFR_AM)*-1 AS BALANC_TRNSFR_AM
,SUM(BALANC_TRNSFR_CT) AS BALANC_TRNSFR_CT
,SUM(MONEY_TRNSFR_AM)*-1 AS MONEY_TRNSFR_AM
,SUM(MONEY_TRNSFR_CT) AS MONEY_TRNSFR_CT
,SUM(PROMO_CHEQUE_AM)*-1 AS PROMO_CHEQUE_AM
,SUM(PROMO_CHEQUE_CT) AS PROMO_CHEQUE_CT
,SUM(CONVNC_CHEQUE_AM)*-1 AS CONVNC_CHEQUE_AM
,SUM(CONVNC_CHEQUE_CT) AS CONVNC_CHEQUE_CT
,SUM(INTRST_FEE_AM)*-1 AS INTRST_FEE_AM
,SUM(INTRST_FEE_REVRSL_AM)*-1 AS INTRST_FEE_REVRSL_AM
,SUM(PPI_FEE_AM)*-1 AS PPI_FEE_AM
,SUM(PPI_FEE_REVRSL_AM)*-1 AS PPI_FEE_REVRSL_AM
,SUM(BT_FEE_AM)*-1 AS BT_FEE_AM
,SUM(MT_FEE_AM)*-1 AS MT_FEE_AM
,SUM(LATE_FEE_AM)*-1 AS LATE_FEE_AM
,SUM(LATE_FEE_REVRSL_AM)*-1 AS LATE_FEE_REVRSL_AM
,SUM(OVRLMT_FEE_AM)*-1 AS OVRLMT_FEE_AM
,SUM(OVRLMT_FEE_REVRSL_AM)*-1 AS OVRLMT_FEE_REVRSL_AM
,SUM(RETPMT_FEE_AM)*-1 AS RETPMT_FEE_AM
,SUM(RETPMT_FEE_REVRSL_AM)*-1 AS RETPMT_FEE_REVRSL_AM
,SUM(MBRSHP_FEE_AM)*-1 AS MBRSHP_FEE_AM
,SUM(CSHADV_FEE_AM)*-1 AS CSHADV_FEE_AM
,SUM(SNTNL_FEE_AM)*-1 AS SNTNL_FEE_AM
,SUM(PVYGRD_FEE_AM)*-1 AS PVYGRD_FEE_AM
,SUM(FOREX_FEE_AM)*-1 AS FOREX_FEE_AM
,SUM(OTHER_FEE_AM)*-1 AS OTHER_FEE_AM
,SUM(BT_OUT_AM)*-1 AS BT_OUT_AM
,SUM(PAYMNT_MIN_AM)*-1 AS PAYMNT_MIN_AM
,SUM(PAYMNT_PRTFUL_AM)*-1 AS PAYMNT_PRTFUL_AM
,SUM(CHARGE_OFF_AM)*-1 AS CHARGE_OFF_AM
,SUM(ADJMNT_AM)*-1 AS ADJMNT_AM
,SUM(CSHBCK_AM)*-1 AS CSHBCK_AM
,SUM(TRNSFR_AM)*-1 AS TRNSFR_AM
,SUM(WRITE_OFF_AM)*-1 AS WRITE_OFF_AM
,SUM(FRAUD_AM)*-1 AS FRAUD_AM
,SUM(UNCLFD_MOVMNT_AM)*-1 AS UNCLFD_MOVMNT_AM
,SUM(CLOSE_BALANC_AM)*-1 AS CLOSE_BALANC_AM
,SUM(VERDE_IN_AM)*-1 AS VERDE_IN_AM
,SUM(VERDE_OUT_AM)*-1 AS VERDE_OUT_AM
,SUM(AVERAG_MNTHLY_BALANC_AM)*-1 AS AVERAG_MNTHLY_BALANC_AM
,SUM(CASE WHEN VERDE_OUT_AM <> 0 
AND
ABS(OPEN_BALANC_AM)
+ABS(TRADE_XFRIN_AM)
+ABS(TRADE_XFROUT_AM)

+ABS(XFRIN_CHRDSP_AM)
+ABS(XFRIN_RHRDSP_AM)
+ABS(XFRIN_IHRDSP_AM)
+ABS(XFRIN_BHRDSP_AM)
+ABS(XFRIN_MHRDSP_AM)
+ABS(XFRIN_PHRDSP_AM)
+ABS(XFRIN_BXHDSP_AM)
+ABS(XFRIN_MXHDSP_AM)
+ABS(XFRIN_IXHDSP_AM)
+ABS(XFRIN_ISTAT_AM)
+ABS(XFRIN_CIMPRD_AM)
+ABS(XFRIN_RIMPRD_AM)
+ABS(XFRIN_IIMPRD_AM)
+ABS(XFRIN_BIMPRD_AM)
+ABS(XFRIN_MIMPRD_AM)
+ABS(XFRIN_PIMPRD_AM)
+ABS(XFRIN_BXIMPD_AM)
+ABS(XFRIN_MXIMPD_AM)
+ABS(XFRIN_IXIMPD_AM)
+ABS(XFRIN_CIBB_AM)
+ABS(XFRIN_RIBB_AM)
+ABS(XFRIN_IIBB_AM)
+ABS(XFRIN_IZIBB_AM)
+ABS(XFRIN_BIBB_AM)
+ABS(XFRIN_BZIBB_AM)
+ABS(XFRIN_MIBB_AM)
+ABS(XFRIN_MZIBB_AM)
+ABS(XFRIN_PIBB_AM)
+ABS(XFRIN_PZIBB_AM)
+ABS(XFRIN_BXIBB_AM)
+ABS(XFRIN_MXIBB_AM)
+ABS(XFRIN_IXIBB_AM)
+ABS(XFRIN_RNIBB_AM)
+ABS(XFROUT_CHRDSP_AM)
+ABS(XFROUT_RHRDSP_AM)
+ABS(XFROUT_IHRDSP_AM)
+ABS(XFROUT_BHRDSP_AM)
+ABS(XFROUT_MHRDSP_AM)
+ABS(XFROUT_PHRDSP_AM)
+ABS(XFROUT_BXHDSP_AM)
+ABS(XFROUT_MXHDSP_AM)
+ABS(XFROUT_IXHDSP_AM)
+ABS(XFROUT_ISTAT_AM)
+ABS(XFROUT_CIMPRD_AM)
+ABS(XFROUT_RIMPRD_AM)
+ABS(XFROUT_IIMPRD_AM)
+ABS(XFROUT_BIMPRD_AM)
+ABS(XFROUT_MIMPRD_AM)
+ABS(XFROUT_PIMPRD_AM)
+ABS(XFROUT_BXIMPD_AM)
+ABS(XFROUT_MXIMPD_AM)
+ABS(XFROUT_IXIMPD_AM)
+ABS(XFROUT_CIBB_AM)
+ABS(XFROUT_RIBB_AM)
+ABS(XFROUT_IIBB_AM)
+ABS(XFROUT_IZIBB_AM)
+ABS(XFROUT_BIBB_AM)
+ABS(XFROUT_BZIBB_AM)
+ABS(XFROUT_MIBB_AM)
+ABS(XFROUT_MZIBB_AM)
+ABS(XFROUT_PIBB_AM)
+ABS(XFROUT_PZIBB_AM)
+ABS(XFROUT_BXIBB_AM)
+ABS(XFROUT_MXIBB_AM)
+ABS(XFROUT_IXIBB_AM)
+ABS(XFROUT_RNIBB_AM)

+ABS(RETAIL_A_UK_AM) 
+ABS(RETAIL_A_UK_CT) 
+ABS(RETAIL_M_UK_AM)
+ABS(RETAIL_M_UK_CT) 
+ABS(RETAIL_V_UK_AM) 
+ABS(RETAIL_V_UK_CT) 
+ABS(RETAIL_A_FOREGN_AM)
+ABS(RETAIL_A_FOREGN_CT)
+ABS(RETAIL_M_FOREGN_AM) 
+ABS(RETAIL_M_FOREGN_CT)
+ABS(RETAIL_V_FOREGN_AM) 
+ABS(RETAIL_V_FOREGN_CT)
+ABS(CASH_A_UK_AM) 
+ABS(CASH_A_UK_CT)
+ABS(CASH_M_UK_AM) 
+ABS(CASH_M_UK_CT)
+ABS(CASH_V_UK_AM)
+ABS(CASH_V_UK_CT) 
+ABS(CASH_A_FOREGN_AM) 
+ABS(CASH_A_FOREGN_CT) 
+ABS(CASH_M_FOREGN_AM) 
+ABS(CASH_M_FOREGN_CT) 
+ABS(CASH_V_FOREGN_AM) 
+ABS(CASH_V_FOREGN_CT)
+ABS(BALANC_TRNSFR_AM) 
+ABS(BALANC_TRNSFR_CT)
+ABS(MONEY_TRNSFR_AM) 
+ABS(MONEY_TRNSFR_CT)
+ABS(PROMO_CHEQUE_AM)
+ABS(PROMO_CHEQUE_CT) 
+ABS(CONVNC_CHEQUE_AM) 
+ABS(CONVNC_CHEQUE_CT)
+ABS(INTRST_FEE_AM) 
+ABS(INTRST_FEE_REVRSL_AM) 
+ABS(PPI_FEE_AM)
+ABS(PPI_FEE_REVRSL_AM)
+ABS(BT_FEE_AM)
+ABS(MT_FEE_AM)
+ABS(LATE_FEE_AM)
+ABS(LATE_FEE_REVRSL_AM)
+ABS(OVRLMT_FEE_AM)
+ABS(OVRLMT_FEE_REVRSL_AM)
+ABS(RETPMT_FEE_AM)
+ABS(RETPMT_FEE_REVRSL_AM)
+ABS(MBRSHP_FEE_AM)
+ABS(CSHADV_FEE_AM)
+ABS(SNTNL_FEE_AM)
+ABS(PVYGRD_FEE_AM)
+ABS(FOREX_FEE_AM)
+ABS(OTHER_FEE_AM)
+ABS(BT_OUT_AM)
+ABS(PAYMNT_MIN_AM)
+ABS(PAYMNT_PRTFUL_AM)
+ABS(CHARGE_OFF_AM)
+ABS(ADJMNT_AM)
+ABS(CSHBCK_AM)
+ABS(TRNSFR_AM)
+ABS(WRITE_OFF_AM)
+ABS(FRAUD_AM)
+ABS(UNCLFD_MOVMNT_AM)
+ABS(CLOSE_BALANC_AM)
+ABS(AVERAG_MNTHLY_BALANC_AM)
+ABS(VERDE_IN_AM)
+ABS(BT_OUT_CT)
=0
THEN 0 ELSE 1 END) AS COUNT_ACCOUNTS
,SUM(BT_OUT_CT) AS BT_OUT_CT
FROM CC_COBRA.WK_FR15_J09_REPORT_T2 A
JOIN CC_COBRA.FR15_FLAGS_STATIC B
ON   A.AGRMNT_ID = B.AGRMNT_ID
WHERE BALANC_TYPE_CD IS NOT NULL
GROUP BY 1,2,3,4,5,6,7,8,9;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR15_NEW_BALANCE_WALK_AGG 
INDEX( ORG ,V_ORG ,LOGO_CD ,VINTAGE_MTH ,LTSB_REL_TYPE_CD ,
SEC_FLAG ,ACQ_CHANNL ,BALANC_TYPE_CD ,PERIOD_END_DT );

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


DELETE FROM CC_COBRA.WK_FR15_J09_REPORT_T1 ALL;
DELETE FROM CC_COBRA.WK_FR15_J09_REPORT_T2 ALL;


DELETE FROM CC_COBRA.FR15_MIA_BALANCE_WALK_AGG 
WHERE PERIOD_END_DT = (SELECT REPORT_DT FROM CC_COBRA.WK_FR15_DATE_CONTROL);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.FR15_MIA_BALANCE_WALK_AGG 
SELECT 
 	A.ORG		
,	A.V_ORG		
,	A.LOGO_CD		
,	A.VINTAGE_MTH		
,	A.LTSB_REL_TYPE_CD		
,	A.SEC_FLAG		
,	A.ACQ_CHANNL		
,   B.MIA_BALANC_TYPE_CD AS BALANC_TYPE_CD		
,	PERIOD_END_DT		
,SUM(	OPEN_BALANC_AM	)	AS OPEN_BALANC_AM
,SUM(	TRADE_XFRIN_AM	)	AS TRADE_XFRIN_AM
,SUM(	TRADE_XFROUT_AM	)	AS TRADE_XFROUT_AM
, SUM ( CASE WHEN A.BALANC_TYPE_CD IN ('BHRDSP','BXHDSP','CHRDSP','IHRDSP','IXHDSP','MHRDSP','MXHDSP','PHRDSP','RHRDSP','ISTAT') THEN 0 
             ELSE XFRIN_BHRDSP_AM+XFRIN_BXHDSP_AM+XFRIN_CHRDSP_AM+XFRIN_IHRDSP_AM+XFRIN_IXHDSP_AM+XFRIN_MHRDSP_AM+XFRIN_MXHDSP_AM+XFRIN_PHRDSP_AM+XFRIN_RHRDSP_AM+XFRIN_ISTAT_AM END ) AS XFRIN_HRDSP_AM 
, SUM ( CASE WHEN A.BALANC_TYPE_CD IN ('BIMPRD','BXIMPD','CIMPRD','IIMPRD','IXIMPD','MIMPRD','MXIMPD','PIMPRD','RIMPRD') THEN 0 
             ELSE XFRIN_BIMPRD_AM+XFRIN_BXIMPD_AM+XFRIN_CIMPRD_AM+XFRIN_IIMPRD_AM+XFRIN_IXIMPD_AM+XFRIN_MIMPRD_AM+XFRIN_MXIMPD_AM+XFRIN_PIMPRD_AM+XFRIN_RIMPRD_AM END ) AS XFRIN_IMPRD_AM 
,SUM(	XFRIN_CIBB_AM	)	AS XFRIN_CIBB_AM
, SUM ( CASE WHEN A.BALANC_TYPE_CD IN ('RIBB','IIBB','IXIBB') THEN 0 ELSE XFRIN_RIBB_AM+XFRIN_IIBB_AM+XFRIN_IXIBB_AM END ) AS XFRIN_RIBB_AM 
,SUM(	XFRIN_BIBB_AM	)	AS XFRIN_BIBB_AM
,SUM(	XFRIN_BZIBB_AM	)	AS XFRIN_BZIBB_AM
,SUM(	XFRIN_BXIBB_AM	)	AS XFRIN_BXIBB_AM
,SUM(	XFRIN_MIBB_AM	)	AS XFRIN_MIBB_AM
,SUM(	XFRIN_MZIBB_AM	)	AS XFRIN_MZIBB_AM
,SUM(	XFRIN_MXIBB_AM	)	AS XFRIN_MXIBB_AM
,SUM(	XFRIN_PIBB_AM	)	AS XFRIN_PIBB_AM
, SUM ( CASE WHEN A.BALANC_TYPE_CD IN ('IZIBB','PZIBB') THEN 0 ELSE XFRIN_IZIBB_AM+XFRIN_PZIBB_AM END ) AS XFRIN_PZIBB_AM 
,SUM(	XFRIN_RNIBB_AM	)	AS XFRIN_RNIBB_AM

, SUM ( CASE WHEN A.BALANC_TYPE_CD IN ('BHRDSP','BXHDSP','CHRDSP','IHRDSP','IXHDSP','MHRDSP','MXHDSP','PHRDSP','RHRDSP','ISTAT') THEN 0 
             ELSE XFROUT_BHRDSP_AM+XFROUT_BXHDSP_AM+XFROUT_CHRDSP_AM+XFROUT_IHRDSP_AM+XFROUT_IXHDSP_AM+XFROUT_MHRDSP_AM+XFROUT_MXHDSP_AM+XFROUT_PHRDSP_AM+XFROUT_RHRDSP_AM+XFROUT_ISTAT_AM END ) AS XFROUT_HRDSP_AM 
, SUM ( CASE WHEN A.BALANC_TYPE_CD IN ('BIMPRD','BXIMPD','CIMPRD','IIMPRD','IXIMPD','MIMPRD','MXIMPD','PIMPRD','RIMPRD') THEN 0 
             ELSE XFROUT_BIMPRD_AM+XFROUT_BXIMPD_AM+XFROUT_CIMPRD_AM+XFROUT_IIMPRD_AM+XFROUT_IXIMPD_AM+XFROUT_MIMPRD_AM+XFROUT_MXIMPD_AM+XFROUT_PIMPRD_AM+XFROUT_RIMPRD_AM END ) AS XFROUT_IMPRD_AM 
,SUM(	XFROUT_CIBB_AM	)	AS XFROUT_CIBB_AM
, SUM ( CASE WHEN A.BALANC_TYPE_CD IN ('RIBB','IIBB','IXIBB') THEN 0 ELSE XFROUT_RIBB_AM+XFROUT_IIBB_AM+XFROUT_IXIBB_AM END ) AS XFROUT_RIBB_AM 
,SUM(	XFROUT_BIBB_AM	)	AS XFROUT_BIBB_AM
,SUM(	XFROUT_BZIBB_AM	)	AS XFROUT_BZIBB_AM
,SUM(	XFROUT_BXIBB_AM	)	AS XFROUT_BXIBB_AM
,SUM(	XFROUT_MIBB_AM	)	AS XFROUT_MIBB_AM
,SUM(	XFROUT_MZIBB_AM	)	AS XFROUT_MZIBB_AM
,SUM(	XFROUT_MXIBB_AM	)	AS XFROUT_MXIBB_AM
,SUM(	XFROUT_PIBB_AM	)	AS XFROUT_PIBB_AM
, SUM ( CASE WHEN A.BALANC_TYPE_CD IN ('IZIBB','PZIBB') THEN 0 ELSE XFROUT_IZIBB_AM+XFROUT_PZIBB_AM END ) AS XFROUT_PZIBB_AM 
,SUM(	XFROUT_RNIBB_AM	)	AS XFROUT_RNIBB_AM

,SUM(	RETAIL_A_UK_AM	)	AS RETAIL_A_UK_AM
,SUM(	RETAIL_A_UK_CT	)	AS RETAIL_A_UK_CT
,SUM(	RETAIL_M_UK_AM	)	AS RETAIL_M_UK_AM
,SUM(	RETAIL_M_UK_CT	)	AS RETAIL_M_UK_CT
,SUM(	RETAIL_V_UK_AM	)	AS RETAIL_V_UK_AM
,SUM(	RETAIL_V_UK_CT	)	AS RETAIL_V_UK_CT
,SUM(	RETAIL_A_FOREGN_AM	)	AS RETAIL_A_FOREGN_AM
,SUM(	RETAIL_A_FOREGN_CT	)	AS RETAIL_A_FOREGN_CT
,SUM(	RETAIL_M_FOREGN_AM	)	AS RETAIL_M_FOREGN_AM
,SUM(	RETAIL_M_FOREGN_CT	)	AS RETAIL_M_FOREGN_CT
,SUM(	RETAIL_V_FOREGN_AM	)	AS RETAIL_V_FOREGN_AM
,SUM(	RETAIL_V_FOREGN_CT	)	AS RETAIL_V_FOREGN_CT
,SUM(	CASH_A_UK_AM	)	AS CASH_A_UK_AM
,SUM(	CASH_A_UK_CT	)	AS CASH_A_UK_CT
,SUM(	CASH_M_UK_AM	)	AS CASH_M_UK_AM
,SUM(	CASH_M_UK_CT	)	AS CASH_M_UK_CT
,SUM(	CASH_V_UK_AM	)	AS CASH_V_UK_AM
,SUM(	CASH_V_UK_CT	)	AS CASH_V_UK_CT
,SUM(	CASH_A_FOREGN_AM	)	AS CASH_A_FOREGN_AM
,SUM(	CASH_A_FOREGN_CT	)	AS CASH_A_FOREGN_CT
,SUM(	CASH_M_FOREGN_AM	)	AS CASH_M_FOREGN_AM
,SUM(	CASH_M_FOREGN_CT	)	AS CASH_M_FOREGN_CT
,SUM(	CASH_V_FOREGN_AM	)	AS CASH_V_FOREGN_AM
,SUM(	CASH_V_FOREGN_CT	)	AS CASH_V_FOREGN_CT
,SUM(	BALANC_TRNSFR_AM	)	AS BALANC_TRNSFR_AM
,SUM(	BALANC_TRNSFR_CT	)	AS BALANC_TRNSFR_CT
,SUM(	MONEY_TRNSFR_AM	)	AS MONEY_TRNSFR_AM
,SUM(	MONEY_TRNSFR_CT	)	AS MONEY_TRNSFR_CT
,SUM(	PROMO_CHEQUE_AM	)	AS PROMO_CHEQUE_AM
,SUM(	PROMO_CHEQUE_CT	)	AS PROMO_CHEQUE_CT
,SUM(	CONVNC_CHEQUE_AM	)	AS CONVNC_CHEQUE_AM
,SUM(	CONVNC_CHEQUE_CT	)	AS CONVNC_CHEQUE_CT
,SUM(	INTRST_FEE_AM	)	AS INTRST_FEE_AM
,SUM(	INTRST_FEE_REVRSL_AM	)	AS INTRST_FEE_REVRSL_AM
,SUM(	PPI_FEE_AM	)	AS PPI_FEE_AM
,SUM(	PPI_FEE_REVRSL_AM	)	AS PPI_FEE_REVRSL_AM
,SUM(	BT_FEE_AM	)	AS BT_FEE_AM
,SUM(	MT_FEE_AM	)	AS MT_FEE_AM
,SUM(	LATE_FEE_AM	)	AS LATE_FEE_AM
,SUM(	LATE_FEE_REVRSL_AM	)	AS LATE_FEE_REVRSL_AM
,SUM(	OVRLMT_FEE_AM	)	AS OVRLMT_FEE_AM
,SUM(	OVRLMT_FEE_REVRSL_AM	)	AS OVRLMT_FEE_REVRSL_AM
,SUM(	RETPMT_FEE_AM	)	AS RETPMT_FEE_AM
,SUM(	RETPMT_FEE_REVRSL_AM	)	AS RETPMT_FEE_REVRSL_AM
,SUM(	MBRSHP_FEE_AM	)	AS MBRSHP_FEE_AM
,SUM(	CSHADV_FEE_AM	)	AS CSHADV_FEE_AM
,SUM(	SNTNL_FEE_AM	)	AS SNTNL_FEE_AM
,SUM(	PVYGRD_FEE_AM	)	AS PVYGRD_FEE_AM
,SUM(	FOREX_FEE_AM	)	AS FOREX_FEE_AM
,SUM(	OTHER_FEE_AM	)	AS OTHER_FEE_AM
,SUM(	BT_OUT_AM	)	AS BT_OUT_AM
,SUM(	PAYMNT_MIN_AM	)	AS PAYMNT_MIN_AM
,SUM(	PAYMNT_PRTFUL_AM	)	AS PAYMNT_PRTFUL_AM
,SUM(	CHARGE_OFF_AM	)	AS CHARGE_OFF_AM
,SUM(	ADJMNT_AM	)	AS ADJMNT_AM
,SUM(	CSHBCK_AM	)	AS CSHBCK_AM
,SUM(	TRNSFR_AM	)	AS TRNSFR_AM
,SUM(	WRITE_OFF_AM	)	AS WRITE_OFF_AM
,SUM(	FRAUD_AM	)	AS FRAUD_AM
,SUM(	UNCLFD_MOVMNT_AM	)	AS UNCLFD_MOVMNT_AM
,SUM(	CLOSE_BALANC_AM	)	AS CLOSE_BALANC_AM
,SUM(	VERDE_IN_AM	)	AS VERDE_IN_AM
,SUM(	VERDE_OUT_AM	)	AS VERDE_OUT_AM
,SUM(	AVERAG_MNTHLY_BALANC_AM	)	AS AVERAG_MNTHLY_BALANC_AM
,SUM(	COUNT_PLANS	)	AS COUNT_PLANS
,SUM(	BT_OUT_CT	)	AS BT_OUT_CT

FROM CC_COBRA.FR15_NEW_BALANCE_WALK_AGG A
LEFT JOIN CC_COBRA.FR15_BALANC_TYPE_CD_LOOKUP B
ON   A.BALANC_TYPE_CD = B.BALANC_TYPE_CD
WHERE PERIOD_END_DT = (SELECT REPORT_DT FROM CC_COBRA.WK_FR15_DATE_CONTROL)
GROUP BY 1,2,3,4,5,6,7,8,9
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR15_MIA_BALANCE_WALK_AGG 
INDEX( ORG ,V_ORG ,LOGO_CD ,VINTAGE_MTH ,LTSB_REL_TYPE_CD ,
SEC_FLAG ,ACQ_CHANNL ,BALANC_TYPE_CD ,PERIOD_END_DT );


/*UPDATE THE LOG TABLE IF IT HAS RUN OK!*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  CURRENT_LOAD_DT = (SELECT START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , UPDATE_DT = DATE
   , UPDATE_TM = TIME
   , LOAD_STATUS = 'C'
WHERE GRID_LOAD_ID = 'FR15A'
;
.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

SELECT GRID_LOAD_ID, CURRENT_BUS_DT, CURRENT_LOAD_DT   
FROM CC_COBRA.CC_COBRA_LOAD_LOG WHERE GRID_LOAD_ID = 'FR15A';

.QUIT;

.LABEL SKIPJOB;

.QUIT;

.LABEL GRIDERROR;

.QUIT;

.LABEL FOUNDERROR;

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  LOAD_STATUS = 'F'
WHERE GRID_LOAD_ID = 'FR15A'
;

.QUIT 0;

