/************************************************************************/
/*JOB:      FR25 - NEW ACCOUNTS                                         */
/*VERSION:  FR25v02 - remove dependency on AGREEMENT.sql                */
/*DATE VERSION IMPLEMENTED: 2016-01-26                                  */
/*DEPENDENCIES:                                                         */
/*C01J01                                                                */
/*C01J02                                                                */
/*C01J08                                                                */
/*C01J13                                                                */
/************************************************************************/

.SET ERRORLEVEL (2641,3603) SEVERITY 4, UNKNOWN SEVERITY 8

SET QUERY_BAND = 'APPLICATIONNAME=CC_FINANCE_DAILY_RUN;JOBID=GRFD043;WORKTYPE=TRIPLER;VERSION=LBG;' FOR SESSION;

DATABASE CC_COBRA;

/*STEP 01: CHECK PRIOR JOBS FOR COMPLETION*/

/*INITIAL CHECKS TO SEE IF DAILY LOAD IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J01';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF CC_AGREEMENT_ADDED_DATE IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J02';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF AGREEMENT_STATIC_DAILY IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J08';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF CC_AGREEMENT_CHANNEL IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J13';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF THIS JOB HAS ALREADY RUN SUCCESSFULLY*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'FR25';

.IF ACTIVITYCOUNT <> 0 THEN .GOTO SKIPJOB;

/*SET THE STATUS START DT/TM*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
FROM CC_COBRA.CC_COBRA_LOAD_STATUS A
SET RUN_ID = A.RUN_ID
,   LOAD_STATUS = 'I'
,   LOAD_START_DT = DATE
,   LOAD_START_TM = TIME
WHERE CC_COBRA.CC_COBRA_LOAD_LOG.GRID_LOAD_ID = 'FR25'
AND   A.RUN_STATUS = 'I'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*STEP 02: UPDATE DATE PARAMETER TABLE*/

/*
CREATE SET TABLE CC_COBRA.WK_FR25_REPORT_DATE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      REPORT_DT DATE FORMAT 'YY/MM/DD')
UNIQUE PRIMARY INDEX ( REPORT_DT );
*/

UPDATE CC_COBRA.WK_FR25_REPORT_DATE
SET REPORT_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT);         
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.WK_FR25_REPORT_DATE INDEX(REPORT_DT);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*DISPLAY DATE INSERTED ABOVE FOR OUTPUT*/

SELECT * FROM CC_COBRA.WK_FR25_REPORT_DATE;

/*CREATE SUMMARY*/
/*
CREATE TABLE CC_COBRA.FR25_NEW_ACCOUNTS_SUMMARY (
QRY_RUN_DT DATE
,ORG_TX CHAR(3) COMPRESS ('120','170','190','195')
,V_ORG CHAR(3) 
,ADDED_DT DATE
,OPENED_DT DATE
,AGRMNT_OPEN_REASON_CD CHAR(1) 
,AGRMNT_RLTNSP_CD CHAR(1) COMPRESS ('T','N','M')
,CHANNL_CD CHAR(1) COMPRESS ('B','G','E','C','S','D','T','I','A','0')
,REGION_ORGNSN_NM VARCHAR(100)
,COUNT_ACCS INTEGER
)
PRIMARY INDEX(V_ORG,ADDED_DT,OPENED_DT,AGRMNT_OPEN_REASON_CD);
*/

/* ACCOUNTS QUERY*/

DELETE FROM CC_COBRA.FR25_NEW_ACCOUNTS_SUMMARY WHERE QRY_RUN_DT = DATE;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR; 

INSERT INTO CC_COBRA.FR25_NEW_ACCOUNTS_SUMMARY	
SELECT
DATE AS QRY_RUN_DT
,CCA.ORG_TX AS ORG 
,CCA.V_ORG 
,CCA.ADDED_DT
,CCA.OPENED_DT
,ASD.AGRMNT_OPEN_REASON_CD
,CASE WHEN AR.AGRMNT_RLTNSP_TYPE_CD = '00500001' THEN 'T'
      WHEN AR.AGRMNT_RLTNSP_TYPE_CD = '00500002' THEN 'M'
      WHEN CCA.ADDED_DT = '2013/05/11' THEN 'M'
      ELSE 'N' END AS AR_TYPE
,ACH.CHANNL_CD
,CASE WHEN ACH.REGION_ORGNSN_NM IS NULL THEN 'N/A' ELSE ACH.REGION_ORGNSN_NM END BRANCH_REGION
,COUNT (DISTINCT(CCA.AGRMNT_ID)) AS COUNT_ACCS
FROM CC_COBRA.CC_AGREEMENT_ADDED_DATE CCA
JOIN CC_COBRA.WK_FR25_REPORT_DATE DC
ON   CCA.ADDED_DT/100 = DC.REPORT_DT/100
AND  (		CCA.PURGED_DT IS NULL
		OR  CCA.PURGED_DT > DC.REPORT_DT)
JOIN CC_COBRA.AGREEMENT_STATIC_DAILY ASD
ON   CCA.AGRMNT_ID = ASD.AGRMNT_ID
JOIN GDW_VIEWSX.AGREEMENT_STATUS_SUMMARY ASS 
ON   CCA.AGRMNT_ID = ASS.AGRMNT_ID
AND  ASS.AGRMNT_STATUS_SUMMRY_TYPE_CD = '00500026'
AND  ASS.SOURCE_END_DT = '3500/12/31'
LEFT JOIN GDW_VIEWSX.AGREEMENT_RELATIONSHIP AR
ON   CCA.AGRMNT_ID = AR.AGRMNT_ID
LEFT JOIN CC_COBRA.CC_AGREEMENT_CHANNEL ACH
ON   CCA.AGRMNT_ID = ACH.AGRMNT_ID
GROUP BY 1,2,3,4,5,6,7,8,9;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR; 

COLLECT STATS ON CC_COBRA.FR25_NEW_ACCOUNTS_SUMMARY INDEX(V_ORG,ADDED_DT,OPENED_DT,AGRMNT_OPEN_REASON_CD);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR; 

/*UPDATE THE LOG TABLE IF IT HAS RUN OK!*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  CURRENT_LOAD_DT = (SELECT START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , UPDATE_DT = DATE
   , UPDATE_TM = TIME
   , LOAD_STATUS = 'C'
WHERE GRID_LOAD_ID = 'FR25'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

SELECT GRID_LOAD_ID, CURRENT_BUS_DT, CURRENT_LOAD_DT   
FROM CC_COBRA.CC_COBRA_LOAD_LOG WHERE GRID_LOAD_ID = 'FR25';

.QUIT;

.LABEL SKIPJOB;

.QUIT;

.LABEL GRIDERROR;

.QUIT;

.LABEL FOUNDERROR;

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  LOAD_STATUS = 'F'
WHERE GRID_LOAD_ID = 'FR25'
;

.QUIT 0;

