/************************************************************************/
/*JOB:      FR35 - PREFERENCE MONTH END SPOT BALANCE AND MONTHLY TXNS   */
/*VERSION:  FR35v01.sql                                                 */
/*DATE VERSION IMPLEMENTED: 2015-09-29                                  */
/*DEPENDENCIES:                                                         */
/*C01J01                                                                */
/*C01J02                                                                */
/*C01J04                                                                */
/*C01J14                                                                */
/*FR20                                                                  */
/************************************************************************/

.SET ERRORLEVEL (2641,3603) SEVERITY 4, UNKNOWN SEVERITY 8

SET QUERY_BAND = 'ApplicationName=CC_Finance_daily_run;JobID=GRFD043;Worktype=TripleR;Version=LBG;' FOR SESSION;

DATABASE CC_COBRA;

/*STEP 01: CHECK PRIOR JOBS FOR COMPLETION*/

/*INITIAL CHECKS TO SEE IF DAILY LOAD IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J01';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF CC_EVENTS_TO_EXCLUDE IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J04';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF CC_AGREEMENT_ME_SNAPSHOT IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J14';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF CC_AGREEMENT_ADDED_DATE IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J02';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF CC_MONETARY_TRANSACTION_LM IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'FR20';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF THIS JOB HAS ALREADY RUN SUCCESSFULLY*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'FR35';

.IF ACTIVITYCOUNT <> 0 THEN .GOTO SKIPJOB;

/*STEP 02: CHECKS TO SEE IF WORKING DAY IS WD1 */

SELECT * FROM CC_COBRA.GRID_REPORTS_CONTROL 
WHERE (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT) = PRIOR_WORKDAY_DT
AND WORKDAY_OF_MONTH = 1;

.IF ACTIVITYCOUNT = 0 THEN .GOTO SKIPJOB;


/*UPDATE START_DT AND TM*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
FROM CC_COBRA.CC_COBRA_LOAD_STATUS A
SET RUN_ID = A.RUN_ID
,   LOAD_STATUS = 'I'
,   LOAD_START_DT = DATE
,   LOAD_START_TM = TIME
WHERE CC_COBRA.CC_COBRA_LOAD_LOG.GRID_LOAD_ID = 'FR35'
AND   A.RUN_STATUS = 'I'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*STEP 03: UPDATE DATE PARAMETER TABLE*/

/*
CREATE SET TABLE CC_COBRA.WK_FR35_REPORT_DATE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      REPORT_DT DATE FORMAT 'YY/MM/DD')
UNIQUE PRIMARY INDEX ( REPORT_DT );

*/

UPDATE CC_COBRA.WK_FR35_REPORT_DATE
SET REPORT_DT = (SELECT ADD_MONTHS(CAST(((SOURCE_START_DT/100*100)+1)AS DATE),1)-1 FROM CC_COBRA.CC_COBRA_LOAD_START_DT)    
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.WK_FR35_REPORT_DATE INDEX(REPORT_DT);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*DISPLAY DATE INSERTED ABOVE FOR OUTPUT*/

SELECT * FROM CC_COBRA.WK_FR35_REPORT_DATE;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*STEP 04: AGGREGATE DATA*/
/*
CREATE TABLE CC_COBRA.FR35_ME_BAL (
 REPORT_DT DATE
,ORG_TX CHAR(3) 
,CREDIT_CARD_LOGO_CD SMALLINT 
,INT_STATUS_CD CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('8','9','A','D','F','T','X','Z')
,MONTH_END_BAL_AM DECIMAL(15,2))
PRIMARY INDEX(REPORT_DT,ORG_TX,CREDIT_CARD_LOGO_CD);
*/


DELETE FROM CC_COBRA.FR35_ME_BAL WHERE REPORT_DT =(SELECT REPORT_DT FROM CC_COBRA.WK_FR35_REPORT_DATE);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.FR35_ME_BAL
SELECT 
PERIOD_END_DT 
,B.ORG_TX
,B.CREDIT_CARD_LOGO_CD
,INT_STATUS_CD
,SUM(ME_BAL_AM) 
FROM CC_COBRA.CC_AGREEMENT_ME_SNAPSHOT A
JOIN CC_COBRA.WK_FR35_REPORT_DATE D
ON   A.PERIOD_END_DT = D.REPORT_DT
JOIN CC_COBRA.CC_AGREEMENT_ADDED_DATE B
ON   A.AGRMNT_ID = B.AGRMNT_ID
GROUP BY 1,2,3,4;


.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR35_ME_BAL INDEX(REPORT_DT,ORG_TX,CREDIT_CARD_LOGO_CD);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*STEP 05: AGGREGATE DATA*/
/* 
CREATE TABLE CC_COBRA.FR35_TXNS (
 REPORT_DT DATE
,ORG_TX CHAR(3) 
,CREDIT_CARD_LOGO_CD SMALLINT 
,EVENT_ACTVTY_CD CHAR(10) 
,EVENT_AM DECIMAL(15,2))
PRIMARY INDEX(REPORT_DT,ORG_TX,CREDIT_CARD_LOGO_CD,EVENT_ACTVTY_CD);
*/

DELETE FROM CC_COBRA.FR35_TXNS WHERE REPORT_DT =(SELECT REPORT_DT FROM CC_COBRA.WK_FR35_REPORT_DATE);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.FR35_TXNS
SELECT 
A.PERIOD_END_DT 
,B.ORG_TX
,B.CREDIT_CARD_LOGO_CD
,T.EVENT_ACTVTY_CD
,SUM(T.EVENT_AM) 
FROM CC_COBRA.CC_AGREEMENT_ME_SNAPSHOT A
JOIN CC_COBRA.WK_FR35_REPORT_DATE D
ON   A.PERIOD_END_DT = D.REPORT_DT
JOIN CC_COBRA.CC_AGREEMENT_ADDED_DATE B
ON   A.AGRMNT_ID = B.AGRMNT_ID
JOIN CC_COBRA.CC_MONETARY_TRANSACTION_LM T  /*FROM FR20*/
ON   A.AGRMNT_ID = T.AGRMNT_ID
GROUP BY 1,2,3,4;


.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR35_TXNS INDEX(REPORT_DT,ORG_TX,CREDIT_CARD_LOGO_CD,EVENT_ACTVTY_CD);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*FOR EXCEL*/

/*

*/


/*UPDATE THE LOG TABLE IF IT HAS RUN OK!*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  CURRENT_LOAD_DT = (SELECT START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , UPDATE_DT = DATE
   , UPDATE_TM = TIME
   , LOAD_STATUS = 'C'
WHERE GRID_LOAD_ID = 'FR35'
;

SELECT GRID_LOAD_ID, CURRENT_BUS_DT, CURRENT_LOAD_DT   
FROM CC_COBRA.CC_COBRA_LOAD_LOG WHERE GRID_LOAD_ID = 'FR35';

.QUIT;

.LABEL SKIPJOB;

.QUIT;

.LABEL GRIDERROR;

.QUIT;

.LABEL FOUNDERROR;

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  LOAD_STATUS = 'F'
WHERE GRID_LOAD_ID = 'FR35'
;

.QUIT 0;

