/************************************************************************/
/*JOB:      FR36 - SCHEME BY TRANSACTIONS AND TXN TYPE                  */
/*VERSION:  FR36v02 - bw changes.sql                                    */
/*DATE VERSION IMPLEMENTED: 2018-09-30                                  */
/*DEPENDENCIES:                                                         */
/*C01J01                                                                */
/*FR14                                                                  */
/*FR15                                                                  */
/************************************************************************/

.SET ERRORLEVEL (2641,3603) SEVERITY 4, UNKNOWN SEVERITY 8

SET QUERY_BAND = 'ApplicationName=CC_Finance_daily_run;JobID=GRFD043;Worktype=TripleR;Version=LBG;' FOR SESSION;

DATABASE CC_COBRA;

/*STEP 01: CHECK PRIOR JOBS FOR COMPLETION*/

/*INITIAL CHECKS TO SEE IF DAILY LOAD IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'C01J01';


.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF FR14 IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'FR14';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF FR15 IS SUCCESSFUL*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'FR15';

.IF ACTIVITYCOUNT = 0 THEN .GOTO GRIDERROR;

/*INITIAL CHECKS TO SEE IF THIS JOB HAS ALREADY RUN SUCCESSFULLY*/

SELECT * FROM CC_COBRA.CC_COBRA_LOAD_LOG 
WHERE CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
AND   GRID_LOAD_ID = 'FR36';

.IF ACTIVITYCOUNT <> 0 THEN .GOTO SKIPJOB;

/*STEP 02: CHECKS TO SEE IF WORKING DAY IS WD1 */

SELECT * FROM CC_COBRA.GRID_REPORTS_CONTROL 
WHERE (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT) = PRIOR_WORKDAY_DT
AND WORKDAY_OF_MONTH = 1;

.IF ACTIVITYCOUNT = 0 THEN .GOTO SKIPJOB;

/*UPDATE START_DT AND TM*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
FROM CC_COBRA.CC_COBRA_LOAD_STATUS A
SET RUN_ID = A.RUN_ID
,   LOAD_STATUS = 'I'
,   LOAD_START_DT = DATE
,   LOAD_START_TM = TIME
WHERE CC_COBRA.CC_COBRA_LOAD_LOG.GRID_LOAD_ID = 'FR36'
AND   A.RUN_STATUS = 'I'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

/*
CREATE TABLE CC_COBRA.FR36_SCHEMES (
SCHEME CHAR(5)
)UNIQUE PRIMARY INDEX(SCHEME);

INSERT INTO CC_COBRA.FR36_SCHEMES SELECT 'AMEX';
INSERT INTO CC_COBRA.FR36_SCHEMES SELECT 'VISA';
INSERT INTO CC_COBRA.FR36_SCHEMES SELECT 'MCARD';
*/

/*
CREATE TABLE CC_COBRA.FR36_TXN_REPORT_SUMMARY (
ORG CHAR(3) 
,LOGO_CD SMALLINT 
,SCHEME CHAR(5)
,PERIOD_END_DT DATE
,RETAIL_AM DECIMAL(15,2)
,RETAIL_CT INT
,CASH_AM DECIMAL(15,2)
,CASH_CT INT
,BT_AM DECIMAL(15,2)
,BT_CT INT
) 
UNIQUE PRIMARY INDEX(ORG, LOGO_CD,SCHEME,PERIOD_END_DT)
;
*/

DELETE FROM CC_COBRA.FR36_TXN_REPORT_SUMMARY ALL;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

INSERT INTO CC_COBRA.FR36_TXN_REPORT_SUMMARY
SELECT 
A.ORG
,A.LOGO_CD
,S.SCHEME
,A.PERIOD_END_DT
,SUM(
 CASE WHEN S.SCHEME = 'AMEX' THEN RETAIL_A_UK_AM+RETAIL_A_FOREGN_AM 
      WHEN S.SCHEME = 'MCARD' THEN RETAIL_M_UK_AM+RETAIL_M_FOREGN_AM 
      WHEN S.SCHEME = 'VISA' THEN RETAIL_V_UK_AM+RETAIL_V_FOREGN_AM 
      ELSE 0 END) AS RETAIL_AM
,SUM(
 CASE WHEN S.SCHEME = 'AMEX' THEN RETAIL_A_UK_CT+RETAIL_A_FOREGN_CT 
      WHEN S.SCHEME = 'MCARD' THEN RETAIL_M_UK_CT+RETAIL_M_FOREGN_CT
      WHEN S.SCHEME = 'VISA' THEN RETAIL_V_UK_CT+RETAIL_V_FOREGN_CT 
      ELSE 0 END) AS RETAIL_CT
,SUM(
 CASE WHEN S.SCHEME = 'AMEX' THEN CASH_A_UK_AM+CASH_A_FOREGN_AM 
      WHEN S.SCHEME = 'MCARD' THEN CASH_M_UK_AM+CASH_M_FOREGN_AM 
      WHEN S.SCHEME = 'VISA' THEN CASH_V_UK_AM+CASH_V_FOREGN_AM 
      ELSE 0 END) AS CASH_AM
,SUM(
 CASE WHEN S.SCHEME = 'AMEX' THEN CASH_A_UK_CT+CASH_A_FOREGN_CT 
      WHEN S.SCHEME = 'MCARD' THEN CASH_M_UK_CT+CASH_M_FOREGN_CT
      WHEN S.SCHEME = 'VISA' THEN CASH_V_UK_CT+CASH_V_FOREGN_CT 
      ELSE 0 END) AS CASH_CT
,SUM(
 CASE WHEN S.SCHEME = 'AMEX' AND B.SCHEME = 'A' THEN BALANC_TRNSFR_AM+PROMO_CHEQUE_AM+CONVNC_CHEQUE_AM+MONEY_TRNSFR_AM
      WHEN S.SCHEME = 'MCARD' AND B.SCHEME = 'M' THEN BALANC_TRNSFR_AM+PROMO_CHEQUE_AM+CONVNC_CHEQUE_AM+MONEY_TRNSFR_AM
      WHEN S.SCHEME = 'VISA' AND B.SCHEME = 'V' THEN BALANC_TRNSFR_AM+PROMO_CHEQUE_AM+CONVNC_CHEQUE_AM+MONEY_TRNSFR_AM
      ELSE 0 END) AS BT_AM
,SUM(
 CASE WHEN S.SCHEME = 'AMEX' AND B.SCHEME = 'A' THEN BALANC_TRNSFR_CT+PROMO_CHEQUE_CT+CONVNC_CHEQUE_CT+MONEY_TRNSFR_CT
      WHEN S.SCHEME = 'MCARD' AND B.SCHEME = 'M' THEN BALANC_TRNSFR_CT+PROMO_CHEQUE_CT+CONVNC_CHEQUE_CT+MONEY_TRNSFR_CT
      WHEN S.SCHEME = 'VISA' AND B.SCHEME = 'V' THEN BALANC_TRNSFR_CT+PROMO_CHEQUE_CT+CONVNC_CHEQUE_CT+MONEY_TRNSFR_CT
      ELSE 0 END) AS BT_CT     

FROM CC_COBRA.FR15_NEW_BALANCE_WALK_AGG A
JOIN CC_COBRA.FR14_PRODUCT_SCHEME B
ON   A.ORG = B.ORG_TX
AND  A.LOGO_CD = B.LOGO_VL
CROSS JOIN CC_COBRA.FR36_SCHEMES S
GROUP BY 1,2,3,4
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

COLLECT STATS ON CC_COBRA.FR36_TXN_REPORT_SUMMARY INDEX(ORG, LOGO_CD,SCHEME,PERIOD_END_DT);

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;


/*FOR EXCEL*/
/*
SELECT *
FROM (
SELECT 
CASE WHEN ORG = '120' THEN 'LTSB'
WHEN TRIM(ORG)||TRIM(LOGO_CD) = '190505' THEN 'PREF'
WHEN ORG = '190' THEN 'BOS'
WHEN ORG = '195' THEN 'HCS'
ELSE 'OTHER'
END AS HERITAGE
,ORG
,SCHEME
,PERIOD_END_DT
,SUM(RETAIL_AM) AS RETAIL_AM
,SUM(RETAIL_CT) AS RETAIL_CT
,SUM(CASH_AM) AS CASH_AM
,SUM(CASH_CT) AS CASH_CT
,SUM(BT_AM) AS BT_AM
,SUM(BT_CT) AS BT_CT
FROM CC_COBRA.FR36_TXN_REPORT_SUMMARY
GROUP BY 1,2,3,4
) A
ORDER BY 1,2,3,4 DESC;
*/


/*UPDATE THE LOG TABLE IF IT HAS RUN OK!*/

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  CURRENT_LOAD_DT = (SELECT START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , CURRENT_BUS_DT = (SELECT SOURCE_START_DT FROM CC_COBRA.CC_COBRA_LOAD_START_DT)
   , UPDATE_DT = DATE
   , UPDATE_TM = TIME
   , LOAD_STATUS = 'C'
WHERE GRID_LOAD_ID = 'FR36'
;

.IF ERRORCODE <> 0 THEN .GOTO FOUNDERROR;

SELECT GRID_LOAD_ID, CURRENT_BUS_DT, CURRENT_LOAD_DT   
FROM CC_COBRA.CC_COBRA_LOAD_LOG WHERE GRID_LOAD_ID = 'FR36';

.QUIT;

.LABEL SKIPJOB;

.QUIT;

.LABEL GRIDERROR;

.QUIT;

.LABEL FOUNDERROR;

UPDATE CC_COBRA.CC_COBRA_LOAD_LOG
SET  LOAD_STATUS = 'F'
WHERE GRID_LOAD_ID = 'FR36'
;

.QUIT 0;

